import type { DomainDefinition, TableDef } from './types.js';
import { col, generateSummaryTable } from '../generator.js';

/* ================================================================
 * ODS Layer — ~45 tables: raw operational data from source systems
 * ================================================================ */

const odsTables: TableDef[] = [
  // ---------- Supplier Management ----------
  {
    name: 'ods_supplier',
    comment: '供应商主数据',
    layer: 'ods',
    columns: [
      col.id('供应商ID'),
      col.varchar('supplier_code', 50, '供应商编码', { isNullable: false }),
      col.varchar('supplier_name', 200, '供应商名称', { isNullable: false }),
      col.varchar('supplier_type', 50, '供应商类型: 原材料/包装/设备/服务'),
      col.varchar('contact_name', 100, '联系人姓名'),
      col.varchar('contact_phone', 30, '联系电话'),
      col.varchar('contact_email', 100, '联系邮箱'),
      col.varchar('country', 50, '国家'),
      col.varchar('province', 50, '省份'),
      col.varchar('city', 50, '城市'),
      col.text('address', '详细地址'),
      col.varchar('payment_terms', 50, '付款条件: NET30/NET60/COD'),
      col.varchar('currency', 10, '结算币种'),
      col.int('lead_time_days', '标准交货提前期(天)'),
      col.decimal('credit_limit', '18,2', '信用额度'),
      col.decimal('quality_rating', '5,2', '质量评分'),
      col.decimal('delivery_rating', '5,2', '交货评分'),
      col.status('供应商状态', '合格/待审核/暂停/淘汰'),
      col.date('cooperation_start_date', '合作开始日期'),
      col.bool('is_strategic', '是否战略供应商'),
      col.createdAt(),
      col.updatedAt(),
    ],
  },
  {
    name: 'ods_supplier_certification',
    comment: '供应商资质认证',
    layer: 'ods',
    columns: [
      col.id('认证ID'),
      col.fk('supplier_id', 'ods_supplier', '供应商ID'),
      col.varchar('cert_type', 50, '认证类型: ISO9001/ISO14001/IATF16949/HACCP'),
      col.varchar('cert_number', 100, '证书编号'),
      col.date('issue_date', '颁发日期'),
      col.date('expiry_date', '到期日期'),
      col.varchar('issuing_body', 100, '颁发机构'),
      col.status('认证状态', '有效/即将到期/已过期'),
      col.createdAt(),
    ],
  },
  {
    name: 'ods_supplier_evaluation',
    comment: '供应商评估记录',
    layer: 'ods',
    columns: [
      col.id('评估ID'),
      col.fk('supplier_id', 'ods_supplier', '供应商ID'),
      col.varchar('eval_period', 20, '评估周期: 2024-Q1'),
      col.decimal('quality_score', '5,2', '质量得分'),
      col.decimal('delivery_score', '5,2', '交付得分'),
      col.decimal('cost_score', '5,2', '成本得分'),
      col.decimal('service_score', '5,2', '服务得分'),
      col.decimal('total_score', '5,2', '综合得分'),
      col.varchar('grade', 10, '评级: A/B/C/D'),
      col.text('comments', '评估意见'),
      col.date('eval_date', '评估日期'),
      col.createdAt(),
    ],
  },
  {
    name: 'ods_supplier_contract',
    comment: '供应商合同',
    layer: 'ods',
    columns: [
      col.id('合同ID'),
      col.fk('supplier_id', 'ods_supplier', '供应商ID'),
      col.varchar('contract_no', 50, '合同编号', { isNullable: false }),
      col.varchar('contract_type', 30, '合同类型: 年度框架/单次采购/长期协议'),
      col.date('start_date', '合同开始日期'),
      col.date('end_date', '合同结束日期'),
      col.decimal('contract_amount', '18,2', '合同金额'),
      col.varchar('currency', 10, '币种'),
      col.status('合同状态', '草案/生效/到期/终止'),
      col.text('terms', '合同条款概要'),
      col.createdAt(),
      col.updatedAt(),
    ],
  },

  // ---------- Raw Materials & BOM ----------
  {
    name: 'ods_material',
    comment: '物料主数据',
    layer: 'ods',
    columns: [
      col.id('物料ID'),
      col.varchar('material_code', 50, '物料编码', { isNullable: false }),
      col.varchar('material_name', 200, '物料名称', { isNullable: false }),
      col.varchar('material_type', 50, '物料类型: 原材料/半成品/成品/包装材料/辅料'),
      col.varchar('category', 50, '物料分类'),
      col.varchar('sub_category', 50, '物料子分类'),
      col.varchar('unit', 20, '基本计量单位'),
      col.varchar('sku', 50, 'SKU编码'),
      col.decimal('unit_cost', '18,4', '单位成本'),
      col.decimal('unit_weight', '12,4', '单位重量(kg)'),
      col.varchar('storage_condition', 50, '存储条件: 常温/冷藏/冷冻/避光'),
      col.int('shelf_life_days', '保质期(天)'),
      col.int('min_order_qty', '最小订购量'),
      col.int('safety_stock', '安全库存量'),
      col.int('reorder_point', '补货点'),
      col.bool('is_hazardous', '是否危险品'),
      col.status('物料状态', '有效/停用/待审'),
      col.createdAt(),
      col.updatedAt(),
    ],
  },
  {
    name: 'ods_bom',
    comment: '物料清单(BOM)表头',
    layer: 'ods',
    columns: [
      col.id('BOM ID'),
      col.fk('product_material_id', 'ods_material', '成品物料ID'),
      col.varchar('bom_version', 20, 'BOM版本号'),
      col.varchar('bom_type', 20, 'BOM类型: 标准/替代/工程'),
      col.int('level_count', 'BOM层级数'),
      col.status('BOM状态', '草案/生效/废弃'),
      col.date('effective_date', '生效日期'),
      col.date('expiry_date', '失效日期'),
      col.createdAt(),
      col.updatedAt(),
    ],
  },
  {
    name: 'ods_bom_detail',
    comment: '物料清单明细',
    layer: 'ods',
    columns: [
      col.id('明细ID'),
      col.fk('bom_id', 'ods_bom', 'BOM ID'),
      col.fk('component_material_id', 'ods_material', '子件物料ID'),
      col.int('level', 'BOM层级'),
      col.decimal('quantity', '12,4', '用量'),
      col.decimal('waste_rate', '5,4', '损耗率'),
      col.varchar('unit', 20, '计量单位'),
      col.bool('is_substitute', '是否替代料'),
      col.fk('substitute_for_id', 'ods_bom_detail', '替代的原明细ID'),
      col.createdAt(),
    ],
  },

  // ---------- Procurement / Purchasing ----------
  {
    name: 'ods_purchase_requisition',
    comment: '采购申请单',
    layer: 'ods',
    columns: [
      col.id('申请单ID'),
      col.varchar('req_no', 50, '申请单号', { isNullable: false }),
      col.varchar('req_type', 30, '申请类型: 计划采购/紧急采购/补货'),
      col.fk('requester_id', 'ods_employee', '申请人ID'),
      col.fk('department_id', 'ods_department', '申请部门ID'),
      col.date('required_date', '需求日期'),
      col.text('reason', '申请原因'),
      col.decimal('estimated_amount', '18,2', '预估金额'),
      col.status('申请状态', '草案/待审批/已批准/已拒绝/已转采购'),
      col.createdAt(),
      col.updatedAt(),
    ],
  },
  {
    name: 'ods_purchase_requisition_item',
    comment: '采购申请明细',
    layer: 'ods',
    columns: [
      col.id('明细ID'),
      col.fk('requisition_id', 'ods_purchase_requisition', '申请单ID'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.int('quantity', '申请数量'),
      col.varchar('unit', 20, '单位'),
      col.decimal('estimated_price', '18,4', '预估单价'),
      col.date('required_date', '期望到货日期'),
      col.text('specification', '规格要求'),
      col.createdAt(),
    ],
  },
  {
    name: 'ods_purchase_order',
    comment: '采购订单',
    layer: 'ods',
    columns: [
      col.id('采购订单ID'),
      col.varchar('po_no', 50, '采购订单号', { isNullable: false }),
      col.fk('supplier_id', 'ods_supplier', '供应商ID'),
      col.fk('requisition_id', 'ods_purchase_requisition', '关联申请单ID'),
      col.varchar('po_type', 30, '订单类型: 标准/框架/紧急'),
      col.date('order_date', '下单日期'),
      col.date('expected_delivery_date', '预期交货日期'),
      col.decimal('total_amount', '18,2', '订单总金额'),
      col.decimal('tax_amount', '18,2', '税额'),
      col.varchar('currency', 10, '币种'),
      col.varchar('payment_terms', 50, '付款条件'),
      col.varchar('delivery_terms', 50, '交货条款: FOB/CIF/EXW'),
      col.fk('buyer_id', 'ods_employee', '采购员ID'),
      col.status('订单状态', '草案/已确认/部分到货/全部到货/已关闭/已取消'),
      col.createdAt(),
      col.updatedAt(),
    ],
  },
  {
    name: 'ods_purchase_order_item',
    comment: '采购订单明细',
    layer: 'ods',
    columns: [
      col.id('明细ID'),
      col.fk('po_id', 'ods_purchase_order', '采购订单ID'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.int('quantity', '采购数量'),
      col.int('received_quantity', '已收货数量'),
      col.decimal('unit_price', '18,4', '采购单价'),
      col.decimal('line_amount', '18,2', '行金额'),
      col.decimal('tax_rate', '5,2', '税率'),
      col.date('promised_date', '承诺交期'),
      col.varchar('unit', 20, '单位'),
      col.status('行状态', '待发货/在途/部分收货/已收货/已取消'),
      col.createdAt(),
    ],
  },

  // ---------- Inventory Management ----------
  {
    name: 'ods_warehouse',
    comment: '仓库主数据',
    layer: 'ods',
    columns: [
      col.id('仓库ID'),
      col.varchar('warehouse_code', 30, '仓库编码', { isNullable: false }),
      col.varchar('warehouse_name', 100, '仓库名称'),
      col.varchar('warehouse_type', 30, '仓库类型: 原料仓/成品仓/中转仓/冷库'),
      col.varchar('region', 50, '所属区域'),
      col.varchar('city', 50, '所在城市'),
      col.text('address', '详细地址'),
      col.decimal('total_area', '12,2', '总面积(㎡)'),
      col.decimal('usable_area', '12,2', '可用面积(㎡)'),
      col.int('total_positions', '总库位数'),
      col.decimal('min_temperature', '5,1', '最低温度(℃)'),
      col.decimal('max_temperature', '5,1', '最高温度(℃)'),
      col.varchar('manager', 100, '仓库负责人'),
      col.status('仓库状态', '正常/维护/停用'),
      col.createdAt(),
      col.updatedAt(),
    ],
  },
  {
    name: 'ods_warehouse_zone',
    comment: '仓库库区',
    layer: 'ods',
    columns: [
      col.id('库区ID'),
      col.fk('warehouse_id', 'ods_warehouse', '仓库ID'),
      col.varchar('zone_code', 30, '库区编码'),
      col.varchar('zone_name', 100, '库区名称'),
      col.varchar('zone_type', 30, '库区类型: 存储区/拣货区/暂存区/退货区'),
      col.decimal('area', '12,2', '面积(㎡)'),
      col.int('position_count', '库位数量'),
      col.varchar('storage_condition', 30, '存储条件: 常温/冷藏/冷冻'),
      col.status('库区状态', '正常/满仓/维护'),
      col.createdAt(),
    ],
  },
  {
    name: 'ods_storage_location',
    comment: '库位信息',
    layer: 'ods',
    columns: [
      col.id('库位ID'),
      col.fk('zone_id', 'ods_warehouse_zone', '库区ID'),
      col.varchar('location_code', 30, '库位编码'),
      col.varchar('shelf_no', 20, '货架号'),
      col.int('layer_no', '层号'),
      col.int('column_no', '列号'),
      col.decimal('max_weight', '10,2', '最大承重(kg)'),
      col.decimal('max_volume', '10,2', '最大容积(m³)'),
      col.status('库位状态', '空闲/占用/锁定/禁用'),
      col.createdAt(),
    ],
  },
  {
    name: 'ods_inventory',
    comment: '库存主记录',
    layer: 'ods',
    columns: [
      col.id('库存记录ID'),
      col.fk('warehouse_id', 'ods_warehouse', '仓库ID'),
      col.fk('location_id', 'ods_storage_location', '库位ID'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.varchar('batch_no', 50, '批次号'),
      col.int('quantity', '库存数量'),
      col.int('available_quantity', '可用数量'),
      col.int('locked_quantity', '锁定数量'),
      col.int('defective_quantity', '不良品数量'),
      col.date('production_date', '生产日期'),
      col.date('expiry_date', '过期日期'),
      col.decimal('unit_cost', '18,4', '库存单位成本'),
      col.status('库存状态', '正常/即将过期/已过期/冻结'),
      col.updatedAt(),
    ],
  },
  {
    name: 'ods_inventory_transaction',
    comment: '库存事务流水',
    layer: 'ods',
    columns: [
      col.id('事务ID'),
      col.fk('warehouse_id', 'ods_warehouse', '仓库ID'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.varchar('transaction_type', 30, '事务类型: 入库/出库/调拨/盘点/报损'),
      col.varchar('source_doc_type', 30, '来源单据类型'),
      col.varchar('source_doc_no', 50, '来源单据号'),
      col.varchar('batch_no', 50, '批次号'),
      col.int('quantity', '事务数量'),
      col.varchar('direction', 10, '方向: IN/OUT'),
      col.decimal('unit_cost', '18,4', '单位成本'),
      col.varchar('operator', 50, '操作人'),
      col.timestamp('transaction_time', '事务时间'),
      col.text('remark', '备注'),
      col.createdAt(),
    ],
  },
  {
    name: 'ods_stock_count',
    comment: '库存盘点单',
    layer: 'ods',
    columns: [
      col.id('盘点单ID'),
      col.varchar('count_no', 50, '盘点单号', { isNullable: false }),
      col.fk('warehouse_id', 'ods_warehouse', '仓库ID'),
      col.varchar('count_type', 30, '盘点类型: 全盘/抽盘/循环盘点'),
      col.date('count_date', '盘点日期'),
      col.varchar('counter', 50, '盘点人'),
      col.varchar('reviewer', 50, '复核人'),
      col.status('盘点状态', '进行中/待审核/已完成'),
      col.createdAt(),
    ],
  },
  {
    name: 'ods_stock_count_detail',
    comment: '盘点明细',
    layer: 'ods',
    columns: [
      col.id('明细ID'),
      col.fk('count_id', 'ods_stock_count', '盘点单ID'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.fk('location_id', 'ods_storage_location', '库位ID'),
      col.varchar('batch_no', 50, '批次号'),
      col.int('system_quantity', '系统数量'),
      col.int('actual_quantity', '实盘数量'),
      col.int('difference', '差异数量'),
      col.text('reason', '差异原因'),
      col.createdAt(),
    ],
  },

  // ---------- Receiving & Inbound ----------
  {
    name: 'ods_receiving_order',
    comment: '收货单',
    layer: 'ods',
    columns: [
      col.id('收货单ID'),
      col.varchar('receiving_no', 50, '收货单号', { isNullable: false }),
      col.fk('po_id', 'ods_purchase_order', '关联采购订单ID'),
      col.fk('warehouse_id', 'ods_warehouse', '收货仓库ID'),
      col.fk('supplier_id', 'ods_supplier', '供应商ID'),
      col.date('receiving_date', '收货日期'),
      col.varchar('receiver', 50, '收货人'),
      col.status('收货状态', '待验收/验收中/已入库/部分退回'),
      col.text('remark', '备注'),
      col.createdAt(),
    ],
  },
  {
    name: 'ods_receiving_order_item',
    comment: '收货单明细',
    layer: 'ods',
    columns: [
      col.id('明细ID'),
      col.fk('receiving_id', 'ods_receiving_order', '收货单ID'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.int('expected_quantity', '预期数量'),
      col.int('received_quantity', '实收数量'),
      col.int('rejected_quantity', '拒收数量'),
      col.varchar('batch_no', 50, '批次号'),
      col.varchar('unit', 20, '单位'),
      col.text('rejection_reason', '拒收原因'),
      col.createdAt(),
    ],
  },

  // ---------- Quality Control ----------
  {
    name: 'ods_quality_inspection',
    comment: '质量检验单',
    layer: 'ods',
    columns: [
      col.id('检验单ID'),
      col.varchar('inspection_no', 50, '检验单号', { isNullable: false }),
      col.varchar('inspection_type', 30, '检验类型: 来料检/过程检/成品检/出货检'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.varchar('batch_no', 50, '批次号'),
      col.varchar('source_doc_no', 50, '来源单据号'),
      col.int('sample_size', '抽样数量'),
      col.int('inspected_quantity', '检验数量'),
      col.int('qualified_quantity', '合格数量'),
      col.int('defective_quantity', '不合格数量'),
      col.decimal('defect_rate', '5,4', '不良率'),
      col.varchar('inspector', 50, '检验员'),
      col.varchar('result', 20, '检验结果: 合格/不合格/让步接收'),
      col.status('检验状态', '待检/检验中/已完成'),
      col.timestamp('inspection_time', '检验时间'),
      col.text('remark', '备注'),
      col.createdAt(),
    ],
  },
  {
    name: 'ods_quality_inspection_item',
    comment: '质量检验项明细',
    layer: 'ods',
    columns: [
      col.id('明细ID'),
      col.fk('inspection_id', 'ods_quality_inspection', '检验单ID'),
      col.varchar('check_item', 100, '检验项目'),
      col.varchar('standard_value', 100, '标准值'),
      col.varchar('actual_value', 100, '实测值'),
      col.varchar('tolerance', 50, '公差范围'),
      col.bool('is_qualified', '是否合格'),
      col.text('remark', '备注'),
      col.createdAt(),
    ],
  },
  {
    name: 'ods_defect_record',
    comment: '质量缺陷记录',
    layer: 'ods',
    columns: [
      col.id('缺陷ID'),
      col.fk('inspection_id', 'ods_quality_inspection', '检验单ID'),
      col.varchar('defect_code', 30, '缺陷编码'),
      col.varchar('defect_type', 50, '缺陷类型: 外观/尺寸/性能/功能'),
      col.varchar('severity', 20, '严重等级: 致命/严重/一般/轻微'),
      col.int('quantity', '缺陷数量'),
      col.text('description', '缺陷描述'),
      col.text('root_cause', '根因分析'),
      col.text('corrective_action', '纠正措施'),
      col.varchar('responsible_party', 100, '责任方'),
      col.createdAt(),
    ],
  },

  // ---------- Logistics / Shipping ----------
  {
    name: 'ods_shipment_order',
    comment: '发货单/物流订单',
    layer: 'ods',
    columns: [
      col.id('发货单ID'),
      col.varchar('shipment_no', 50, '发货单号', { isNullable: false }),
      col.varchar('shipment_type', 30, '发货类型: 整车/零担/快递/冷链'),
      col.varchar('source_doc_no', 50, '来源单据号'),
      col.fk('origin_warehouse_id', 'ods_warehouse', '发货仓库ID'),
      col.varchar('destination', 200, '目的地'),
      col.varchar('consignee', 100, '收货人'),
      col.varchar('consignee_phone', 30, '收货人电话'),
      col.fk('carrier_id', 'ods_carrier', '承运商ID'),
      col.varchar('tracking_no', 100, '物流追踪号'),
      col.date('ship_date', '发货日期'),
      col.date('expected_arrival_date', '预计到达日期'),
      col.date('actual_arrival_date', '实际到达日期'),
      col.decimal('freight_cost', '12,2', '运费'),
      col.decimal('total_weight', '12,2', '总重量(kg)'),
      col.decimal('total_volume', '12,4', '总体积(m³)'),
      col.status('物流状态', '待发货/已发货/运输中/已签收/异常'),
      col.createdAt(),
      col.updatedAt(),
    ],
  },
  {
    name: 'ods_shipment_item',
    comment: '发货单明细',
    layer: 'ods',
    columns: [
      col.id('明细ID'),
      col.fk('shipment_id', 'ods_shipment_order', '发货单ID'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.varchar('batch_no', 50, '批次号'),
      col.int('quantity', '发货数量'),
      col.decimal('weight', '12,2', '重量(kg)'),
      col.decimal('volume', '12,4', '体积(m³)'),
      col.createdAt(),
    ],
  },
  {
    name: 'ods_carrier',
    comment: '承运商主数据',
    layer: 'ods',
    columns: [
      col.id('承运商ID'),
      col.varchar('carrier_code', 30, '承运商编码', { isNullable: false }),
      col.varchar('carrier_name', 100, '承运商名称'),
      col.varchar('carrier_type', 30, '承运商类型: 公路/铁路/航空/海运/快递'),
      col.varchar('contact_name', 100, '联系人'),
      col.varchar('contact_phone', 30, '联系电话'),
      col.decimal('on_time_rate', '5,4', '准时率'),
      col.decimal('damage_rate', '5,4', '破损率'),
      col.status('承运商状态', '合作中/暂停/终止'),
      col.createdAt(),
      col.updatedAt(),
    ],
  },
  {
    name: 'ods_shipment_tracking',
    comment: '物流追踪记录',
    layer: 'ods',
    columns: [
      col.id('追踪ID'),
      col.fk('shipment_id', 'ods_shipment_order', '发货单ID'),
      col.varchar('tracking_status', 50, '追踪状态: 已揽收/运输中/中转/派送中/已签收'),
      col.varchar('location', 200, '当前位置'),
      col.timestamp('event_time', '事件时间'),
      col.text('description', '详细描述'),
      col.createdAt(),
    ],
  },

  // ---------- Production Planning ----------
  {
    name: 'ods_production_plan',
    comment: '生产计划',
    layer: 'ods',
    columns: [
      col.id('计划ID'),
      col.varchar('plan_no', 50, '计划编号', { isNullable: false }),
      col.varchar('plan_type', 30, '计划类型: 月计划/周计划/日计划'),
      col.fk('product_material_id', 'ods_material', '产品物料ID'),
      col.int('planned_quantity', '计划产量'),
      col.int('actual_quantity', '实际产量'),
      col.date('plan_start_date', '计划开始日期'),
      col.date('plan_end_date', '计划结束日期'),
      col.fk('production_line_id', 'ods_production_line', '生产线ID'),
      col.int('priority', '优先级: 1-5'),
      col.status('计划状态', '草案/已排产/执行中/已完成/已取消'),
      col.createdAt(),
      col.updatedAt(),
    ],
  },
  {
    name: 'ods_production_line',
    comment: '生产线信息',
    layer: 'ods',
    columns: [
      col.id('生产线ID'),
      col.varchar('line_code', 30, '生产线编码'),
      col.varchar('line_name', 100, '生产线名称'),
      col.varchar('line_type', 30, '生产线类型'),
      col.fk('workshop_id', 'ods_workshop', '车间ID'),
      col.int('capacity_per_hour', '每小时产能'),
      col.decimal('utilization_rate', '5,2', '利用率'),
      col.status('生产线状态', '运行/维护/停产'),
      col.createdAt(),
    ],
  },
  {
    name: 'ods_workshop',
    comment: '车间信息',
    layer: 'ods',
    columns: [
      col.id('车间ID'),
      col.varchar('workshop_code', 30, '车间编码'),
      col.varchar('workshop_name', 100, '车间名称'),
      col.varchar('factory', 100, '所属工厂'),
      col.decimal('area', '12,2', '面积(㎡)'),
      col.varchar('manager', 50, '车间主任'),
      col.status('车间状态', '正常/维护/停工'),
      col.createdAt(),
    ],
  },
  {
    name: 'ods_production_order',
    comment: '生产工单',
    layer: 'ods',
    columns: [
      col.id('工单ID'),
      col.varchar('work_order_no', 50, '工单号', { isNullable: false }),
      col.fk('plan_id', 'ods_production_plan', '关联计划ID'),
      col.fk('product_material_id', 'ods_material', '产品物料ID'),
      col.fk('bom_id', 'ods_bom', 'BOM ID'),
      col.int('planned_quantity', '计划数量'),
      col.int('completed_quantity', '完成数量'),
      col.int('scrap_quantity', '报废数量'),
      col.date('start_date', '开始日期'),
      col.date('end_date', '结束日期'),
      col.fk('production_line_id', 'ods_production_line', '生产线ID'),
      col.status('工单状态', '已创建/已下达/执行中/已完成/已关闭'),
      col.createdAt(),
      col.updatedAt(),
    ],
  },

  // ---------- Demand Forecasting ----------
  {
    name: 'ods_demand_forecast',
    comment: '需求预测',
    layer: 'ods',
    columns: [
      col.id('预测ID'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.varchar('forecast_period', 20, '预测周期: 2024-01'),
      col.varchar('forecast_type', 30, '预测类型: 统计预测/人工调整/综合'),
      col.int('forecast_quantity', '预测数量'),
      col.int('actual_quantity', '实际数量'),
      col.decimal('accuracy_rate', '5,4', '预测准确率'),
      col.decimal('confidence_level', '5,2', '置信度'),
      col.varchar('model_name', 50, '预测模型名称'),
      col.date('created_date', '创建日期'),
      col.createdAt(),
    ],
  },
  {
    name: 'ods_safety_stock_config',
    comment: '安全库存配置',
    layer: 'ods',
    columns: [
      col.id('配置ID'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.fk('warehouse_id', 'ods_warehouse', '仓库ID'),
      col.int('safety_stock', '安全库存量'),
      col.int('reorder_point', '补货点'),
      col.int('max_stock', '最大库存量'),
      col.int('min_stock', '最小库存量'),
      col.int('economic_order_qty', '经济订货量'),
      col.varchar('replenishment_method', 30, '补货方式: 定量补货/定期补货/MRP驱动'),
      col.updatedAt(),
    ],
  },

  // ---------- Returns Processing ----------
  {
    name: 'ods_return_order',
    comment: '退货单',
    layer: 'ods',
    columns: [
      col.id('退货单ID'),
      col.varchar('return_no', 50, '退货单号', { isNullable: false }),
      col.varchar('return_type', 30, '退货类型: 采购退货/销售退货/内部退货'),
      col.varchar('source_doc_no', 50, '来源单据号'),
      col.fk('warehouse_id', 'ods_warehouse', '退入仓库ID'),
      col.varchar('return_reason_code', 30, '退货原因编码'),
      col.text('return_reason', '退货原因'),
      col.varchar('applicant', 50, '申请人'),
      col.decimal('refund_amount', '18,2', '退款金额'),
      col.status('退货状态', '申请中/已批准/退货中/已入库/已完成/已拒绝'),
      col.createdAt(),
      col.updatedAt(),
    ],
  },
  {
    name: 'ods_return_order_item',
    comment: '退货单明细',
    layer: 'ods',
    columns: [
      col.id('明细ID'),
      col.fk('return_id', 'ods_return_order', '退货单ID'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.varchar('batch_no', 50, '批次号'),
      col.int('return_quantity', '退货数量'),
      col.int('received_quantity', '实收数量'),
      col.varchar('quality_result', 30, '质量判定: 可二次利用/报废/返修'),
      col.text('remark', '备注'),
      col.createdAt(),
    ],
  },

  // ---------- Cold Chain Monitoring ----------
  {
    name: 'ods_cold_chain_device',
    comment: '冷链监控设备',
    layer: 'ods',
    columns: [
      col.id('设备ID'),
      col.varchar('device_code', 50, '设备编码', { isNullable: false }),
      col.varchar('device_type', 30, '设备类型: 温度传感器/湿度传感器/GPS追踪器'),
      col.varchar('install_location', 100, '安装位置'),
      col.fk('warehouse_id', 'ods_warehouse', '关联仓库ID'),
      col.decimal('min_threshold', '5,1', '最低阈值'),
      col.decimal('max_threshold', '5,1', '最高阈值'),
      col.status('设备状态', '正常/告警/离线/维修'),
      col.createdAt(),
    ],
  },
  {
    name: 'ods_cold_chain_reading',
    comment: '冷链监控读数',
    layer: 'ods',
    columns: [
      col.id('读数ID'),
      col.fk('device_id', 'ods_cold_chain_device', '设备ID'),
      col.decimal('temperature', '5,1', '温度(℃)'),
      col.decimal('humidity', '5,1', '湿度(%)'),
      col.timestamp('reading_time', '采集时间'),
      col.bool('is_alarm', '是否告警'),
      col.varchar('alarm_type', 30, '告警类型: 温度超标/湿度超标'),
      col.createdAt(),
    ],
  },
  {
    name: 'ods_cold_chain_alert',
    comment: '冷链告警记录',
    layer: 'ods',
    columns: [
      col.id('告警ID'),
      col.fk('device_id', 'ods_cold_chain_device', '设备ID'),
      col.varchar('alert_type', 30, '告警类型'),
      col.decimal('alert_value', '5,1', '告警值'),
      col.decimal('threshold_value', '5,1', '阈值'),
      col.varchar('severity', 20, '严重程度: 警告/严重/紧急'),
      col.timestamp('alert_time', '告警时间'),
      col.timestamp('resolve_time', '解除时间'),
      col.varchar('handler', 50, '处理人'),
      col.text('action_taken', '处理措施'),
      col.status('告警状态', '未处理/处理中/已解除'),
      col.createdAt(),
    ],
  },

  // ---------- Cost Management ----------
  {
    name: 'ods_cost_center',
    comment: '成本中心',
    layer: 'ods',
    columns: [
      col.id('成本中心ID'),
      col.varchar('cost_center_code', 30, '成本中心编码', { isNullable: false }),
      col.varchar('cost_center_name', 100, '成本中心名称'),
      col.varchar('cost_type', 30, '成本类型: 采购/仓储/物流/生产/质量'),
      col.fk('parent_id', 'ods_cost_center', '上级成本中心ID'),
      col.varchar('department', 100, '所属部门'),
      col.decimal('budget_amount', '18,2', '预算金额'),
      col.status('状态', '有效/冻结/关闭'),
      col.createdAt(),
    ],
  },
  {
    name: 'ods_cost_record',
    comment: '成本记录流水',
    layer: 'ods',
    columns: [
      col.id('记录ID'),
      col.fk('cost_center_id', 'ods_cost_center', '成本中心ID'),
      col.varchar('cost_category', 50, '成本科目: 材料费/运输费/仓储费/质量损失/人工费'),
      col.varchar('source_doc_type', 30, '来源单据类型'),
      col.varchar('source_doc_no', 50, '来源单据号'),
      col.decimal('amount', '18,2', '金额'),
      col.varchar('currency', 10, '币种'),
      col.date('cost_date', '成本发生日期'),
      col.varchar('cost_period', 20, '成本期间: 2024-01'),
      col.text('description', '描述'),
      col.createdAt(),
    ],
  },

  // ---------- Packaging ----------
  {
    name: 'ods_packaging_spec',
    comment: '包装规格',
    layer: 'ods',
    columns: [
      col.id('规格ID'),
      col.varchar('spec_code', 30, '规格编码'),
      col.varchar('spec_name', 100, '规格名称'),
      col.varchar('packaging_type', 30, '包装类型: 纸箱/木箱/托盘/塑料箱/真空包装'),
      col.decimal('length', '10,2', '长度(cm)'),
      col.decimal('width', '10,2', '宽度(cm)'),
      col.decimal('height', '10,2', '高度(cm)'),
      col.decimal('max_weight', '10,2', '最大承重(kg)'),
      col.int('units_per_package', '每包装单元数'),
      col.fk('material_id', 'ods_material', '包装材料ID'),
      col.createdAt(),
    ],
  },

  // ---------- Employee & Department (referenced) ----------
  {
    name: 'ods_employee',
    comment: '员工信息(供应链相关)',
    layer: 'ods',
    columns: [
      col.id('员工ID'),
      col.varchar('employee_code', 30, '工号', { isNullable: false }),
      col.varchar('employee_name', 50, '姓名'),
      col.fk('department_id', 'ods_department', '部门ID'),
      col.varchar('position', 50, '职位'),
      col.varchar('email', 100, '邮箱'),
      col.varchar('phone', 30, '电话'),
      col.status('状态', '在职/离职'),
      col.createdAt(),
    ],
  },
  {
    name: 'ods_department',
    comment: '部门信息',
    layer: 'ods',
    columns: [
      col.id('部门ID'),
      col.varchar('dept_code', 30, '部门编码'),
      col.varchar('dept_name', 100, '部门名称'),
      col.fk('parent_id', 'ods_department', '上级部门ID'),
      col.varchar('manager', 50, '部门负责人'),
      col.createdAt(),
    ],
  },
];

/* ================================================================
 * DWD Layer — ~40 tables: cleaned, standardized, de-duplicated facts
 * ================================================================ */

const dwdTables: TableDef[] = [
  // ---------- Procurement Facts ----------
  {
    name: 'dwd_fact_purchase_order',
    comment: '采购订单事实表(清洗后)',
    layer: 'dwd',
    columns: [
      col.id('采购订单事实ID'),
      col.varchar('po_no', 50, '采购订单号'),
      col.fk('supplier_id', 'ods_supplier', '供应商ID'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.int('order_quantity', '采购数量'),
      col.int('received_quantity', '到货数量'),
      col.decimal('unit_price', '18,4', '采购单价'),
      col.decimal('line_amount', '18,2', '行金额'),
      col.decimal('tax_amount', '18,2', '税额'),
      col.date('order_date', '下单日期'),
      col.date('expected_date', '预期交货日期'),
      col.date('actual_delivery_date', '实际交货日期'),
      col.int('lead_time_days', '采购提前期(天)'),
      col.bool('is_on_time', '是否按时交货'),
      col.varchar('po_type', 30, '订单类型'),
      col.varchar('order_status', 30, '订单状态'),
      col.ds(),
      col.etlTime(),
    ],
  },
  {
    name: 'dwd_fact_purchase_requisition',
    comment: '采购申请事实表',
    layer: 'dwd',
    columns: [
      col.id('申请事实ID'),
      col.varchar('req_no', 50, '申请单号'),
      col.varchar('req_type', 30, '申请类型'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.int('quantity', '申请数量'),
      col.decimal('estimated_amount', '18,2', '预估金额'),
      col.date('submit_date', '提交日期'),
      col.date('approve_date', '批准日期'),
      col.int('approval_days', '审批耗时(天)'),
      col.varchar('req_status', 30, '申请状态'),
      col.ds(),
      col.etlTime(),
    ],
  },
  {
    name: 'dwd_fact_supplier_price',
    comment: '供应商报价事实表',
    layer: 'dwd',
    columns: [
      col.id('报价事实ID'),
      col.fk('supplier_id', 'ods_supplier', '供应商ID'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.decimal('quoted_price', '18,4', '报价'),
      col.decimal('negotiated_price', '18,4', '协商价'),
      col.decimal('final_price', '18,4', '成交价'),
      col.decimal('savings_rate', '5,4', '节省率'),
      col.varchar('currency', 10, '币种'),
      col.date('quote_date', '报价日期'),
      col.date('effective_date', '生效日期'),
      col.ds(),
      col.etlTime(),
    ],
  },

  // ---------- Inventory Facts ----------
  {
    name: 'dwd_fact_inventory_snapshot',
    comment: '库存快照事实表(每日)',
    layer: 'dwd',
    columns: [
      col.id('快照ID'),
      col.fk('warehouse_id', 'ods_warehouse', '仓库ID'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.varchar('batch_no', 50, '批次号'),
      col.int('quantity', '库存数量'),
      col.int('available_quantity', '可用数量'),
      col.int('locked_quantity', '锁定数量'),
      col.decimal('inventory_value', '18,2', '库存金额'),
      col.decimal('unit_cost', '18,4', '单位成本'),
      col.int('days_on_hand', '库龄(天)'),
      col.bool('is_near_expiry', '是否临期'),
      col.varchar('stock_status', 30, '库存状态'),
      col.ds(),
      col.etlTime(),
    ],
  },
  {
    name: 'dwd_fact_inventory_movement',
    comment: '库存变动事实表',
    layer: 'dwd',
    columns: [
      col.id('变动事实ID'),
      col.fk('warehouse_id', 'ods_warehouse', '仓库ID'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.varchar('movement_type', 30, '变动类型: 入库/出库/调拨/盘盈/盘亏/报损'),
      col.varchar('source_doc_type', 30, '来源单据类型'),
      col.varchar('source_doc_no', 50, '来源单据号'),
      col.int('quantity', '变动数量'),
      col.varchar('direction', 10, '方向: IN/OUT'),
      col.decimal('amount', '18,2', '变动金额'),
      col.timestamp('movement_time', '变动时间'),
      col.ds(),
      col.etlTime(),
    ],
  },
  {
    name: 'dwd_fact_stock_count',
    comment: '盘点事实表',
    layer: 'dwd',
    columns: [
      col.id('盘点事实ID'),
      col.fk('warehouse_id', 'ods_warehouse', '仓库ID'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.varchar('count_type', 30, '盘点类型'),
      col.int('system_quantity', '系统数量'),
      col.int('actual_quantity', '实盘数量'),
      col.int('difference', '差异数量'),
      col.decimal('difference_value', '18,2', '差异金额'),
      col.decimal('accuracy_rate', '5,4', '盘点准确率'),
      col.date('count_date', '盘点日期'),
      col.ds(),
      col.etlTime(),
    ],
  },

  // ---------- Receiving Facts ----------
  {
    name: 'dwd_fact_receiving',
    comment: '收货事实表',
    layer: 'dwd',
    columns: [
      col.id('收货事实ID'),
      col.varchar('receiving_no', 50, '收货单号'),
      col.fk('supplier_id', 'ods_supplier', '供应商ID'),
      col.fk('warehouse_id', 'ods_warehouse', '仓库ID'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.int('expected_quantity', '预期数量'),
      col.int('received_quantity', '实收数量'),
      col.int('rejected_quantity', '拒收数量'),
      col.decimal('receiving_rate', '5,4', '收货合格率'),
      col.date('receiving_date', '收货日期'),
      col.int('po_to_receive_days', '下单到收货天数'),
      col.ds(),
      col.etlTime(),
    ],
  },

  // ---------- Quality Facts ----------
  {
    name: 'dwd_fact_quality_inspection',
    comment: '质量检验事实表',
    layer: 'dwd',
    columns: [
      col.id('检验事实ID'),
      col.varchar('inspection_no', 50, '检验单号'),
      col.varchar('inspection_type', 30, '检验类型'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.fk('supplier_id', 'ods_supplier', '供应商ID'),
      col.varchar('batch_no', 50, '批次号'),
      col.int('inspected_quantity', '检验数量'),
      col.int('qualified_quantity', '合格数量'),
      col.int('defective_quantity', '不合格数量'),
      col.decimal('defect_rate', '5,4', '不良率'),
      col.decimal('pass_rate', '5,4', '合格率'),
      col.varchar('result', 20, '检验结果'),
      col.date('inspection_date', '检验日期'),
      col.ds(),
      col.etlTime(),
    ],
  },
  {
    name: 'dwd_fact_defect',
    comment: '质量缺陷事实表',
    layer: 'dwd',
    columns: [
      col.id('缺陷事实ID'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.fk('supplier_id', 'ods_supplier', '供应商ID'),
      col.varchar('defect_type', 50, '缺陷类型'),
      col.varchar('severity', 20, '严重等级'),
      col.int('defect_quantity', '缺陷数量'),
      col.decimal('loss_amount', '18,2', '损失金额'),
      col.varchar('root_cause_category', 50, '根因分类'),
      col.bool('is_resolved', '是否已解决'),
      col.date('defect_date', '发生日期'),
      col.ds(),
      col.etlTime(),
    ],
  },

  // ---------- Logistics Facts ----------
  {
    name: 'dwd_fact_shipment',
    comment: '物流发运事实表',
    layer: 'dwd',
    columns: [
      col.id('发运事实ID'),
      col.varchar('shipment_no', 50, '发货单号'),
      col.varchar('shipment_type', 30, '发运方式'),
      col.fk('carrier_id', 'ods_carrier', '承运商ID'),
      col.fk('origin_warehouse_id', 'ods_warehouse', '发货仓库ID'),
      col.varchar('destination_city', 50, '目的城市'),
      col.decimal('freight_cost', '12,2', '运费'),
      col.decimal('total_weight', '12,2', '总重量(kg)'),
      col.decimal('total_volume', '12,4', '总体积(m³)'),
      col.decimal('cost_per_kg', '10,4', '单位重量运费'),
      col.date('ship_date', '发货日期'),
      col.date('expected_arrival_date', '预计到达日期'),
      col.date('actual_arrival_date', '实际到达日期'),
      col.int('transit_days', '运输天数'),
      col.bool('is_on_time', '是否准时到达'),
      col.bool('is_damaged', '是否有破损'),
      col.ds(),
      col.etlTime(),
    ],
  },
  {
    name: 'dwd_fact_delivery_performance',
    comment: '配送绩效事实表',
    layer: 'dwd',
    columns: [
      col.id('绩效事实ID'),
      col.fk('carrier_id', 'ods_carrier', '承运商ID'),
      col.varchar('route', 100, '线路'),
      col.int('total_shipments', '总发运次数'),
      col.int('on_time_count', '准时次数'),
      col.int('damaged_count', '破损次数'),
      col.int('lost_count', '丢失次数'),
      col.decimal('on_time_rate', '5,4', '准时率'),
      col.decimal('damage_rate', '5,4', '破损率'),
      col.decimal('avg_transit_days', '8,2', '平均运输天数'),
      col.date('stat_date', '统计日期'),
      col.ds(),
      col.etlTime(),
    ],
  },

  // ---------- Production Facts ----------
  {
    name: 'dwd_fact_production_order',
    comment: '生产工单事实表',
    layer: 'dwd',
    columns: [
      col.id('工单事实ID'),
      col.varchar('work_order_no', 50, '工单号'),
      col.fk('product_material_id', 'ods_material', '产品物料ID'),
      col.fk('production_line_id', 'ods_production_line', '生产线ID'),
      col.int('planned_quantity', '计划数量'),
      col.int('completed_quantity', '完成数量'),
      col.int('scrap_quantity', '报废数量'),
      col.decimal('completion_rate', '5,4', '完成率'),
      col.decimal('scrap_rate', '5,4', '报废率'),
      col.date('start_date', '开始日期'),
      col.date('end_date', '结束日期'),
      col.int('production_days', '生产天数'),
      col.varchar('order_status', 30, '工单状态'),
      col.ds(),
      col.etlTime(),
    ],
  },
  {
    name: 'dwd_fact_material_consumption',
    comment: '生产物料消耗事实表',
    layer: 'dwd',
    columns: [
      col.id('消耗事实ID'),
      col.varchar('work_order_no', 50, '工单号'),
      col.fk('product_material_id', 'ods_material', '成品物料ID'),
      col.fk('component_material_id', 'ods_material', '子件物料ID'),
      col.decimal('standard_quantity', '12,4', 'BOM标准用量'),
      col.decimal('actual_quantity', '12,4', '实际用量'),
      col.decimal('variance', '12,4', '差异量'),
      col.decimal('variance_rate', '5,4', '差异率'),
      col.decimal('material_cost', '18,2', '物料成本'),
      col.date('consumption_date', '消耗日期'),
      col.ds(),
      col.etlTime(),
    ],
  },

  // ---------- Return Facts ----------
  {
    name: 'dwd_fact_return',
    comment: '退货事实表',
    layer: 'dwd',
    columns: [
      col.id('退货事实ID'),
      col.varchar('return_no', 50, '退货单号'),
      col.varchar('return_type', 30, '退货类型'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.fk('supplier_id', 'ods_supplier', '供应商ID'),
      col.int('return_quantity', '退货数量'),
      col.decimal('refund_amount', '18,2', '退款金额'),
      col.varchar('reason_code', 30, '退货原因编码'),
      col.varchar('quality_result', 30, '质量判定'),
      col.date('return_date', '退货日期'),
      col.int('process_days', '处理天数'),
      col.ds(),
      col.etlTime(),
    ],
  },

  // ---------- Cost Facts ----------
  {
    name: 'dwd_fact_cost',
    comment: '成本发生事实表',
    layer: 'dwd',
    columns: [
      col.id('成本事实ID'),
      col.fk('cost_center_id', 'ods_cost_center', '成本中心ID'),
      col.varchar('cost_category', 50, '成本科目'),
      col.varchar('cost_sub_category', 50, '成本子科目'),
      col.decimal('amount', '18,2', '金额'),
      col.decimal('budget_amount', '18,2', '预算金额'),
      col.decimal('variance', '18,2', '预算差异'),
      col.varchar('currency', 10, '币种'),
      col.date('cost_date', '成本日期'),
      col.varchar('cost_period', 20, '成本期间'),
      col.ds(),
      col.etlTime(),
    ],
  },

  // ---------- Cold Chain Facts ----------
  {
    name: 'dwd_fact_cold_chain_monitoring',
    comment: '冷链监控事实表',
    layer: 'dwd',
    columns: [
      col.id('监控事实ID'),
      col.fk('device_id', 'ods_cold_chain_device', '设备ID'),
      col.fk('warehouse_id', 'ods_warehouse', '仓库ID'),
      col.decimal('avg_temperature', '5,1', '平均温度'),
      col.decimal('max_temperature', '5,1', '最高温度'),
      col.decimal('min_temperature', '5,1', '最低温度'),
      col.decimal('avg_humidity', '5,1', '平均湿度'),
      col.int('reading_count', '采集次数'),
      col.int('alarm_count', '告警次数'),
      col.bool('has_breach', '是否超标'),
      col.date('monitor_date', '监控日期'),
      col.ds(),
      col.etlTime(),
    ],
  },
  {
    name: 'dwd_fact_cold_chain_alert',
    comment: '冷链告警事实表',
    layer: 'dwd',
    columns: [
      col.id('告警事实ID'),
      col.fk('device_id', 'ods_cold_chain_device', '设备ID'),
      col.fk('warehouse_id', 'ods_warehouse', '仓库ID'),
      col.varchar('alert_type', 30, '告警类型'),
      col.varchar('severity', 20, '严重程度'),
      col.decimal('alert_value', '5,1', '告警值'),
      col.int('duration_minutes', '持续时长(分钟)'),
      col.bool('is_resolved', '是否已解除'),
      col.int('resolve_minutes', '解除耗时(分钟)'),
      col.date('alert_date', '告警日期'),
      col.ds(),
      col.etlTime(),
    ],
  },

  // ---------- Demand Forecast Facts ----------
  {
    name: 'dwd_fact_demand_forecast',
    comment: '需求预测事实表',
    layer: 'dwd',
    columns: [
      col.id('预测事实ID'),
      col.fk('material_id', 'ods_material', '物料ID'),
      col.varchar('forecast_period', 20, '预测周期'),
      col.varchar('forecast_type', 30, '预测类型'),
      col.int('forecast_quantity', '预测数量'),
      col.int('actual_quantity', '实际数量'),
      col.int('deviation', '偏差量'),
      col.decimal('accuracy_rate', '5,4', '准确率'),
      col.decimal('bias', '8,4', '偏差方向(正/负)'),
      col.ds(),
      col.etlTime(),
    ],
  },

  // ---------- Warehouse Operation Facts ----------
  {
    name: 'dwd_fact_warehouse_operation',
    comment: '仓库作业事实表',
    layer: 'dwd',
    columns: [
      col.id('作业事实ID'),
      col.fk('warehouse_id', 'ods_warehouse', '仓库ID'),
      col.varchar('operation_type', 30, '作业类型: 上架/拣货/打包/出库/盘点'),
      col.varchar('operator', 50, '操作人'),
      col.int('item_count', '操作SKU数'),
      col.int('total_quantity', '操作总数量'),
      col.int('duration_minutes', '作业耗时(分钟)'),
      col.decimal('efficiency', '10,2', '效率(件/小时)'),
      col.int('error_count', '差错数'),
      col.date('operation_date', '作业日期'),
      col.ds(),
      col.etlTime(),
    ],
  },

  // ---------- Supplier Dimension (cleaned) ----------
  {
    name: 'dwd_dim_supplier',
    comment: '供应商维度表(清洗后)',
    layer: 'dwd',
    columns: [
      col.id('供应商维度ID'),
      col.varchar('supplier_code', 50, '供应商编码'),
      col.varchar('supplier_name', 200, '供应商名称'),
      col.varchar('supplier_type', 50, '供应商类型'),
      col.varchar('country', 50, '国家'),
      col.varchar('province', 50, '省份'),
      col.varchar('city', 50, '城市'),
      col.varchar('payment_terms', 50, '付款条件'),
      col.int('lead_time_days', '标准提前期(天)'),
      col.bool('is_strategic', '是否战略供应商'),
      col.varchar('grade', 10, '最新评级'),
      col.varchar('supplier_status', 30, '供应商状态'),
      col.ds(),
      col.etlTime(),
    ],
  },
  {
    name: 'dwd_dim_material',
    comment: '物料维度表(清洗后)',
    layer: 'dwd',
    columns: [
      col.id('物料维度ID'),
      col.varchar('material_code', 50, '物料编码'),
      col.varchar('material_name', 200, '物料名称'),
      col.varchar('material_type', 50, '物料类型'),
      col.varchar('category', 50, '分类'),
      col.varchar('sub_category', 50, '子分类'),
      col.varchar('sku', 50, 'SKU编码'),
      col.varchar('unit', 20, '单位'),
      col.decimal('unit_cost', '18,4', '单位成本'),
      col.varchar('storage_condition', 50, '存储条件'),
      col.int('shelf_life_days', '保质期(天)'),
      col.int('safety_stock', '安全库存'),
      col.bool('is_hazardous', '是否危险品'),
      col.varchar('material_status', 30, '物料状态'),
      col.ds(),
      col.etlTime(),
    ],
  },
  {
    name: 'dwd_dim_warehouse',
    comment: '仓库维度表(清洗后)',
    layer: 'dwd',
    columns: [
      col.id('仓库维度ID'),
      col.varchar('warehouse_code', 30, '仓库编码'),
      col.varchar('warehouse_name', 100, '仓库名称'),
      col.varchar('warehouse_type', 30, '仓库类型'),
      col.varchar('region', 50, '区域'),
      col.varchar('city', 50, '城市'),
      col.decimal('total_area', '12,2', '总面积'),
      col.int('total_positions', '总库位数'),
      col.decimal('min_temperature', '5,1', '最低温度'),
      col.decimal('max_temperature', '5,1', '最高温度'),
      col.varchar('warehouse_status', 30, '仓库状态'),
      col.ds(),
      col.etlTime(),
    ],
  },
  {
    name: 'dwd_dim_carrier',
    comment: '承运商维度表(清洗后)',
    layer: 'dwd',
    columns: [
      col.id('承运商维度ID'),
      col.varchar('carrier_code', 30, '承运商编码'),
      col.varchar('carrier_name', 100, '承运商名称'),
      col.varchar('carrier_type', 30, '承运商类型'),
      col.decimal('on_time_rate', '5,4', '准时率'),
      col.decimal('damage_rate', '5,4', '破损率'),
      col.varchar('carrier_status', 30, '承运商状态'),
      col.ds(),
      col.etlTime(),
    ],
  },

  // ---------- Additional DWD facts ----------
  {
    name: 'dwd_fact_purchase_payment',
    comment: '采购付款事实表',
    layer: 'dwd',
    columns: [
      col.id('付款事实ID'),
      col.varchar('po_no', 50, '采购订单号'),
      col.fk('supplier_id', 'ods_supplier', '供应商ID'),
      col.decimal('invoice_amount', '18,2', '发票金额'),
      col.decimal('paid_amount', '18,2', '已付金额'),
      col.decimal('outstanding_amount', '18,2', '待付金额'),
      col.date('invoice_date', '发票日期'),
      col.date('due_date', '到期日'),
      col.date('payment_date', '付款日'),
      col.int('payment_delay_days', '付款延迟天数'),
      col.varchar('payment_status', 30, '付款状态: 待付/已付/逾期'),
      col.ds(),
      col.etlTime(),
    ],
  },
  {
    name: 'dwd_fact_bom_explosion',
    comment: 'BOM展开事实表',
    layer: 'dwd',
    columns: [
      col.id('展开事实ID'),
      col.fk('product_material_id', 'ods_material', '成品物料ID'),
      col.fk('component_material_id', 'ods_material', '子件物料ID'),
      col.varchar('bom_version', 20, 'BOM版本'),
      col.int('level', '层级'),
      col.decimal('unit_quantity', '12,4', '单位用量'),
      col.decimal('waste_rate', '5,4', '损耗率'),
      col.decimal('extended_quantity', '12,4', '展开用量'),
      col.decimal('unit_cost', '18,4', '子件单价'),
      col.decimal('extended_cost', '18,2', '展开成本'),
      col.ds(),
      col.etlTime(),
    ],
  },
];

/* ================================================================
 * DWS Layer — ~45 tables: aggregated summary / wide tables
 * ================================================================ */

const scDimensions = {
  supplier: [
    { name: 'supplier_code', comment: '供应商编码' },
    { name: 'supplier_name', comment: '供应商名称' },
    { name: 'supplier_type', comment: '供应商类型' },
  ],
  material: [
    { name: 'material_code', comment: '物料编码' },
    { name: 'material_name', comment: '物料名称' },
    { name: 'material_type', comment: '物料类型' },
    { name: 'category', comment: '分类' },
  ],
  warehouse: [
    { name: 'warehouse_code', comment: '仓库编码' },
    { name: 'warehouse_name', comment: '仓库名称' },
    { name: 'warehouse_type', comment: '仓库类型' },
    { name: 'region', comment: '区域' },
  ],
  carrier: [
    { name: 'carrier_code', comment: '承运商编码' },
    { name: 'carrier_name', comment: '承运商名称' },
    { name: 'carrier_type', comment: '承运商类型' },
  ],
  timePeriod: [
    { name: 'stat_year', comment: '统计年份' },
    { name: 'stat_month', comment: '统计月份' },
  ],
};

const dwsTables: TableDef[] = [
  // ---------- Supplier Summaries ----------
  generateSummaryTable(
    'dws',
    'supplier_delivery_summary',
    '供应商交货汇总表',
    'dws',
    [...scDimensions.supplier, ...scDimensions.timePeriod],
    [
      { name: 'total_orders', type: 'bigint', comment: '总订单数' },
      { name: 'on_time_orders', type: 'bigint', comment: '准时订单数' },
      { name: 'late_orders', type: 'bigint', comment: '延迟订单数' },
      { name: 'on_time_rate', type: 'decimal', comment: '准时交货率' },
      { name: 'avg_lead_time_days', type: 'decimal', comment: '平均提前期(天)' },
      { name: 'max_lead_time_days', type: 'bigint', comment: '最长提前期(天)' },
    ],
  ),
  generateSummaryTable(
    'dws',
    'supplier_quality_summary',
    '供应商质量汇总表',
    'dws',
    [...scDimensions.supplier, ...scDimensions.timePeriod],
    [
      { name: 'inspected_batches', type: 'bigint', comment: '检验批次数' },
      { name: 'qualified_batches', type: 'bigint', comment: '合格批次数' },
      { name: 'defective_batches', type: 'bigint', comment: '不合格批次数' },
      { name: 'pass_rate', type: 'decimal', comment: '合格率' },
      { name: 'total_defect_qty', type: 'bigint', comment: '不良品总数' },
      { name: 'quality_loss_amount', type: 'decimal', comment: '质量损失金额' },
    ],
  ),
  generateSummaryTable(
    'dws',
    'supplier_cost_summary',
    '供应商采购成本汇总表',
    'dws',
    [...scDimensions.supplier, ...scDimensions.timePeriod],
    [
      { name: 'total_po_amount', type: 'decimal', comment: '采购总金额' },
      { name: 'total_po_count', type: 'bigint', comment: '采购订单数' },
      { name: 'avg_unit_price', type: 'decimal', comment: '平均采购单价' },
      { name: 'price_variance', type: 'decimal', comment: '价格波动' },
      { name: 'savings_amount', type: 'decimal', comment: '议价节省金额' },
      { name: 'savings_rate', type: 'decimal', comment: '采购节省率' },
    ],
  ),
  generateSummaryTable(
    'dws',
    'supplier_overall_score',
    '供应商综合评分汇总表',
    'dws',
    [...scDimensions.supplier, ...scDimensions.timePeriod],
    [
      { name: 'quality_score', type: 'decimal', comment: '质量得分' },
      { name: 'delivery_score', type: 'decimal', comment: '交付得分' },
      { name: 'cost_score', type: 'decimal', comment: '成本得分' },
      { name: 'service_score', type: 'decimal', comment: '服务得分' },
      { name: 'total_score', type: 'decimal', comment: '综合得分' },
      { name: 'grade', type: 'bigint', comment: '评级(A=4/B=3/C=2/D=1)' },
    ],
  ),

  // ---------- Inventory Summaries ----------
  generateSummaryTable(
    'dws',
    'inventory_turnover_summary',
    '库存周转汇总表',
    'dws',
    [...scDimensions.material, ...scDimensions.warehouse.slice(0, 2), ...scDimensions.timePeriod],
    [
      { name: 'avg_inventory_qty', type: 'decimal', comment: '平均库存量' },
      { name: 'avg_inventory_value', type: 'decimal', comment: '平均库存金额' },
      { name: 'total_outbound_qty', type: 'bigint', comment: '总出库量' },
      { name: 'total_outbound_value', type: 'decimal', comment: '总出库金额' },
      { name: 'turnover_times', type: 'decimal', comment: '周转次数' },
      { name: 'turnover_days', type: 'decimal', comment: '周转天数' },
    ],
  ),
  generateSummaryTable(
    'dws',
    'inventory_aging_summary',
    '库存库龄分析汇总表',
    'dws',
    [...scDimensions.material, ...scDimensions.warehouse.slice(0, 2)],
    [
      { name: 'qty_0_30d', type: 'bigint', comment: '0-30天库存量' },
      { name: 'qty_31_60d', type: 'bigint', comment: '31-60天库存量' },
      { name: 'qty_61_90d', type: 'bigint', comment: '61-90天库存量' },
      { name: 'qty_91_180d', type: 'bigint', comment: '91-180天库存量' },
      { name: 'qty_over_180d', type: 'bigint', comment: '180天以上库存量' },
      { name: 'total_quantity', type: 'bigint', comment: '总库存量' },
      { name: 'slow_moving_rate', type: 'decimal', comment: '呆滞率' },
    ],
  ),
  generateSummaryTable(
    'dws',
    'inventory_level_daily',
    '每日库存水位表',
    'dws',
    [...scDimensions.material.slice(0, 2), ...scDimensions.warehouse.slice(0, 2)],
    [
      { name: 'current_qty', type: 'bigint', comment: '当前库存量' },
      { name: 'available_qty', type: 'bigint', comment: '可用库存量' },
      { name: 'safety_stock', type: 'bigint', comment: '安全库存量' },
      { name: 'reorder_point', type: 'bigint', comment: '补货点' },
      { name: 'stock_value', type: 'decimal', comment: '库存金额' },
      { name: 'is_below_safety', type: 'bigint', comment: '是否低于安全库存(1/0)' },
      { name: 'days_of_supply', type: 'decimal', comment: '可供天数' },
    ],
  ),
  generateSummaryTable(
    'dws',
    'inventory_movement_summary',
    '库存出入库汇总表',
    'dws',
    [...scDimensions.warehouse, ...scDimensions.timePeriod],
    [
      { name: 'inbound_qty', type: 'bigint', comment: '入库总量' },
      { name: 'outbound_qty', type: 'bigint', comment: '出库总量' },
      { name: 'transfer_in_qty', type: 'bigint', comment: '调入总量' },
      { name: 'transfer_out_qty', type: 'bigint', comment: '调出总量' },
      { name: 'scrap_qty', type: 'bigint', comment: '报废总量' },
      { name: 'inbound_value', type: 'decimal', comment: '入库总金额' },
      { name: 'outbound_value', type: 'decimal', comment: '出库总金额' },
    ],
  ),
  generateSummaryTable(
    'dws',
    'inventory_expiry_monitor',
    '库存临期监控表',
    'dws',
    [...scDimensions.material.slice(0, 2), ...scDimensions.warehouse.slice(0, 2)],
    [
      { name: 'near_expiry_qty_7d', type: 'bigint', comment: '7天内到期数量' },
      { name: 'near_expiry_qty_30d', type: 'bigint', comment: '30天内到期数量' },
      { name: 'near_expiry_qty_90d', type: 'bigint', comment: '90天内到期数量' },
      { name: 'expired_qty', type: 'bigint', comment: '已过期数量' },
      { name: 'near_expiry_value', type: 'decimal', comment: '临期库存金额' },
      { name: 'expired_value', type: 'decimal', comment: '过期库存金额' },
    ],
  ),

  // ---------- Warehouse Summaries ----------
  generateSummaryTable(
    'dws',
    'warehouse_utilization_daily',
    '仓库利用率日统计表',
    'dws',
    scDimensions.warehouse,
    [
      { name: 'total_positions', type: 'bigint', comment: '总库位数' },
      { name: 'occupied_positions', type: 'bigint', comment: '已占用库位数' },
      { name: 'utilization_rate', type: 'decimal', comment: '库位利用率' },
      { name: 'total_area', type: 'decimal', comment: '总面积(㎡)' },
      { name: 'used_area', type: 'decimal', comment: '已用面积(㎡)' },
      { name: 'area_utilization_rate', type: 'decimal', comment: '面积利用率' },
      { name: 'total_sku_count', type: 'bigint', comment: 'SKU总数' },
    ],
  ),
  generateSummaryTable(
    'dws',
    'warehouse_operation_summary',
    '仓库作业效率汇总表',
    'dws',
    [...scDimensions.warehouse.slice(0, 2), ...scDimensions.timePeriod],
    [
      { name: 'inbound_tasks', type: 'bigint', comment: '入库作业次数' },
      { name: 'outbound_tasks', type: 'bigint', comment: '出库作业次数' },
      { name: 'pick_tasks', type: 'bigint', comment: '拣货作业次数' },
      { name: 'total_items_processed', type: 'bigint', comment: '处理总件数' },
      { name: 'avg_processing_time_min', type: 'decimal', comment: '平均处理时间(分钟)' },
      { name: 'error_rate', type: 'decimal', comment: '差错率' },
    ],
  ),
  generateSummaryTable(
    'dws',
    'warehouse_capacity_forecast',
    '仓库容量预测表',
    'dws',
    [...scDimensions.warehouse.slice(0, 2)],
    [
      { name: 'current_utilization', type: 'decimal', comment: '当前利用率' },
      { name: 'forecast_7d_utilization', type: 'decimal', comment: '7天后预测利用率' },
      { name: 'forecast_30d_utilization', type: 'decimal', comment: '30天后预测利用率' },
      { name: 'remaining_capacity', type: 'bigint', comment: '剩余容量(库位)' },
      { name: 'expected_inbound_qty', type: 'bigint', comment: '预期入库量' },
      { name: 'expected_outbound_qty', type: 'bigint', comment: '预期出库量' },
    ],
  ),

  // ---------- Procurement Summaries ----------
  generateSummaryTable(
    'dws',
    'procurement_summary_monthly',
    '月度采购汇总表',
    'dws',
    scDimensions.timePeriod,
    [
      { name: 'total_po_count', type: 'bigint', comment: '采购订单总数' },
      { name: 'total_po_amount', type: 'decimal', comment: '采购总金额' },
      { name: 'total_material_types', type: 'bigint', comment: '采购物料种类数' },
      { name: 'avg_lead_time_days', type: 'decimal', comment: '平均采购提前期' },
      { name: 'on_time_delivery_rate', type: 'decimal', comment: '准时交货率' },
      { name: 'total_savings', type: 'decimal', comment: '采购节省总额' },
      { name: 'emergency_po_count', type: 'bigint', comment: '紧急采购订单数' },
      { name: 'emergency_po_rate', type: 'decimal', comment: '紧急采购占比' },
    ],
  ),
  generateSummaryTable(
    'dws',
    'procurement_by_category',
    '分类采购汇总表',
    'dws',
    [
      { name: 'category', comment: '物料分类' },
      { name: 'sub_category', comment: '物料子分类' },
      ...scDimensions.timePeriod,
    ],
    [
      { name: 'po_count', type: 'bigint', comment: '订单数' },
      { name: 'po_amount', type: 'decimal', comment: '采购金额' },
      { name: 'supplier_count', type: 'bigint', comment: '供应商数量' },
      { name: 'avg_unit_price', type: 'decimal', comment: '平均采购单价' },
      { name: 'price_trend', type: 'decimal', comment: '价格环比变化率' },
    ],
  ),
  generateSummaryTable(
    'dws',
    'purchase_fulfillment_summary',
    '采购履约汇总表',
    'dws',
    [...scDimensions.supplier.slice(0, 2), ...scDimensions.timePeriod],
    [
      { name: 'total_order_qty', type: 'bigint', comment: '订购总量' },
      { name: 'received_qty', type: 'bigint', comment: '到货总量' },
      { name: 'rejected_qty', type: 'bigint', comment: '拒收总量' },
      { name: 'fill_rate', type: 'decimal', comment: '订单满足率' },
      { name: 'short_delivery_count', type: 'bigint', comment: '短交次数' },
      { name: 'over_delivery_count', type: 'bigint', comment: '超交次数' },
    ],
  ),

  // ---------- Quality Summaries ----------
  generateSummaryTable(
    'dws',
    'quality_summary_monthly',
    '月度质量汇总表',
    'dws',
    scDimensions.timePeriod,
    [
      { name: 'total_inspections', type: 'bigint', comment: '检验总批次' },
      { name: 'qualified_count', type: 'bigint', comment: '合格批次' },
      { name: 'defective_count', type: 'bigint', comment: '不合格批次' },
      { name: 'overall_pass_rate', type: 'decimal', comment: '总合格率' },
      { name: 'incoming_pass_rate', type: 'decimal', comment: '来料合格率' },
      { name: 'process_pass_rate', type: 'decimal', comment: '过程合格率' },
      { name: 'final_pass_rate', type: 'decimal', comment: '成品合格率' },
      { name: 'total_loss_amount', type: 'decimal', comment: '质量损失总额' },
    ],
  ),
  generateSummaryTable(
    'dws',
    'defect_analysis_summary',
    '缺陷分析汇总表',
    'dws',
    [
      { name: 'defect_type', comment: '缺陷类型' },
      { name: 'severity', comment: '严重等级' },
      ...scDimensions.timePeriod,
    ],
    [
      { name: 'defect_count', type: 'bigint', comment: '缺陷数量' },
      { name: 'affected_batches', type: 'bigint', comment: '涉及批次数' },
      { name: 'defect_qty', type: 'bigint', comment: '不良品数量' },
      { name: 'loss_amount', type: 'decimal', comment: '损失金额' },
      { name: 'resolved_count', type: 'bigint', comment: '已解决数量' },
      { name: 'resolution_rate', type: 'decimal', comment: '解决率' },
    ],
  ),

  // ---------- Logistics Summaries ----------
  generateSummaryTable(
    'dws',
    'logistics_performance_summary',
    '物流绩效汇总表',
    'dws',
    [...scDimensions.carrier, ...scDimensions.timePeriod],
    [
      { name: 'total_shipments', type: 'bigint', comment: '总发运次数' },
      { name: 'on_time_shipments', type: 'bigint', comment: '准时到达次数' },
      { name: 'on_time_rate', type: 'decimal', comment: '准时到达率' },
      { name: 'avg_transit_days', type: 'decimal', comment: '平均运输天数' },
      { name: 'total_freight_cost', type: 'decimal', comment: '总运费' },
      { name: 'avg_cost_per_kg', type: 'decimal', comment: '平均单位运费(元/kg)' },
      { name: 'damage_count', type: 'bigint', comment: '破损次数' },
      { name: 'damage_rate', type: 'decimal', comment: '破损率' },
    ],
  ),
  generateSummaryTable(
    'dws',
    'logistics_route_analysis',
    '物流线路分析表',
    'dws',
    [
      { name: 'origin_city', comment: '起运城市' },
      { name: 'destination_city', comment: '目的城市' },
      ...scDimensions.timePeriod,
    ],
    [
      { name: 'shipment_count', type: 'bigint', comment: '发运次数' },
      { name: 'total_weight', type: 'decimal', comment: '总重量(kg)' },
      { name: 'total_volume', type: 'decimal', comment: '总体积(m³)' },
      { name: 'total_cost', type: 'decimal', comment: '总运费' },
      { name: 'avg_transit_days', type: 'decimal', comment: '平均运输天数' },
      { name: 'on_time_rate', type: 'decimal', comment: '准时率' },
    ],
  ),
  generateSummaryTable(
    'dws',
    'freight_cost_summary',
    '运费成本汇总表',
    'dws',
    [{ name: 'shipment_type', comment: '运输方式' }, ...scDimensions.timePeriod],
    [
      { name: 'shipment_count', type: 'bigint', comment: '发运次数' },
      { name: 'total_cost', type: 'decimal', comment: '总运费' },
      { name: 'avg_cost_per_shipment', type: 'decimal', comment: '平均单次运费' },
      { name: 'avg_cost_per_kg', type: 'decimal', comment: '平均运费(元/kg)' },
      { name: 'cost_vs_budget', type: 'decimal', comment: '预算偏差率' },
    ],
  ),

  // ---------- Production Summaries ----------
  generateSummaryTable(
    'dws',
    'production_output_summary',
    '生产产出汇总表',
    'dws',
    [
      { name: 'production_line_code', comment: '生产线编码' },
      { name: 'product_name', comment: '产品名称' },
      ...scDimensions.timePeriod,
    ],
    [
      { name: 'planned_qty', type: 'bigint', comment: '计划产量' },
      { name: 'completed_qty', type: 'bigint', comment: '完成产量' },
      { name: 'scrap_qty', type: 'bigint', comment: '报废量' },
      { name: 'completion_rate', type: 'decimal', comment: '完成率' },
      { name: 'scrap_rate', type: 'decimal', comment: '报废率' },
      { name: 'yield_rate', type: 'decimal', comment: '良品率' },
    ],
  ),
  generateSummaryTable(
    'dws',
    'production_material_usage',
    '生产物料消耗汇总表',
    'dws',
    [
      { name: 'product_name', comment: '产品名称' },
      { name: 'component_name', comment: '子件名称' },
      ...scDimensions.timePeriod,
    ],
    [
      { name: 'standard_qty', type: 'decimal', comment: '标准用量' },
      { name: 'actual_qty', type: 'decimal', comment: '实际用量' },
      { name: 'variance_qty', type: 'decimal', comment: '差异量' },
      { name: 'variance_rate', type: 'decimal', comment: '差异率' },
      { name: 'material_cost', type: 'decimal', comment: '物料成本' },
      { name: 'waste_cost', type: 'decimal', comment: '浪费成本' },
    ],
  ),
  generateSummaryTable(
    'dws',
    'production_line_efficiency',
    '生产线效率汇总表',
    'dws',
    [
      { name: 'line_code', comment: '生产线编码' },
      { name: 'line_name', comment: '生产线名称' },
      ...scDimensions.timePeriod,
    ],
    [
      { name: 'total_hours', type: 'decimal', comment: '总可用工时' },
      { name: 'running_hours', type: 'decimal', comment: '实际运行工时' },
      { name: 'downtime_hours', type: 'decimal', comment: '停机工时' },
      { name: 'utilization_rate', type: 'decimal', comment: '设备利用率' },
      { name: 'oee', type: 'decimal', comment: 'OEE综合设备效率' },
      { name: 'output_per_hour', type: 'decimal', comment: '每小时产出' },
    ],
  ),

  // ---------- Return Summaries ----------
  generateSummaryTable(
    'dws',
    'return_summary_monthly',
    '月度退货汇总表',
    'dws',
    [{ name: 'return_type', comment: '退货类型' }, ...scDimensions.timePeriod],
    [
      { name: 'return_count', type: 'bigint', comment: '退货单数' },
      { name: 'return_qty', type: 'bigint', comment: '退货总量' },
      { name: 'refund_amount', type: 'decimal', comment: '退款总额' },
      { name: 'avg_process_days', type: 'decimal', comment: '平均处理天数' },
      { name: 'reusable_qty', type: 'bigint', comment: '可二次利用数量' },
      { name: 'scrap_qty', type: 'bigint', comment: '报废数量' },
    ],
  ),
  generateSummaryTable(
    'dws',
    'return_reason_analysis',
    '退货原因分析表',
    'dws',
    [
      { name: 'reason_code', comment: '退货原因编码' },
      { name: 'reason_desc', comment: '退货原因描述' },
      ...scDimensions.timePeriod,
    ],
    [
      { name: 'return_count', type: 'bigint', comment: '退货次数' },
      { name: 'return_qty', type: 'bigint', comment: '退货数量' },
      { name: 'loss_amount', type: 'decimal', comment: '损失金额' },
      { name: 'proportion', type: 'decimal', comment: '占比' },
    ],
  ),

  // ---------- Cold Chain Summaries ----------
  generateSummaryTable(
    'dws',
    'cold_chain_daily_summary',
    '冷链日监控汇总表',
    'dws',
    [...scDimensions.warehouse.slice(0, 2), { name: 'zone_name', comment: '库区名称' }],
    [
      { name: 'avg_temperature', type: 'decimal', comment: '日均温度' },
      { name: 'max_temperature', type: 'decimal', comment: '最高温度' },
      { name: 'min_temperature', type: 'decimal', comment: '最低温度' },
      { name: 'avg_humidity', type: 'decimal', comment: '日均湿度' },
      { name: 'alarm_count', type: 'bigint', comment: '告警次数' },
      { name: 'breach_minutes', type: 'bigint', comment: '超标总分钟数' },
      { name: 'compliance_rate', type: 'decimal', comment: '合规率' },
    ],
  ),
  generateSummaryTable(
    'dws',
    'cold_chain_alert_summary',
    '冷链告警汇总表',
    'dws',
    [...scDimensions.warehouse.slice(0, 2), ...scDimensions.timePeriod],
    [
      { name: 'total_alerts', type: 'bigint', comment: '总告警数' },
      { name: 'critical_alerts', type: 'bigint', comment: '紧急告警数' },
      { name: 'resolved_count', type: 'bigint', comment: '已解除数' },
      { name: 'avg_resolve_minutes', type: 'decimal', comment: '平均处理时长(分钟)' },
      { name: 'unresolved_count', type: 'bigint', comment: '未处理数' },
    ],
  ),

  // ---------- Cost Summaries ----------
  generateSummaryTable(
    'dws',
    'supply_chain_cost_summary',
    '供应链成本汇总表',
    'dws',
    [
      { name: 'cost_category', comment: '成本科目' },
      { name: 'cost_center_name', comment: '成本中心' },
      ...scDimensions.timePeriod,
    ],
    [
      { name: 'actual_amount', type: 'decimal', comment: '实际金额' },
      { name: 'budget_amount', type: 'decimal', comment: '预算金额' },
      { name: 'variance_amount', type: 'decimal', comment: '差异金额' },
      { name: 'variance_rate', type: 'decimal', comment: '差异率' },
      { name: 'yoy_change_rate', type: 'decimal', comment: '同比变化率' },
    ],
  ),
  generateSummaryTable(
    'dws',
    'total_cost_of_ownership',
    '物料总拥有成本表',
    'dws',
    [...scDimensions.material.slice(0, 2), ...scDimensions.timePeriod],
    [
      { name: 'purchase_cost', type: 'decimal', comment: '采购成本' },
      { name: 'logistics_cost', type: 'decimal', comment: '物流成本' },
      { name: 'warehousing_cost', type: 'decimal', comment: '仓储成本' },
      { name: 'quality_loss_cost', type: 'decimal', comment: '质量损失成本' },
      { name: 'handling_cost', type: 'decimal', comment: '搬运成本' },
      { name: 'total_cost', type: 'decimal', comment: '总拥有成本' },
      { name: 'cost_per_unit', type: 'decimal', comment: '单位总成本' },
    ],
  ),

  // ---------- Demand Forecast Summaries ----------
  generateSummaryTable(
    'dws',
    'demand_forecast_accuracy',
    '需求预测准确率表',
    'dws',
    [...scDimensions.material.slice(0, 2), ...scDimensions.timePeriod],
    [
      { name: 'forecast_qty', type: 'bigint', comment: '预测数量' },
      { name: 'actual_qty', type: 'bigint', comment: '实际数量' },
      { name: 'absolute_error', type: 'bigint', comment: '绝对偏差' },
      { name: 'mape', type: 'decimal', comment: 'MAPE' },
      { name: 'bias', type: 'decimal', comment: '偏差方向' },
      { name: 'accuracy_rate', type: 'decimal', comment: '准确率' },
    ],
  ),

  // ---------- BOM Cost Summary ----------
  generateSummaryTable(
    'dws',
    'bom_cost_summary',
    'BOM成本汇总表',
    'dws',
    [
      { name: 'product_code', comment: '产品编码' },
      { name: 'product_name', comment: '产品名称' },
      { name: 'bom_version', comment: 'BOM版本' },
    ],
    [
      { name: 'material_cost', type: 'decimal', comment: '物料总成本' },
      { name: 'component_count', type: 'bigint', comment: '子件数量' },
      { name: 'level_count', type: 'bigint', comment: '层级数' },
      { name: 'max_lead_time_days', type: 'bigint', comment: '最长物料提前期' },
      { name: 'cost_vs_prev_version', type: 'decimal', comment: '与前版本成本差异' },
    ],
  ),

  // ---------- Packaging Summary ----------
  generateSummaryTable(
    'dws',
    'packaging_usage_summary',
    '包装使用汇总表',
    'dws',
    [
      { name: 'packaging_type', comment: '包装类型' },
      { name: 'spec_name', comment: '规格名称' },
      ...scDimensions.timePeriod,
    ],
    [
      { name: 'usage_count', type: 'bigint', comment: '使用次数' },
      { name: 'total_cost', type: 'decimal', comment: '总成本' },
      { name: 'avg_cost_per_unit', type: 'decimal', comment: '单件平均成本' },
      { name: 'damage_count', type: 'bigint', comment: '损坏数量' },
      { name: 'reuse_count', type: 'bigint', comment: '重复利用次数' },
    ],
  ),
];

/* ================================================================
 * ADS Layer — ~40 tables: application-ready analytics & dashboards
 * ================================================================ */

const adsTables: TableDef[] = [
  // ---------- Executive Dashboards ----------
  generateSummaryTable(
    'ads',
    'supply_chain_kpi_dashboard',
    '供应链KPI看板',
    'ads',
    scDimensions.timePeriod,
    [
      { name: 'inventory_turnover_times', type: 'decimal', comment: '库存周转次数' },
      { name: 'fill_rate', type: 'decimal', comment: '订单满足率' },
      { name: 'order_fulfillment_rate', type: 'decimal', comment: '订单履行率' },
      { name: 'avg_supplier_lead_time', type: 'decimal', comment: '平均供应商提前期(天)' },
      { name: 'defect_rate', type: 'decimal', comment: '不良率' },
      { name: 'warehouse_utilization', type: 'decimal', comment: '仓库利用率' },
      { name: 'on_time_delivery_rate', type: 'decimal', comment: '准时交货率' },
      { name: 'procurement_savings_rate', type: 'decimal', comment: '采购节省率' },
      { name: 'return_rate', type: 'decimal', comment: '退货率' },
      { name: 'supply_chain_total_cost', type: 'decimal', comment: '供应链总成本' },
    ],
  ),
  generateSummaryTable(
    'ads',
    'supply_chain_health_score',
    '供应链健康度评分',
    'ads',
    scDimensions.timePeriod,
    [
      { name: 'procurement_score', type: 'decimal', comment: '采购健康度' },
      { name: 'inventory_score', type: 'decimal', comment: '库存健康度' },
      { name: 'logistics_score', type: 'decimal', comment: '物流健康度' },
      { name: 'quality_score', type: 'decimal', comment: '质量健康度' },
      { name: 'cost_score', type: 'decimal', comment: '成本健康度' },
      { name: 'overall_score', type: 'decimal', comment: '综合健康度' },
      { name: 'risk_level', type: 'bigint', comment: '风险等级(1-5)' },
    ],
  ),

  // ---------- Inventory Analytics ----------
  generateSummaryTable(
    'ads',
    'inventory_optimization_report',
    '库存优化建议报告',
    'ads',
    [...scDimensions.material.slice(0, 2), ...scDimensions.warehouse.slice(0, 2)],
    [
      { name: 'current_stock', type: 'bigint', comment: '当前库存' },
      { name: 'safety_stock', type: 'bigint', comment: '安全库存' },
      { name: 'reorder_point', type: 'bigint', comment: '补货点' },
      { name: 'economic_order_qty', type: 'bigint', comment: '经济订货量' },
      { name: 'excess_qty', type: 'bigint', comment: '过剩数量' },
      { name: 'shortage_qty', type: 'bigint', comment: '缺口数量' },
      { name: 'action_type', type: 'bigint', comment: '建议动作: 1补货/2清仓/3维持' },
      { name: 'potential_savings', type: 'decimal', comment: '潜在节省金额' },
    ],
  ),
  generateSummaryTable(
    'ads',
    'abc_xyz_classification',
    'ABC-XYZ库存分类分析',
    'ads',
    [...scDimensions.material.slice(0, 3)],
    [
      { name: 'annual_consumption_value', type: 'decimal', comment: '年消耗金额' },
      { name: 'consumption_proportion', type: 'decimal', comment: '消耗占比' },
      { name: 'abc_class', type: 'bigint', comment: 'ABC分类(A=1/B=2/C=3)' },
      { name: 'demand_variability', type: 'decimal', comment: '需求变异系数' },
      { name: 'xyz_class', type: 'bigint', comment: 'XYZ分类(X=1/Y=2/Z=3)' },
      { name: 'recommended_strategy', type: 'bigint', comment: '推荐策略编码' },
    ],
  ),
  generateSummaryTable(
    'ads',
    'slow_moving_inventory',
    '呆滞库存分析',
    'ads',
    [...scDimensions.material.slice(0, 2), ...scDimensions.warehouse.slice(0, 2)],
    [
      { name: 'quantity', type: 'bigint', comment: '呆滞数量' },
      { name: 'inventory_value', type: 'decimal', comment: '呆滞金额' },
      { name: 'days_no_movement', type: 'bigint', comment: '无变动天数' },
      { name: 'last_movement_date', type: 'bigint', comment: '最近变动日期(yyyymmdd)' },
      { name: 'disposal_suggestion', type: 'bigint', comment: '处置建议: 1降价/2转移/3报废' },
    ],
  ),
  generateSummaryTable(
    'ads',
    'stockout_risk_alert',
    '缺货风险预警',
    'ads',
    [...scDimensions.material.slice(0, 2), ...scDimensions.warehouse.slice(0, 2)],
    [
      { name: 'current_stock', type: 'bigint', comment: '当前库存' },
      { name: 'safety_stock', type: 'bigint', comment: '安全库存' },
      { name: 'avg_daily_consumption', type: 'decimal', comment: '日均消耗' },
      { name: 'days_of_supply', type: 'decimal', comment: '可供天数' },
      { name: 'in_transit_qty', type: 'bigint', comment: '在途数量' },
      { name: 'expected_arrival_days', type: 'bigint', comment: '预计到货天数' },
      { name: 'risk_level', type: 'bigint', comment: '风险等级: 1安全/2关注/3预警/4紧急' },
    ],
  ),

  // ---------- Supplier Analytics ----------
  generateSummaryTable(
    'ads',
    'supplier_ranking',
    '供应商排名榜',
    'ads',
    [...scDimensions.supplier, ...scDimensions.timePeriod],
    [
      { name: 'overall_rank', type: 'bigint', comment: '综合排名' },
      { name: 'quality_rank', type: 'bigint', comment: '质量排名' },
      { name: 'delivery_rank', type: 'bigint', comment: '交付排名' },
      { name: 'cost_rank', type: 'bigint', comment: '成本排名' },
      { name: 'total_score', type: 'decimal', comment: '综合得分' },
      { name: 'total_po_amount', type: 'decimal', comment: '采购总额' },
      { name: 'on_time_rate', type: 'decimal', comment: '准时率' },
      { name: 'pass_rate', type: 'decimal', comment: '合格率' },
    ],
  ),
  generateSummaryTable(
    'ads',
    'supplier_risk_assessment',
    '供应商风险评估',
    'ads',
    [...scDimensions.supplier],
    [
      { name: 'financial_risk_score', type: 'decimal', comment: '财务风险分' },
      { name: 'quality_risk_score', type: 'decimal', comment: '质量风险分' },
      { name: 'delivery_risk_score', type: 'decimal', comment: '交付风险分' },
      { name: 'dependency_score', type: 'decimal', comment: '依赖度分' },
      { name: 'overall_risk_score', type: 'decimal', comment: '综合风险分' },
      { name: 'cert_expiry_days', type: 'bigint', comment: '最近证书到期天数' },
      { name: 'risk_level', type: 'bigint', comment: '风险等级: 1低/2中/3高/4极高' },
      { name: 'alternative_count', type: 'bigint', comment: '可替代供应商数' },
    ],
  ),
  generateSummaryTable(
    'ads',
    'supplier_concentration_analysis',
    '供应商集中度分析',
    'ads',
    [{ name: 'category', comment: '物料分类' }, ...scDimensions.timePeriod],
    [
      { name: 'total_suppliers', type: 'bigint', comment: '供应商总数' },
      { name: 'active_suppliers', type: 'bigint', comment: '活跃供应商数' },
      { name: 'top1_share', type: 'decimal', comment: '第一大供应商占比' },
      { name: 'top3_share', type: 'decimal', comment: '前三供应商占比' },
      { name: 'hhi_index', type: 'decimal', comment: '赫芬达尔指数' },
      { name: 'concentration_risk', type: 'bigint', comment: '集中度风险: 1低/2中/3高' },
    ],
  ),

  // ---------- Procurement Analytics ----------
  generateSummaryTable(
    'ads',
    'procurement_savings_analysis',
    '采购节省分析',
    'ads',
    [{ name: 'category', comment: '物料分类' }, ...scDimensions.timePeriod],
    [
      { name: 'total_spend', type: 'decimal', comment: '总支出' },
      { name: 'negotiated_savings', type: 'decimal', comment: '议价节省' },
      { name: 'volume_savings', type: 'decimal', comment: '批量节省' },
      { name: 'substitution_savings', type: 'decimal', comment: '替代节省' },
      { name: 'total_savings', type: 'decimal', comment: '总节省额' },
      { name: 'savings_rate', type: 'decimal', comment: '节省率' },
      { name: 'target_savings', type: 'decimal', comment: '目标节省额' },
      { name: 'achievement_rate', type: 'decimal', comment: '达成率' },
    ],
  ),
  generateSummaryTable(
    'ads',
    'purchase_price_trend',
    '采购价格趋势分析',
    'ads',
    [...scDimensions.material.slice(0, 2), ...scDimensions.timePeriod],
    [
      { name: 'avg_price', type: 'decimal', comment: '平均采购价' },
      { name: 'min_price', type: 'decimal', comment: '最低采购价' },
      { name: 'max_price', type: 'decimal', comment: '最高采购价' },
      { name: 'price_stddev', type: 'decimal', comment: '价格标准差' },
      { name: 'mom_change_rate', type: 'decimal', comment: '环比变化率' },
      { name: 'yoy_change_rate', type: 'decimal', comment: '同比变化率' },
    ],
  ),

  // ---------- Logistics Analytics ----------
  generateSummaryTable(
    'ads',
    'on_time_delivery_analysis',
    '准时交货分析',
    'ads',
    [...scDimensions.carrier.slice(0, 2), ...scDimensions.timePeriod],
    [
      { name: 'total_deliveries', type: 'bigint', comment: '总交付次数' },
      { name: 'on_time_count', type: 'bigint', comment: '准时次数' },
      { name: 'early_count', type: 'bigint', comment: '提前次数' },
      { name: 'late_count', type: 'bigint', comment: '延迟次数' },
      { name: 'on_time_rate', type: 'decimal', comment: '准时率' },
      { name: 'avg_delay_days', type: 'decimal', comment: '平均延迟天数' },
      { name: 'max_delay_days', type: 'bigint', comment: '最大延迟天数' },
    ],
  ),
  generateSummaryTable(
    'ads',
    'logistics_cost_optimization',
    '物流成本优化分析',
    'ads',
    [
      { name: 'origin_region', comment: '起运区域' },
      { name: 'destination_region', comment: '目的区域' },
      { name: 'transport_mode', comment: '运输方式' },
    ],
    [
      { name: 'avg_cost_per_kg', type: 'decimal', comment: '平均运费(元/kg)' },
      { name: 'avg_transit_days', type: 'decimal', comment: '平均运输天数' },
      { name: 'total_cost', type: 'decimal', comment: '总运费' },
      { name: 'benchmark_cost', type: 'decimal', comment: '行业基准运费' },
      { name: 'optimization_potential', type: 'decimal', comment: '优化潜力(金额)' },
      { name: 'recommended_mode', type: 'bigint', comment: '推荐运输方式编码' },
    ],
  ),

  // ---------- Quality Analytics ----------
  generateSummaryTable(
    'ads',
    'quality_trend_analysis',
    '质量趋势分析',
    'ads',
    [...scDimensions.timePeriod],
    [
      { name: 'incoming_defect_rate', type: 'decimal', comment: '来料不良率' },
      { name: 'process_defect_rate', type: 'decimal', comment: '过程不良率' },
      { name: 'final_defect_rate', type: 'decimal', comment: '成品不良率' },
      { name: 'overall_defect_rate', type: 'decimal', comment: '综合不良率' },
      { name: 'quality_cost_rate', type: 'decimal', comment: '质量成本率' },
      { name: 'improvement_trend', type: 'decimal', comment: '改善趋势(正为改善)' },
    ],
  ),
  generateSummaryTable(
    'ads',
    'quality_pareto_analysis',
    '质量帕累托分析',
    'ads',
    [
      { name: 'defect_type', comment: '缺陷类型' },
      { name: 'material_category', comment: '物料分类' },
    ],
    [
      { name: 'defect_count', type: 'bigint', comment: '缺陷次数' },
      { name: 'loss_amount', type: 'decimal', comment: '损失金额' },
      { name: 'proportion', type: 'decimal', comment: '占比' },
      { name: 'cumulative_proportion', type: 'decimal', comment: '累计占比' },
      { name: 'pareto_class', type: 'bigint', comment: '帕累托分类: A(80%)/B(95%)/C(100%)' },
    ],
  ),

  // ---------- Production Analytics ----------
  generateSummaryTable(
    'ads',
    'production_planning_accuracy',
    '生产计划准确率分析',
    'ads',
    [{ name: 'product_name', comment: '产品名称' }, ...scDimensions.timePeriod],
    [
      { name: 'planned_qty', type: 'bigint', comment: '计划数量' },
      { name: 'actual_qty', type: 'bigint', comment: '实际数量' },
      { name: 'variance', type: 'bigint', comment: '偏差量' },
      { name: 'accuracy_rate', type: 'decimal', comment: '计划准确率' },
      { name: 'schedule_adherence', type: 'decimal', comment: '计划遵从率' },
    ],
  ),
  generateSummaryTable(
    'ads',
    'capacity_utilization_report',
    '产能利用率报告',
    'ads',
    [
      { name: 'factory', comment: '工厂' },
      { name: 'line_name', comment: '生产线名称' },
      ...scDimensions.timePeriod,
    ],
    [
      { name: 'design_capacity', type: 'bigint', comment: '设计产能' },
      { name: 'actual_output', type: 'bigint', comment: '实际产出' },
      { name: 'utilization_rate', type: 'decimal', comment: '产能利用率' },
      { name: 'bottleneck_factor', type: 'bigint', comment: '瓶颈因素编码' },
      { name: 'improvement_potential', type: 'decimal', comment: '提升潜力(%)' },
    ],
  ),

  // ---------- Return Analytics ----------
  generateSummaryTable(
    'ads',
    'return_rate_analysis',
    '退货率分析',
    'ads',
    [{ name: 'category', comment: '物料分类' }, ...scDimensions.timePeriod],
    [
      { name: 'total_shipped_qty', type: 'bigint', comment: '总出货量' },
      { name: 'return_qty', type: 'bigint', comment: '退货量' },
      { name: 'return_rate', type: 'decimal', comment: '退货率' },
      { name: 'return_amount', type: 'decimal', comment: '退货金额' },
      { name: 'quality_return_rate', type: 'decimal', comment: '质量原因退货率' },
      { name: 'non_quality_return_rate', type: 'decimal', comment: '非质量退货率' },
      { name: 'mom_trend', type: 'decimal', comment: '环比趋势' },
    ],
  ),

  // ---------- Cold Chain Analytics ----------
  generateSummaryTable(
    'ads',
    'cold_chain_compliance_report',
    '冷链合规报告',
    'ads',
    [...scDimensions.warehouse.slice(0, 2), ...scDimensions.timePeriod],
    [
      { name: 'total_monitoring_hours', type: 'decimal', comment: '总监控小时数' },
      { name: 'compliant_hours', type: 'decimal', comment: '合规小时数' },
      { name: 'breach_hours', type: 'decimal', comment: '超标小时数' },
      { name: 'compliance_rate', type: 'decimal', comment: '合规率' },
      { name: 'total_alerts', type: 'bigint', comment: '告警总数' },
      { name: 'avg_response_minutes', type: 'decimal', comment: '平均响应时间(分钟)' },
      { name: 'affected_inventory_value', type: 'decimal', comment: '受影响库存金额' },
    ],
  ),

  // ---------- Cost Analytics ----------
  generateSummaryTable(
    'ads',
    'total_supply_chain_cost',
    '供应链总成本分析',
    'ads',
    scDimensions.timePeriod,
    [
      { name: 'procurement_cost', type: 'decimal', comment: '采购成本' },
      { name: 'inbound_logistics_cost', type: 'decimal', comment: '入库物流成本' },
      { name: 'warehousing_cost', type: 'decimal', comment: '仓储成本' },
      { name: 'outbound_logistics_cost', type: 'decimal', comment: '出库物流成本' },
      { name: 'quality_cost', type: 'decimal', comment: '质量成本' },
      { name: 'return_cost', type: 'decimal', comment: '退货成本' },
      { name: 'total_cost', type: 'decimal', comment: '总成本' },
      { name: 'cost_per_unit_shipped', type: 'decimal', comment: '单位出货成本' },
      { name: 'cost_vs_revenue_rate', type: 'decimal', comment: '成本收入比' },
    ],
  ),
  generateSummaryTable(
    'ads',
    'cost_reduction_opportunities',
    '降本机会分析',
    'ads',
    [
      { name: 'cost_category', comment: '成本类型' },
      { name: 'opportunity_type', comment: '机会类型' },
    ],
    [
      { name: 'current_cost', type: 'decimal', comment: '当前成本' },
      { name: 'benchmark_cost', type: 'decimal', comment: '标杆成本' },
      { name: 'gap_amount', type: 'decimal', comment: '差距金额' },
      { name: 'gap_rate', type: 'decimal', comment: '差距比例' },
      { name: 'achievable_savings', type: 'decimal', comment: '可实现节省' },
      { name: 'implementation_difficulty', type: 'bigint', comment: '实施难度: 1易/2中/3难' },
      { name: 'priority', type: 'bigint', comment: '优先级: 1高/2中/3低' },
    ],
  ),

  // ---------- Demand Forecast Analytics ----------
  generateSummaryTable(
    'ads',
    'demand_supply_balance',
    '供需平衡分析',
    'ads',
    [...scDimensions.material.slice(0, 2), ...scDimensions.timePeriod],
    [
      { name: 'forecast_demand', type: 'bigint', comment: '预测需求量' },
      { name: 'confirmed_orders', type: 'bigint', comment: '已确认订单量' },
      { name: 'available_supply', type: 'bigint', comment: '可用供给量' },
      { name: 'in_transit_supply', type: 'bigint', comment: '在途供给量' },
      { name: 'planned_production', type: 'bigint', comment: '计划生产量' },
      { name: 'net_balance', type: 'bigint', comment: '净供需差额' },
      { name: 'balance_status', type: 'bigint', comment: '平衡状态: 1充足/2紧张/3短缺' },
    ],
  ),

  // ---------- BOM Analytics ----------
  generateSummaryTable(
    'ads',
    'bom_cost_comparison',
    'BOM成本对比分析',
    'ads',
    [
      { name: 'product_code', comment: '产品编码' },
      { name: 'product_name', comment: '产品名称' },
    ],
    [
      { name: 'current_bom_cost', type: 'decimal', comment: '当前BOM成本' },
      { name: 'prev_bom_cost', type: 'decimal', comment: '上一版BOM成本' },
      { name: 'cost_change', type: 'decimal', comment: '成本变化' },
      { name: 'cost_change_rate', type: 'decimal', comment: '成本变化率' },
      { name: 'material_count', type: 'bigint', comment: '物料种类数' },
      { name: 'critical_material_count', type: 'bigint', comment: '关键物料数' },
      { name: 'single_source_count', type: 'bigint', comment: '单一来源物料数' },
    ],
  ),

  // ---------- Warehouse Analytics ----------
  generateSummaryTable(
    'ads',
    'warehouse_efficiency_benchmark',
    '仓库效率对标分析',
    'ads',
    [...scDimensions.warehouse.slice(0, 2), ...scDimensions.timePeriod],
    [
      { name: 'throughput_per_sqm', type: 'decimal', comment: '每平方米吞吐量' },
      { name: 'pick_accuracy', type: 'decimal', comment: '拣货准确率' },
      { name: 'order_cycle_time_hours', type: 'decimal', comment: '订单处理周期(小时)' },
      { name: 'labor_productivity', type: 'decimal', comment: '人均产出(件/小时)' },
      { name: 'cost_per_order', type: 'decimal', comment: '单订单成本' },
      { name: 'benchmark_score', type: 'decimal', comment: '对标得分' },
    ],
  ),

  // ---------- Cross-functional Report ----------
  generateSummaryTable(
    'ads',
    'monthly_supply_chain_report',
    '月度供应链综合报告',
    'ads',
    scDimensions.timePeriod,
    [
      { name: 'total_procurement_amount', type: 'decimal', comment: '采购总额' },
      { name: 'inventory_turnover', type: 'decimal', comment: '库存周转次数' },
      { name: 'avg_warehouse_utilization', type: 'decimal', comment: '平均仓库利用率' },
      { name: 'on_time_delivery_rate', type: 'decimal', comment: '准时交货率' },
      { name: 'overall_pass_rate', type: 'decimal', comment: '整体合格率' },
      { name: 'return_rate', type: 'decimal', comment: '退货率' },
      { name: 'total_logistics_cost', type: 'decimal', comment: '物流总成本' },
      { name: 'cost_savings', type: 'decimal', comment: '成本节省' },
      { name: 'supplier_score_avg', type: 'decimal', comment: '供应商平均得分' },
      { name: 'cold_chain_compliance', type: 'decimal', comment: '冷链合规率' },
    ],
  ),
];

/* ================================================================
 * Metrics, Glossary, Knowledge, Conversations, Query History
 * ================================================================ */

const allTables = [...odsTables, ...dwdTables, ...dwsTables, ...adsTables];

export const supplyChainDomain: DomainDefinition = {
  name: '供应链管理',
  description:
    '覆盖供应链全链路的数据仓库：采购管理、供应商管理、库存管理、仓储管理、物流配送、质量控制、生产计划、需求预测、退货处理、冷链监控、BOM管理、包装管理、成本优化等业务领域。',
  dialect: 'postgresql',
  tables: allTables,

  metrics: [
    {
      name: 'inventory_turnover',
      displayName: '库存周转率',
      expression: 'SUM(outbound_value) / AVG(inventory_value)',
      metricType: 'derived',
      sourceTable: 'dws_inventory_turnover_summary',
      dimensions: ['material_code', 'warehouse_code', 'stat_month'],
      granularity: ['monthly', 'quarterly', 'yearly'],
      format: 'number',
      description:
        '衡量库存资金利用效率，数值越高表示库存流动性越好。计算公式为一定期间内出库金额除以平均库存金额。',
    },
    {
      name: 'fill_rate',
      displayName: '订单满足率',
      expression: 'SUM(received_qty) / SUM(total_order_qty)',
      metricType: 'derived',
      sourceTable: 'dws_purchase_fulfillment_summary',
      dimensions: ['supplier_code', 'stat_month'],
      granularity: ['monthly', 'quarterly'],
      format: 'percentage',
      description: '供应商实际交付数量占订购数量的比例，反映供应商的交付能力和可靠性。',
    },
    {
      name: 'order_fulfillment_rate',
      displayName: '订单履行率',
      expression:
        "COUNT(CASE WHEN order_status = '全部到货' OR order_status = '已关闭' THEN 1 END) / COUNT(*)",
      metricType: 'derived',
      sourceTable: 'dwd_fact_purchase_order',
      dimensions: ['supplier_id', 'po_type', 'ds'],
      granularity: ['daily', 'monthly'],
      format: 'percentage',
      description: '成功完成的采购订单占总订单的比例，衡量整体采购执行力。',
    },
    {
      name: 'supplier_lead_time',
      displayName: '供应商交货提前期',
      expression: 'AVG(lead_time_days)',
      metricType: 'atomic',
      sourceTable: 'dwd_fact_purchase_order',
      dimensions: ['supplier_id', 'material_id'],
      granularity: ['monthly', 'quarterly'],
      format: 'number',
      description: '从下达采购订单到供应商实际交货的平均天数，反映供应链响应速度。',
    },
    {
      name: 'defect_rate',
      displayName: '不良率',
      expression: 'SUM(defective_quantity) / SUM(inspected_quantity)',
      metricType: 'derived',
      sourceTable: 'dwd_fact_quality_inspection',
      dimensions: ['material_id', 'supplier_id', 'inspection_type'],
      granularity: ['daily', 'monthly'],
      format: 'percentage',
      description: '质量检验中不合格品数量占检验总量的比例，是衡量产品质量的核心指标。',
    },
    {
      name: 'warehouse_utilization',
      displayName: '仓库利用率',
      expression: 'SUM(occupied_positions) / SUM(total_positions)',
      metricType: 'derived',
      sourceTable: 'dws_warehouse_utilization_daily',
      dimensions: ['warehouse_code', 'warehouse_type', 'region'],
      granularity: ['daily', 'weekly'],
      format: 'percentage',
      description:
        '已占用库位数占总库位数的比例，反映仓储资源的使用效率。过高可能导致运营效率下降。',
    },
    {
      name: 'on_time_delivery_rate',
      displayName: '准时交货率',
      expression: 'SUM(on_time_shipments) / SUM(total_shipments)',
      metricType: 'derived',
      sourceTable: 'dws_logistics_performance_summary',
      dimensions: ['carrier_code', 'carrier_type', 'stat_month'],
      granularity: ['monthly', 'quarterly'],
      format: 'percentage',
      description: '按时到达的物流订单占总发运订单的比例，是衡量物流服务水平的关键指标。',
    },
    {
      name: 'procurement_savings',
      displayName: '采购节省率',
      expression: 'SUM(total_savings) / SUM(total_spend)',
      metricType: 'derived',
      sourceTable: 'ads_procurement_savings_analysis',
      dimensions: ['category', 'stat_month'],
      granularity: ['monthly', 'quarterly', 'yearly'],
      format: 'percentage',
      description: '通过议价、批量采购、替代选型等方式节省的金额占总采购支出的比例。',
    },
  ],

  glossary: [
    {
      term: '库存周转率',
      sqlExpression: 'SUM(outbound_value) / AVG(inventory_value)',
      description:
        '衡量在一定时间内库存被销售和替换的速率。周转率越高，说明库存管理效率越高，资金占用越少。通常按月或按季度计算。',
    },
    {
      term: '安全库存',
      sqlExpression: 'safety_stock',
      description:
        '为应对需求波动和供应不确定性而额外储备的库存量。安全库存 = Z × σ_d × √L，其中 Z 为服务水平系数，σ_d 为需求标准差，L 为补货提前期。',
    },
    {
      term: '采购提前期',
      sqlExpression: 'DATEDIFF(actual_delivery_date, order_date)',
      description:
        '从发出采购订单到供应商实际交货的时间间隔（天数）。采购提前期直接影响安全库存水平和补货策略的制定。',
    },
    {
      term: '良品率',
      sqlExpression: '1 - SUM(defective_quantity) / NULLIF(SUM(inspected_quantity), 0)',
      description:
        '质量检验中合格品占检验总量的比例，即 1 - 不良率。良品率是衡量供应商质量和生产工艺水平的核心指标。',
    },
    {
      term: '仓库利用率',
      sqlExpression: 'SUM(occupied_positions) / NULLIF(SUM(total_positions), 0)',
      description:
        '已占用库位数与总库位数的比值。最佳利用率通常在 85%-90% 之间，过高会导致作业效率下降和安全隐患，过低则意味着资源浪费。',
    },
    {
      term: '物流时效',
      sqlExpression: 'AVG(actual_arrival_date - ship_date)',
      description:
        '从发货到签收的平均时间（天数），是衡量物流配送效率和服务水平的重要指标。通常按运输方式和线路分别统计。',
    },
    {
      term: '退货率',
      sqlExpression: 'SUM(return_qty) / NULLIF(SUM(total_shipped_qty), 0)',
      description:
        '退货数量占总出货数量的比例。退货率是衡量产品质量、包装完好性和客户满意度的综合指标，需区分质量退货和非质量退货。',
    },
    {
      term: 'SKU',
      sqlExpression: 'COUNT(DISTINCT sku)',
      description:
        'Stock Keeping Unit（库存量单位）的缩写，是库存管理的最小单位。每一个 SKU 对应一个唯一的商品属性组合（如品类+规格+颜色+批次）。SKU 数量是衡量库存复杂度的关键指标。',
    },
  ],

  knowledgeDocs: [
    {
      title: '供应链数据仓库分层设计与使用指南',
      content: `# 供应链数据仓库分层设计

## 数据分层架构
本供应链数据仓库采用经典四层架构（ODS → DWD → DWS → ADS），覆盖供应链全链路数据。

### ODS层（操作数据存储）
存储从各业务系统同步的原始数据，包含供应商、物料、采购、库存、仓储、物流、质量、生产、退货、冷链监控等主数据和事务数据。
- 表命名规范：\`ods_<业务实体>\`
- 保持与源系统一致的粒度，不做清洗和聚合

### DWD层（明细数据）
经过清洗、标准化、去重后的事实表和维度表。
- 事实表命名：\`dwd_fact_<业务事件>\`，如 dwd_fact_purchase_order
- 维度表命名：\`dwd_dim_<维度实体>\`，如 dwd_dim_supplier
- 每行记录一个业务事件的完整上下文，包含计算后的派生字段

### DWS层（汇总数据）
面向分析主题的轻度汇总宽表。
- 表命名：\`dws_<分析主题>_<汇总粒度>\`，如 dws_supplier_delivery_summary
- 按维度组合进行预聚合，减少下游查询的 JOIN 次数

### ADS层（应用数据）
直接面向报表和应用的高度汇总数据。
- 表命名：\`ads_<应用场景>\`，如 ads_supply_chain_kpi_dashboard
- 可直接用于看板展示、API 输出和导出报告

## 常见查询场景
1. **库存周转分析**：查询 dws_inventory_turnover_summary，按物料分类和仓库维度分析周转率
2. **供应商评估**：查询 dws_supplier_overall_score + ads_supplier_ranking 进行综合排名
3. **采购成本分析**：查询 ads_procurement_savings_analysis，关注各分类的节省率和趋势
4. **物流效率监控**：查询 dws_logistics_performance_summary，按承运商和线路评估时效
5. **质量管控**：查询 ads_quality_trend_analysis，监控各环节不良率趋势
6. **冷链合规**：查询 ads_cold_chain_compliance_report，确保温控合规率达标
7. **缺货预警**：查询 ads_stockout_risk_alert，及时识别和处理缺货风险`,
      docType: 'document',
    },
  ],

  conversations: [
    {
      title: '查询上月各供应商准时交货率',
      messages: [
        {
          role: 'user',
          content: '帮我查一下上个月各供应商的准时交货率，按供应商排序',
        },
        {
          role: 'assistant',
          content:
            '这是上个月各供应商的准时交货率查询结果。数据来源于供应商交货汇总表，已按准时交货率从高到低排序。',
          sql: `SELECT
  supplier_code,
  supplier_name,
  supplier_type,
  total_orders,
  on_time_orders,
  late_orders,
  ROUND(on_time_rate * 100, 2) AS on_time_rate_pct,
  ROUND(avg_lead_time_days, 1) AS avg_lead_time_days
FROM dws_supplier_delivery_summary
WHERE stat_year = EXTRACT(YEAR FROM CURRENT_DATE - INTERVAL '1 month')
  AND stat_month = EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL '1 month')
ORDER BY on_time_rate DESC;`,
          confidence: 0.95,
        },
      ],
    },
    {
      title: '分析库存周转率低的物料',
      messages: [
        {
          role: 'user',
          content: '哪些物料的库存周转率低于2次？列出物料信息和库存金额',
        },
        {
          role: 'assistant',
          content:
            '以下是本季度库存周转率低于2次的物料清单，按库存金额从高到低排列，帮助识别重点优化对象。',
          sql: `SELECT
  t.material_code,
  t.material_name,
  t.material_type,
  t.category,
  ROUND(t.turnover_times, 2) AS turnover_times,
  ROUND(t.avg_inventory_value, 2) AS avg_inventory_value,
  ROUND(t.total_outbound_value, 2) AS total_outbound_value,
  ROUND(t.turnover_days, 1) AS turnover_days
FROM dws_inventory_turnover_summary t
WHERE t.stat_year = EXTRACT(YEAR FROM CURRENT_DATE)
  AND t.stat_month = EXTRACT(MONTH FROM CURRENT_DATE)
  AND t.turnover_times < 2
ORDER BY t.avg_inventory_value DESC
LIMIT 50;`,
          confidence: 0.92,
        },
      ],
    },
  ],

  queryHistory: [
    {
      naturalLanguage: '查询本月各仓库的利用率',
      generatedSql: `SELECT
  warehouse_code,
  warehouse_name,
  warehouse_type,
  region,
  total_positions,
  occupied_positions,
  ROUND(utilization_rate * 100, 2) AS utilization_rate_pct,
  total_sku_count
FROM dws_warehouse_utilization_daily
WHERE ds = CURRENT_DATE
ORDER BY utilization_rate DESC;`,
      status: 'accepted',
      isGolden: true,
      tablesUsed: ['dws_warehouse_utilization_daily'],
    },
    {
      naturalLanguage: '统计上季度采购金额Top10供应商',
      generatedSql: `SELECT
  supplier_code,
  supplier_name,
  supplier_type,
  SUM(total_po_amount) AS total_amount,
  SUM(total_po_count) AS total_orders,
  ROUND(AVG(avg_unit_price), 2) AS avg_price
FROM dws_supplier_cost_summary
WHERE stat_year = EXTRACT(YEAR FROM CURRENT_DATE - INTERVAL '1 quarter')
  AND stat_month BETWEEN
    EXTRACT(MONTH FROM DATE_TRUNC('quarter', CURRENT_DATE - INTERVAL '1 quarter'))
    AND EXTRACT(MONTH FROM DATE_TRUNC('quarter', CURRENT_DATE - INTERVAL '1 quarter') + INTERVAL '2 months')
GROUP BY supplier_code, supplier_name, supplier_type
ORDER BY total_amount DESC
LIMIT 10;`,
      status: 'accepted',
      isGolden: true,
      tablesUsed: ['dws_supplier_cost_summary'],
    },
    {
      naturalLanguage: '查看有哪些物料低于安全库存需要补货',
      generatedSql: `SELECT
  material_code,
  material_name,
  warehouse_code,
  warehouse_name,
  current_stock,
  safety_stock,
  avg_daily_consumption,
  days_of_supply,
  in_transit_qty,
  risk_level
FROM ads_stockout_risk_alert
WHERE ds = CURRENT_DATE
  AND risk_level >= 3
ORDER BY risk_level DESC, days_of_supply ASC;`,
      status: 'accepted',
      isGolden: false,
      tablesUsed: ['ads_stockout_risk_alert'],
    },
    {
      naturalLanguage: '分析最近3个月的冷链告警趋势',
      generatedSql: `SELECT
  stat_year,
  stat_month,
  warehouse_code,
  warehouse_name,
  total_alerts,
  critical_alerts,
  resolved_count,
  unresolved_count,
  ROUND(avg_resolve_minutes, 1) AS avg_resolve_minutes
FROM dws_cold_chain_alert_summary
WHERE ds >= CURRENT_DATE - INTERVAL '3 months'
ORDER BY stat_year, stat_month, total_alerts DESC;`,
      status: 'pending',
      isGolden: false,
      tablesUsed: ['dws_cold_chain_alert_summary'],
    },
  ],
};
