import type { DomainDefinition } from './types.js';
import { col, generateSummaryTable } from '../generator.js';

/* ================================================================
 * User Growth Analytics Domain
 * ~130 tables across 4 layers (ODS / DWD / DWS / ADS)
 *
 * Areas: registration funnels, retention/cohort, A/B testing,
 * push notifications, user attribution, engagement scoring,
 * lifecycle management, segmentation, channel analytics,
 * referral programs, onboarding, user feedback, NPS surveys.
 * ================================================================ */

export const userGrowthDomain: DomainDefinition = {
  name: '用户增长分析',
  description:
    'Full-spectrum user growth analytics covering registration funnels, ' +
    'retention cohorts, A/B testing, push notifications, attribution, ' +
    'engagement scoring, lifecycle management, segmentation, channel analytics, ' +
    'referral programs, onboarding flows, user feedback, and NPS surveys.',
  dialect: 'postgresql',

  /* ----------------------------------------------------------------
   * TABLES  (~130 total: ODS ~35, DWD ~30, DWS ~35, ADS ~30)
   * ---------------------------------------------------------------- */
  tables: [
    // ============================================================
    //  ODS Layer  (~35 tables) — raw operational data
    // ============================================================

    // --- User core ---
    {
      name: 'ods_user_register',
      comment: '用户注册原始数据',
      layer: 'ods',
      columns: [
        col.id('注册记录ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('username', 100, '用户名'),
        col.varchar('email', 200, '注册邮箱', { isPii: true }),
        col.varchar('phone', 30, '手机号', { isPii: true }),
        col.varchar('register_channel', 50, '注册渠道'),
        col.varchar('register_source', 50, '注册来源'),
        col.varchar('device_type', 30, '设备类型: ios/android/web'),
        col.varchar('os_version', 30, 'OS版本'),
        col.varchar('app_version', 30, 'App版本'),
        col.varchar('ip_address', 50, '注册IP', { isPii: true }),
        col.varchar('country', 50, '国家'),
        col.varchar('city', 50, '城市'),
        col.timestamp('register_time', '注册时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'ods_user_profile',
      comment: '用户画像原始表',
      layer: 'ods',
      columns: [
        col.id('记录ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('nickname', 100, '昵称'),
        col.varchar('gender', 10, '性别'),
        col.date('birthday', '生日'),
        col.varchar('avatar_url', 500, '头像URL'),
        col.varchar('language', 20, '语言偏好'),
        col.varchar('timezone', 50, '时区'),
        col.json('extra_attrs', '扩展属性JSON'),
        col.timestamp('updated_at', '更新时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'ods_user_device',
      comment: '用户设备信息原始表',
      layer: 'ods',
      columns: [
        col.id('记录ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('device_id', 100, '设备唯一标识'),
        col.varchar('device_model', 100, '设备型号'),
        col.varchar('os_type', 20, '操作系统'),
        col.varchar('os_version', 30, 'OS版本'),
        col.varchar('app_version', 30, 'App版本'),
        col.varchar('push_token', 300, '推送Token'),
        col.bool('push_enabled', '是否开启推送'),
        col.timestamp('first_seen_at', '首次出现时间'),
        col.timestamp('last_seen_at', '最后出现时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'ods_user_login',
      comment: '用户登录日志',
      layer: 'ods',
      columns: [
        col.id('日志ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('login_type', 30, '登录方式: password/sms/oauth'),
        col.varchar('device_id', 100, '设备标识'),
        col.varchar('ip_address', 50, '登录IP'),
        col.varchar('geo_country', 50, '国家'),
        col.varchar('geo_city', 50, '城市'),
        col.bool('is_success', '是否成功'),
        col.varchar('fail_reason', 100, '失败原因'),
        col.timestamp('login_time', '登录时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'ods_user_session',
      comment: '用户会话原始数据',
      layer: 'ods',
      columns: [
        col.id('会话ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('device_id', 100, '设备标识'),
        col.timestamp('session_start', '会话开始时间'),
        col.timestamp('session_end', '会话结束时间'),
        col.int('duration_seconds', '会话时长(秒)'),
        col.int('page_views', '页面浏览数'),
        col.int('event_count', '事件数'),
        col.varchar('entry_page', 200, '入口页面'),
        col.varchar('exit_page', 200, '退出页面'),
        col.ds(),
        col.etlTime(),
      ],
    },

    // --- Registration funnel ---
    {
      name: 'ods_register_funnel_event',
      comment: '注册漏斗事件原始表',
      layer: 'ods',
      columns: [
        col.id('事件ID'),
        col.varchar('anonymous_id', 100, '匿名用户标识'),
        col.bigint('user_id', '用户ID(注册后回填)'),
        col.varchar('funnel_step', 30, '漏斗步骤: visit/click_register/fill_form/verify/complete'),
        col.varchar('channel', 50, '渠道'),
        col.varchar('campaign_id', 50, '活动ID'),
        col.varchar('device_type', 30, '设备类型'),
        col.json('event_properties', '事件属性'),
        col.timestamp('event_time', '事件时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'ods_register_verification',
      comment: '注册验证码发送/校验记录',
      layer: 'ods',
      columns: [
        col.id('记录ID'),
        col.varchar('verify_type', 20, '验证类型: sms/email'),
        col.varchar('target', 200, '目标(手机/邮箱)', { isPii: true }),
        col.varchar('code', 10, '验证码'),
        col.bool('is_verified', '是否验证成功'),
        col.timestamp('send_time', '发送时间'),
        col.timestamp('verify_time', '验证时间'),
        col.ds(),
        col.etlTime(),
      ],
    },

    // --- Attribution ---
    {
      name: 'ods_attribution_event',
      comment: '归因事件原始表',
      layer: 'ods',
      columns: [
        col.id('事件ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('attribution_source', 50, '归因来源'),
        col.varchar('attribution_medium', 50, '归因媒介'),
        col.varchar('attribution_campaign', 100, '归因活动'),
        col.varchar('attribution_content', 100, '归因内容'),
        col.varchar('click_id', 100, '点击ID'),
        col.decimal('cost', '12,2', '获客成本'),
        col.timestamp('click_time', '点击时间'),
        col.timestamp('install_time', '安装时间'),
        col.timestamp('register_time', '注册时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'ods_channel_config',
      comment: '渠道配置原始表',
      layer: 'ods',
      columns: [
        col.id('渠道ID'),
        col.varchar('channel_code', 50, '渠道编码'),
        col.varchar('channel_name', 100, '渠道名称'),
        col.varchar('channel_type', 30, '渠道类型: organic/paid/social/referral'),
        col.varchar('platform', 30, '平台'),
        col.varchar('partner_name', 100, '合作方名称'),
        col.bool('is_active', '是否启用'),
        col.decimal('cpi_budget', '12,2', 'CPI预算'),
        col.createdAt(),
        col.updatedAt(),
      ],
    },
    {
      name: 'ods_campaign',
      comment: '营销活动原始表',
      layer: 'ods',
      columns: [
        col.id('活动ID'),
        col.varchar('campaign_name', 200, '活动名称'),
        col.varchar('campaign_type', 30, '活动类型: acquisition/retention/reactivation'),
        col.fk('channel_id', 'ods_channel_config', '渠道ID'),
        col.decimal('budget', '14,2', '预算'),
        col.decimal('spent', '14,2', '已花费'),
        col.date('start_date', '开始日期'),
        col.date('end_date', '结束日期'),
        col.status('活动状态', 'draft/active/paused/completed'),
        col.createdAt(),
        col.updatedAt(),
      ],
    },

    // --- A/B Testing ---
    {
      name: 'ods_ab_experiment',
      comment: 'A/B实验配置原始表',
      layer: 'ods',
      columns: [
        col.id('实验ID'),
        col.varchar('experiment_name', 200, '实验名称'),
        col.varchar('experiment_key', 100, '实验标识'),
        col.varchar('hypothesis', 500, '实验假设'),
        col.varchar('primary_metric', 100, '主指标'),
        col.json('secondary_metrics', '次要指标列表'),
        col.int('traffic_percent', '流量百分比'),
        col.date('start_date', '开始日期'),
        col.date('end_date', '结束日期'),
        col.status('实验状态', 'draft/running/stopped/concluded'),
        col.varchar('owner', 100, '负责人'),
        col.createdAt(),
        col.updatedAt(),
      ],
    },
    {
      name: 'ods_ab_experiment_variant',
      comment: 'A/B实验分组配置',
      layer: 'ods',
      columns: [
        col.id('分组ID'),
        col.fk('experiment_id', 'ods_ab_experiment', '实验ID'),
        col.varchar('variant_key', 50, '分组标识: control/treatment_a/treatment_b'),
        col.varchar('variant_name', 100, '分组名称'),
        col.int('traffic_weight', '流量权重'),
        col.json('config_overrides', '配置覆盖JSON'),
        col.createdAt(),
      ],
    },
    {
      name: 'ods_ab_exposure',
      comment: 'A/B实验曝光日志',
      layer: 'ods',
      columns: [
        col.id('曝光ID'),
        col.fk('experiment_id', 'ods_ab_experiment', '实验ID'),
        col.fk('variant_id', 'ods_ab_experiment_variant', '分组ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('device_id', 100, '设备标识'),
        col.timestamp('exposure_time', '曝光时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'ods_ab_metric_event',
      comment: 'A/B实验指标事件原始表',
      layer: 'ods',
      columns: [
        col.id('事件ID'),
        col.fk('experiment_id', 'ods_ab_experiment', '实验ID'),
        col.fk('variant_id', 'ods_ab_experiment_variant', '分组ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('metric_name', 100, '指标名称'),
        col.decimal('metric_value', '18,4', '指标值'),
        col.timestamp('event_time', '事件时间'),
        col.ds(),
        col.etlTime(),
      ],
    },

    // --- Push notifications ---
    {
      name: 'ods_push_template',
      comment: '推送模板原始表',
      layer: 'ods',
      columns: [
        col.id('模板ID'),
        col.varchar('template_name', 200, '模板名称'),
        col.varchar('push_type', 30, '推送类型: notification/in_app/sms/email'),
        col.varchar('title_template', 300, '标题模板'),
        col.text('body_template', '内容模板'),
        col.varchar('target_action', 100, '目标动作'),
        col.varchar('deeplink', 500, '深链接'),
        col.bool('is_active', '是否启用'),
        col.createdAt(),
        col.updatedAt(),
      ],
    },
    {
      name: 'ods_push_task',
      comment: '推送任务原始表',
      layer: 'ods',
      columns: [
        col.id('任务ID'),
        col.fk('template_id', 'ods_push_template', '模板ID'),
        col.varchar('task_name', 200, '任务名称'),
        col.varchar('audience_type', 30, '受众类型: all/segment/individual'),
        col.varchar('segment_id', 50, '分群ID'),
        col.int('target_count', '目标用户数'),
        col.timestamp('scheduled_time', '计划发送时间'),
        col.timestamp('actual_send_time', '实际发送时间'),
        col.status('任务状态', 'pending/sending/sent/failed'),
        col.createdAt(),
      ],
    },
    {
      name: 'ods_push_send_log',
      comment: '推送发送日志',
      layer: 'ods',
      columns: [
        col.id('日志ID'),
        col.fk('task_id', 'ods_push_task', '任务ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('device_id', 100, '设备标识'),
        col.varchar('push_type', 30, '推送类型'),
        col.bool('is_delivered', '是否送达'),
        col.bool('is_opened', '是否打开'),
        col.bool('is_clicked', '是否点击'),
        col.timestamp('send_time', '发送时间'),
        col.timestamp('deliver_time', '送达时间'),
        col.timestamp('open_time', '打开时间'),
        col.timestamp('click_time', '点击时间'),
        col.ds(),
        col.etlTime(),
      ],
    },

    // --- Referral ---
    {
      name: 'ods_referral_program',
      comment: '裂变活动原始表',
      layer: 'ods',
      columns: [
        col.id('活动ID'),
        col.varchar('program_name', 200, '活动名称'),
        col.varchar('program_type', 30, '类型: invite/share/group_buy'),
        col.varchar('reward_type', 30, '奖励类型: coupon/credit/gift'),
        col.decimal('inviter_reward', '10,2', '邀请人奖励'),
        col.decimal('invitee_reward', '10,2', '被邀请人奖励'),
        col.int('max_invites', '最大邀请数'),
        col.date('start_date', '开始日期'),
        col.date('end_date', '结束日期'),
        col.status('状态', 'active/paused/ended'),
        col.createdAt(),
      ],
    },
    {
      name: 'ods_referral_invite',
      comment: '裂变邀请记录',
      layer: 'ods',
      columns: [
        col.id('记录ID'),
        col.fk('program_id', 'ods_referral_program', '活动ID'),
        col.bigint('inviter_user_id', '邀请人ID'),
        col.bigint('invitee_user_id', '被邀请人ID'),
        col.varchar('invite_code', 30, '邀请码'),
        col.varchar('invite_channel', 50, '邀请渠道'),
        col.bool('is_registered', '被邀请人是否注册'),
        col.bool('is_activated', '被邀请人是否激活'),
        col.bool('reward_issued', '奖励是否发放'),
        col.timestamp('invite_time', '邀请时间'),
        col.timestamp('register_time', '注册时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'ods_referral_reward',
      comment: '裂变奖励发放记录',
      layer: 'ods',
      columns: [
        col.id('记录ID'),
        col.fk('invite_id', 'ods_referral_invite', '邀请记录ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('reward_type', 30, '奖励类型'),
        col.decimal('reward_amount', '10,2', '奖励金额'),
        col.varchar('reward_status', 20, '发放状态: pending/issued/expired'),
        col.timestamp('issued_at', '发放时间'),
        col.ds(),
        col.etlTime(),
      ],
    },

    // --- Onboarding ---
    {
      name: 'ods_onboarding_step',
      comment: '新手引导步骤配置',
      layer: 'ods',
      columns: [
        col.id('步骤ID'),
        col.varchar('step_key', 50, '步骤标识'),
        col.varchar('step_name', 100, '步骤名称'),
        col.int('step_order', '步骤顺序'),
        col.varchar('step_type', 30, '步骤类型: tooltip/modal/highlight/task'),
        col.bool('is_required', '是否必须完成'),
        col.bool('is_active', '是否启用'),
        col.createdAt(),
      ],
    },
    {
      name: 'ods_onboarding_progress',
      comment: '用户新手引导进度',
      layer: 'ods',
      columns: [
        col.id('记录ID'),
        col.bigint('user_id', '用户ID'),
        col.fk('step_id', 'ods_onboarding_step', '步骤ID'),
        col.bool('is_completed', '是否完成'),
        col.bool('is_skipped', '是否跳过'),
        col.timestamp('started_at', '开始时间'),
        col.timestamp('completed_at', '完成时间'),
        col.ds(),
        col.etlTime(),
      ],
    },

    // --- Engagement events ---
    {
      name: 'ods_user_event',
      comment: '用户行为事件原始表',
      layer: 'ods',
      columns: [
        col.id('事件ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('event_name', 100, '事件名称'),
        col.varchar('event_category', 50, '事件类别'),
        col.json('event_properties', '事件属性JSON'),
        col.varchar('page_name', 100, '页面名称'),
        col.varchar('device_id', 100, '设备标识'),
        col.varchar('platform', 20, '平台: ios/android/web'),
        col.timestamp('event_time', '事件时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'ods_page_view',
      comment: '页面浏览原始表',
      layer: 'ods',
      columns: [
        col.id('记录ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('page_name', 200, '页面名称'),
        col.varchar('page_url', 500, '页面URL'),
        col.varchar('referrer', 500, '来源页面'),
        col.int('duration_ms', '停留时长(毫秒)'),
        col.varchar('device_id', 100, '设备标识'),
        col.timestamp('view_time', '浏览时间'),
        col.ds(),
        col.etlTime(),
      ],
    },

    // --- Feedback / NPS ---
    {
      name: 'ods_user_feedback',
      comment: '用户反馈原始表',
      layer: 'ods',
      columns: [
        col.id('反馈ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('feedback_type', 30, '反馈类型: bug/suggestion/complaint/praise'),
        col.varchar('category', 50, '反馈分类'),
        col.text('content', '反馈内容'),
        col.int('rating', '评分(1-5)'),
        col.varchar('app_version', 30, '提交时App版本'),
        col.varchar('contact_info', 200, '联系方式', { isPii: true }),
        col.status('处理状态', 'open/in_progress/resolved/closed'),
        col.timestamp('submitted_at', '提交时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'ods_nps_survey',
      comment: 'NPS调查原始表',
      layer: 'ods',
      columns: [
        col.id('调查ID'),
        col.varchar('survey_name', 200, '调查名称'),
        col.varchar('survey_version', 20, '调查版本'),
        col.varchar('trigger_event', 100, '触发事件'),
        col.int('sample_rate', '采样比例(百分比)'),
        col.date('start_date', '开始日期'),
        col.date('end_date', '结束日期'),
        col.bool('is_active', '是否启用'),
        col.createdAt(),
      ],
    },
    {
      name: 'ods_nps_response',
      comment: 'NPS调查回复原始表',
      layer: 'ods',
      columns: [
        col.id('回复ID'),
        col.fk('survey_id', 'ods_nps_survey', '调查ID'),
        col.bigint('user_id', '用户ID'),
        col.int('score', 'NPS评分(0-10)'),
        col.text('comment', '用户评语'),
        col.varchar('nps_category', 20, 'NPS分类: promoter/passive/detractor'),
        col.varchar('app_version', 30, 'App版本'),
        col.varchar('platform', 20, '平台'),
        col.timestamp('responded_at', '回复时间'),
        col.ds(),
        col.etlTime(),
      ],
    },

    // --- Lifecycle ---
    {
      name: 'ods_lifecycle_rule',
      comment: '生命周期规则配置',
      layer: 'ods',
      columns: [
        col.id('规则ID'),
        col.varchar('lifecycle_stage', 30, '生命周期阶段: new/active/dormant/churned/reactivated'),
        col.varchar('rule_name', 100, '规则名称'),
        col.json('conditions', '判定条件JSON'),
        col.int('priority', '优先级'),
        col.bool('is_active', '是否启用'),
        col.createdAt(),
        col.updatedAt(),
      ],
    },
    {
      name: 'ods_user_lifecycle_log',
      comment: '用户生命周期变更日志',
      layer: 'ods',
      columns: [
        col.id('日志ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('prev_stage', 30, '变更前阶段'),
        col.varchar('curr_stage', 30, '变更后阶段'),
        col.fk('rule_id', 'ods_lifecycle_rule', '触发规则ID'),
        col.timestamp('changed_at', '变更时间'),
        col.ds(),
        col.etlTime(),
      ],
    },

    // --- Segmentation ---
    {
      name: 'ods_user_segment',
      comment: '用户分群定义',
      layer: 'ods',
      columns: [
        col.id('分群ID'),
        col.varchar('segment_name', 200, '分群名称'),
        col.varchar('segment_type', 30, '分群类型: static/dynamic/rulebase'),
        col.json('segment_rules', '分群规则JSON'),
        col.int('user_count', '用户数量'),
        col.varchar('owner', 100, '负责人'),
        col.bool('is_active', '是否启用'),
        col.createdAt(),
        col.updatedAt(),
      ],
    },
    {
      name: 'ods_user_segment_member',
      comment: '用户分群成员关系',
      layer: 'ods',
      columns: [
        col.id('记录ID'),
        col.fk('segment_id', 'ods_user_segment', '分群ID'),
        col.bigint('user_id', '用户ID'),
        col.timestamp('joined_at', '加入时间'),
        col.timestamp('removed_at', '移除时间'),
        col.bool('is_active', '是否在分群中'),
        col.ds(),
        col.etlTime(),
      ],
    },

    // --- Channel analytics ---
    {
      name: 'ods_ad_impression',
      comment: '广告曝光原始数据',
      layer: 'ods',
      columns: [
        col.id('记录ID'),
        col.fk('campaign_id', 'ods_campaign', '活动ID'),
        col.varchar('ad_group_id', 50, '广告组ID'),
        col.varchar('creative_id', 50, '创意ID'),
        col.varchar('platform', 30, '投放平台'),
        col.bigint('impressions', '曝光次数'),
        col.bigint('clicks', '点击次数'),
        col.decimal('spend', '12,2', '花费'),
        col.date('stat_date', '统计日期'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'ods_deeplink_click',
      comment: '深链接点击原始表',
      layer: 'ods',
      columns: [
        col.id('记录ID'),
        col.varchar('link_id', 50, '链接标识'),
        col.varchar('deeplink_url', 500, '深链接URL'),
        col.varchar('source', 50, '来源'),
        col.varchar('medium', 50, '媒介'),
        col.varchar('campaign', 100, '活动'),
        col.varchar('device_type', 30, '设备类型'),
        col.varchar('ip_address', 50, 'IP地址'),
        col.bool('is_matched', '是否匹配到用户'),
        col.bigint('user_id', '匹配到的用户ID'),
        col.timestamp('click_time', '点击时间'),
        col.ds(),
        col.etlTime(),
      ],
    },

    // --- Engagement scoring ---
    {
      name: 'ods_engagement_rule',
      comment: '用户活跃度评分规则',
      layer: 'ods',
      columns: [
        col.id('规则ID'),
        col.varchar('rule_name', 100, '规则名称'),
        col.varchar('event_name', 100, '关联事件'),
        col.int('score_weight', '权重得分'),
        col.varchar('decay_type', 20, '衰减方式: none/linear/exponential'),
        col.int('decay_days', '衰减周期(天)'),
        col.bool('is_active', '是否启用'),
        col.createdAt(),
      ],
    },
    {
      name: 'ods_user_engagement_score',
      comment: '用户活跃度得分原始表',
      layer: 'ods',
      columns: [
        col.id('记录ID'),
        col.bigint('user_id', '用户ID'),
        col.decimal('total_score', '10,2', '总得分'),
        col.json('score_breakdown', '各维度得分明细'),
        col.varchar('engagement_level', 20, '活跃等级: high/medium/low/inactive'),
        col.date('score_date', '评分日期'),
        col.ds(),
        col.etlTime(),
      ],
    },

    // --- Misc ODS ---
    {
      name: 'ods_app_crash_log',
      comment: 'App崩溃日志',
      layer: 'ods',
      columns: [
        col.id('日志ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('device_id', 100, '设备标识'),
        col.varchar('app_version', 30, 'App版本'),
        col.varchar('os_version', 30, 'OS版本'),
        col.text('crash_stack', '崩溃堆栈'),
        col.varchar('crash_type', 50, '崩溃类型'),
        col.timestamp('crash_time', '崩溃时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'ods_user_uninstall',
      comment: '用户卸载记录',
      layer: 'ods',
      columns: [
        col.id('记录ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('device_id', 100, '设备标识'),
        col.varchar('app_version', 30, '卸载前版本'),
        col.int('days_since_install', '安装到卸载天数'),
        col.varchar('last_active_page', 200, '最后活跃页面'),
        col.timestamp('uninstall_time', '卸载时间'),
        col.ds(),
        col.etlTime(),
      ],
    },

    // ============================================================
    //  DWD Layer  (~30 tables) — cleansed detail fact tables
    // ============================================================

    {
      name: 'dwd_user_register_detail',
      comment: '注册明细表(清洗去重)',
      layer: 'dwd',
      columns: [
        col.id('注册ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('register_channel', 50, '注册渠道(标准化)'),
        col.varchar('register_source', 50, '注册来源(标准化)'),
        col.varchar('device_type', 30, '设备类型'),
        col.varchar('country', 50, '国家'),
        col.varchar('city', 50, '城市'),
        col.varchar('attribution_source', 50, '归因来源'),
        col.varchar('attribution_medium', 50, '归因媒介'),
        col.varchar('attribution_campaign', 100, '归因活动'),
        col.bool('is_organic', '是否自然流量'),
        col.timestamp('register_time', '注册时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_user_login_detail',
      comment: '登录明细表',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('login_type', 30, '登录方式(标准化)'),
        col.varchar('device_type', 30, '设备类型'),
        col.varchar('platform', 20, '平台'),
        col.varchar('country', 50, '国家'),
        col.varchar('city', 50, '城市'),
        col.bool('is_first_login', '是否首次登录'),
        col.int('days_since_register', '注册至今天数'),
        col.timestamp('login_time', '登录时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_session_detail',
      comment: '会话明细表(清洗后)',
      layer: 'dwd',
      columns: [
        col.id('会话ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('device_type', 30, '设备类型'),
        col.varchar('platform', 20, '平台'),
        col.int('duration_seconds', '会话时长(秒)'),
        col.int('page_views', '页面浏览数'),
        col.int('event_count', '事件数'),
        col.varchar('entry_page', 200, '入口页面'),
        col.varchar('exit_page', 200, '退出页面'),
        col.bool('is_bounce', '是否跳出(单页退出)'),
        col.timestamp('session_start', '会话开始'),
        col.timestamp('session_end', '会话结束'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_register_funnel_detail',
      comment: '注册漏斗明细表',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.varchar('anonymous_id', 100, '匿名标识'),
        col.bigint('user_id', '用户ID'),
        col.varchar('funnel_step', 30, '漏斗步骤(标准化)'),
        col.int('step_order', '步骤序号'),
        col.varchar('channel', 50, '渠道'),
        col.varchar('device_type', 30, '设备类型'),
        col.int('time_from_prev_step_sec', '距上步时长(秒)'),
        col.timestamp('event_time', '事件时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_attribution_detail',
      comment: '归因明细表',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('attribution_model', 30, '归因模型: last_click/first_click/linear'),
        col.varchar('source', 50, '来源'),
        col.varchar('medium', 50, '媒介'),
        col.varchar('campaign', 100, '活动'),
        col.fk('channel_id', 'ods_channel_config', '渠道ID'),
        col.decimal('cost', '12,2', '获客成本'),
        col.int('click_to_install_sec', '点击到安装时长(秒)'),
        col.int('install_to_register_sec', '安装到注册时长(秒)'),
        col.timestamp('register_time', '注册时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_ab_exposure_detail',
      comment: 'A/B实验曝光明细',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.fk('experiment_id', 'ods_ab_experiment', '实验ID'),
        col.varchar('experiment_key', 100, '实验标识'),
        col.varchar('variant_key', 50, '分组标识'),
        col.bigint('user_id', '用户ID'),
        col.varchar('platform', 20, '平台'),
        col.bool('is_first_exposure', '是否首次曝光'),
        col.timestamp('exposure_time', '曝光时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_ab_conversion_detail',
      comment: 'A/B实验转化明细',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.fk('experiment_id', 'ods_ab_experiment', '实验ID'),
        col.varchar('variant_key', 50, '分组标识'),
        col.bigint('user_id', '用户ID'),
        col.varchar('metric_name', 100, '转化指标'),
        col.decimal('metric_value', '18,4', '指标值'),
        col.int('time_to_convert_sec', '曝光到转化时长(秒)'),
        col.timestamp('convert_time', '转化时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_push_delivery_detail',
      comment: '推送送达明细表',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.fk('task_id', 'ods_push_task', '任务ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('push_type', 30, '推送类型'),
        col.varchar('platform', 20, '平台'),
        col.bool('is_delivered', '是否送达'),
        col.bool('is_opened', '是否打开'),
        col.bool('is_clicked', '是否点击'),
        col.int('deliver_delay_sec', '送达延迟(秒)'),
        col.int('open_delay_sec', '打开延迟(秒)'),
        col.timestamp('send_time', '发送时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_referral_detail',
      comment: '裂变邀请明细表',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.fk('program_id', 'ods_referral_program', '活动ID'),
        col.bigint('inviter_id', '邀请人ID'),
        col.bigint('invitee_id', '被邀请人ID'),
        col.varchar('invite_channel', 50, '邀请渠道'),
        col.bool('is_registered', '是否注册'),
        col.bool('is_activated', '是否激活'),
        col.int('invite_to_register_sec', '邀请到注册时长(秒)'),
        col.decimal('inviter_reward_amount', '10,2', '邀请人奖励金额'),
        col.decimal('invitee_reward_amount', '10,2', '被邀请人奖励金额'),
        col.timestamp('invite_time', '邀请时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_onboarding_detail',
      comment: '新手引导明细表',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('step_key', 50, '步骤标识'),
        col.varchar('step_name', 100, '步骤名称'),
        col.int('step_order', '步骤序号'),
        col.bool('is_completed', '是否完成'),
        col.bool('is_skipped', '是否跳过'),
        col.int('time_spent_sec', '该步骤耗时(秒)'),
        col.timestamp('started_at', '开始时间'),
        col.timestamp('completed_at', '完成时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_user_event_detail',
      comment: '用户行为事件明细(清洗)',
      layer: 'dwd',
      columns: [
        col.id('事件ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('event_name', 100, '事件名称(标准化)'),
        col.varchar('event_category', 50, '事件类别(标准化)'),
        col.varchar('page_name', 100, '页面名称'),
        col.varchar('platform', 20, '平台'),
        col.varchar('device_type', 30, '设备类型'),
        col.json('event_properties', '事件属性'),
        col.timestamp('event_time', '事件时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_feedback_detail',
      comment: '用户反馈明细表',
      layer: 'dwd',
      columns: [
        col.id('反馈ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('feedback_type', 30, '反馈类型(标准化)'),
        col.varchar('category', 50, '反馈分类(标准化)'),
        col.int('rating', '评分'),
        col.varchar('sentiment', 20, '情感: positive/neutral/negative'),
        col.varchar('lifecycle_stage', 30, '提交时生命周期阶段'),
        col.int('days_since_register', '注册天数'),
        col.timestamp('submitted_at', '提交时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_nps_response_detail',
      comment: 'NPS回复明细表',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.fk('survey_id', 'ods_nps_survey', '调查ID'),
        col.bigint('user_id', '用户ID'),
        col.int('score', 'NPS评分(0-10)'),
        col.varchar('nps_category', 20, '分类: promoter/passive/detractor'),
        col.varchar('platform', 20, '平台'),
        col.varchar('lifecycle_stage', 30, '回复时生命周期阶段'),
        col.int('days_since_register', '注册天数'),
        col.timestamp('responded_at', '回复时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_lifecycle_transition_detail',
      comment: '生命周期转移明细表',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('from_stage', 30, '转移前阶段'),
        col.varchar('to_stage', 30, '转移后阶段'),
        col.varchar('trigger_reason', 100, '触发原因'),
        col.int('days_in_prev_stage', '前阶段停留天数'),
        col.timestamp('transition_time', '转移时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_engagement_score_detail',
      comment: '用户活跃度得分明细',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.bigint('user_id', '用户ID'),
        col.decimal('total_score', '10,2', '总活跃得分'),
        col.decimal('login_score', '10,2', '登录维度得分'),
        col.decimal('action_score', '10,2', '操作维度得分'),
        col.decimal('social_score', '10,2', '社交维度得分'),
        col.varchar('engagement_level', 20, '活跃等级'),
        col.varchar('lifecycle_stage', 30, '生命周期阶段'),
        col.date('score_date', '评分日期'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_channel_cost_detail',
      comment: '渠道投放成本明细',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.fk('campaign_id', 'ods_campaign', '活动ID'),
        col.fk('channel_id', 'ods_channel_config', '渠道ID'),
        col.varchar('ad_group_id', 50, '广告组ID'),
        col.varchar('platform', 30, '投放平台'),
        col.bigint('impressions', '曝光数'),
        col.bigint('clicks', '点击数'),
        col.bigint('installs', '安装数'),
        col.bigint('registers', '注册数'),
        col.decimal('spend', '12,2', '花费'),
        col.date('stat_date', '统计日期'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_user_activation_detail',
      comment: '用户激活明细表',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('activation_event', 100, '激活事件'),
        col.int('time_to_activate_sec', '注册到激活时长(秒)'),
        col.varchar('register_channel', 50, '注册渠道'),
        col.varchar('device_type', 30, '设备类型'),
        col.varchar('platform', 20, '平台'),
        col.timestamp('register_time', '注册时间'),
        col.timestamp('activation_time', '激活时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_user_churn_detail',
      comment: '用户流失明细表',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.bigint('user_id', '用户ID'),
        col.int('inactive_days', '不活跃天数'),
        col.varchar('last_lifecycle_stage', 30, '最后生命周期阶段'),
        col.decimal('last_engagement_score', '10,2', '最后活跃得分'),
        col.varchar('last_active_page', 200, '最后活跃页面'),
        col.varchar('register_channel', 50, '注册渠道'),
        col.int('total_active_days', '累计活跃天数'),
        col.timestamp('last_active_time', '最后活跃时间'),
        col.timestamp('churn_time', '标记流失时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_segment_snapshot',
      comment: '分群快照明细(每日)',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.fk('segment_id', 'ods_user_segment', '分群ID'),
        col.varchar('segment_name', 200, '分群名称'),
        col.bigint('user_id', '用户ID'),
        col.varchar('lifecycle_stage', 30, '生命周期阶段'),
        col.decimal('engagement_score', '10,2', '活跃得分'),
        col.date('snapshot_date', '快照日期'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_deeplink_attribution_detail',
      comment: '深链接归因明细表',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.varchar('link_id', 50, '链接标识'),
        col.bigint('user_id', '用户ID'),
        col.varchar('source', 50, '来源'),
        col.varchar('medium', 50, '媒介'),
        col.varchar('campaign', 100, '活动'),
        col.varchar('device_type', 30, '设备类型'),
        col.bool('is_new_user', '是否新用户'),
        col.bool('is_reactivated', '是否召回用户'),
        col.timestamp('click_time', '点击时间'),
        col.timestamp('action_time', '后续动作时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_push_response_detail',
      comment: '推送用户响应明细',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.fk('task_id', 'ods_push_task', '任务ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('push_type', 30, '推送类型'),
        col.varchar('action_type', 30, '响应类型: open/click/dismiss/unsubscribe'),
        col.varchar('target_page', 200, '目标页面'),
        col.int('time_to_action_sec', '推送到响应时长(秒)'),
        col.int('subsequent_session_sec', '后续会话时长(秒)'),
        col.timestamp('action_time', '响应时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_crash_impact_detail',
      comment: '崩溃影响明细',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('crash_type', 50, '崩溃类型'),
        col.varchar('app_version', 30, 'App版本'),
        col.int('crash_count_7d', '近7日崩溃次数'),
        col.bool('is_churned_after', '崩溃后是否流失'),
        col.int('days_to_churn', '崩溃后流失天数'),
        col.timestamp('first_crash_time', '首次崩溃时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_uninstall_detail',
      comment: '卸载明细表',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('register_channel', 50, '注册渠道'),
        col.varchar('lifecycle_stage', 30, '卸载时生命周期'),
        col.int('days_since_install', '安装天数'),
        col.int('total_sessions', '累计会话数'),
        col.decimal('engagement_score', '10,2', '卸载前活跃得分'),
        col.varchar('last_nps_category', 20, '最后NPS分类'),
        col.timestamp('uninstall_time', '卸载时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_page_view_detail',
      comment: '页面浏览明细表',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('page_name', 200, '页面名称(标准化)'),
        col.varchar('page_category', 50, '页面分类'),
        col.varchar('platform', 20, '平台'),
        col.int('duration_ms', '停留时长(毫秒)'),
        col.bool('is_bounce', '是否跳出'),
        col.varchar('referrer_page', 200, '来源页面'),
        col.timestamp('view_time', '浏览时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_ab_experiment_summary',
      comment: 'A/B实验维度汇总明细',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.fk('experiment_id', 'ods_ab_experiment', '实验ID'),
        col.varchar('experiment_key', 100, '实验标识'),
        col.varchar('variant_key', 50, '分组标识'),
        col.varchar('metric_name', 100, '指标名称'),
        col.bigint('sample_size', '样本量'),
        col.decimal('metric_sum', '18,4', '指标总和'),
        col.decimal('metric_mean', '18,6', '指标均值'),
        col.decimal('metric_variance', '18,6', '指标方差'),
        col.date('stat_date', '统计日期'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_push_unsubscribe_detail',
      comment: '推送退订明细表',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('push_type', 30, '推送类型'),
        col.varchar('unsubscribe_reason', 100, '退订原因'),
        col.varchar('platform', 20, '平台'),
        col.int('push_received_count_7d', '近7日接收推送数'),
        col.timestamp('unsubscribe_time', '退订时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_referral_chain_detail',
      comment: '裂变链路明细(多级邀请)',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.fk('program_id', 'ods_referral_program', '活动ID'),
        col.bigint('root_inviter_id', '链路发起人ID'),
        col.bigint('inviter_id', '直接邀请人ID'),
        col.bigint('invitee_id', '被邀请人ID'),
        col.int('chain_depth', '链路层级'),
        col.bool('is_activated', '是否激活'),
        col.timestamp('invite_time', '邀请时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_user_reactivation_detail',
      comment: '用户召回明细表',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('reactivation_method', 50, '召回方式: push/sms/email/ad'),
        col.int('churned_days', '流失天数'),
        col.varchar('return_page', 200, '回归着陆页'),
        col.int('sessions_after_7d', '召回后7日会话数'),
        col.bool('is_retained_d7', '召回后7日是否留存'),
        col.timestamp('reactivation_time', '召回时间'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_user_device_detail',
      comment: '用户设备明细表(清洗去重)',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('device_id', 100, '设备标识'),
        col.varchar('device_model', 100, '设备型号(标准化)'),
        col.varchar('os_type', 20, '操作系统'),
        col.varchar('os_version', 30, 'OS版本'),
        col.bool('is_primary_device', '是否主设备'),
        col.int('total_sessions', '该设备总会话数'),
        col.timestamp('first_seen_at', '首次出现'),
        col.timestamp('last_seen_at', '最后出现'),
        col.ds(),
        col.etlTime(),
      ],
    },
    {
      name: 'dwd_campaign_attribution_detail',
      comment: '活动归因明细表',
      layer: 'dwd',
      columns: [
        col.id('记录ID'),
        col.fk('campaign_id', 'ods_campaign', '活动ID'),
        col.bigint('user_id', '用户ID'),
        col.varchar('attribution_model', 30, '归因模型'),
        col.decimal('attributed_cost', '12,2', '归因成本'),
        col.bool('is_activated', '是否激活'),
        col.bool('is_retained_d7', '是否7日留存'),
        col.decimal('ltv_30d', '12,2', '30日LTV'),
        col.timestamp('register_time', '注册时间'),
        col.ds(),
        col.etlTime(),
      ],
    },

    // ============================================================
    //  DWS Layer  (~35 tables) — aggregated summary tables
    // ============================================================

    generateSummaryTable(
      'dws',
      'daily_user_active',
      '每日用户活跃汇总',
      'dws',
      [
        { name: 'platform', comment: '平台' },
        { name: 'country', comment: '国家' },
      ],
      [
        { name: 'dau', type: 'bigint', comment: '日活跃用户数(DAU)' },
        { name: 'new_users', type: 'bigint', comment: '新注册用户数' },
        { name: 'returning_users', type: 'bigint', comment: '回访用户数' },
        { name: 'total_sessions', type: 'bigint', comment: '总会话数' },
        { name: 'avg_session_duration_sec', type: 'decimal', comment: '平均会话时长(秒)' },
        { name: 'total_page_views', type: 'bigint', comment: '总页面浏览数' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'weekly_user_active',
      '每周用户活跃汇总',
      'dws',
      [
        { name: 'platform', comment: '平台' },
        { name: 'country', comment: '国家' },
        { name: 'week_start', comment: '周起始日期' },
      ],
      [
        { name: 'wau', type: 'bigint', comment: '周活跃用户数(WAU)' },
        { name: 'new_users', type: 'bigint', comment: '新注册用户数' },
        { name: 'avg_dau', type: 'decimal', comment: '日均DAU' },
        { name: 'total_sessions', type: 'bigint', comment: '总会话数' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'monthly_user_active',
      '每月用户活跃汇总',
      'dws',
      [
        { name: 'platform', comment: '平台' },
        { name: 'country', comment: '国家' },
        { name: 'month_id', comment: '月份(YYYY-MM)' },
      ],
      [
        { name: 'mau', type: 'bigint', comment: '月活跃用户数(MAU)' },
        { name: 'new_users', type: 'bigint', comment: '新注册用户数' },
        { name: 'avg_dau', type: 'decimal', comment: '日均DAU' },
        { name: 'dau_mau_ratio', type: 'decimal', comment: 'DAU/MAU比值(粘性)' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'retention_cohort',
      '留存率Cohort汇总',
      'dws',
      [
        { name: 'cohort_date', comment: '注册日期(cohort)' },
        { name: 'platform', comment: '平台' },
        { name: 'register_channel', comment: '注册渠道' },
      ],
      [
        { name: 'cohort_size', type: 'bigint', comment: 'Cohort用户数' },
        { name: 'retained_d1', type: 'bigint', comment: '次日留存用户数' },
        { name: 'retained_d3', type: 'bigint', comment: '3日留存用户数' },
        { name: 'retained_d7', type: 'bigint', comment: '7日留存用户数' },
        { name: 'retained_d14', type: 'bigint', comment: '14日留存用户数' },
        { name: 'retained_d30', type: 'bigint', comment: '30日留存用户数' },
        { name: 'retention_d1_rate', type: 'decimal', comment: '次日留存率' },
        { name: 'retention_d7_rate', type: 'decimal', comment: '7日留存率' },
        { name: 'retention_d30_rate', type: 'decimal', comment: '30日留存率' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'register_funnel',
      '注册漏斗汇总',
      'dws',
      [
        { name: 'channel', comment: '渠道' },
        { name: 'device_type', comment: '设备类型' },
      ],
      [
        { name: 'visit_count', type: 'bigint', comment: '访问数' },
        { name: 'click_register_count', type: 'bigint', comment: '点击注册数' },
        { name: 'fill_form_count', type: 'bigint', comment: '填写表单数' },
        { name: 'verify_count', type: 'bigint', comment: '验证通过数' },
        { name: 'complete_count', type: 'bigint', comment: '注册完成数' },
        { name: 'overall_conversion_rate', type: 'decimal', comment: '总体转化率' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'attribution_channel',
      '归因渠道汇总',
      'dws',
      [
        { name: 'source', comment: '来源' },
        { name: 'medium', comment: '媒介' },
        { name: 'campaign', comment: '活动' },
      ],
      [
        { name: 'impressions', type: 'bigint', comment: '曝光数' },
        { name: 'clicks', type: 'bigint', comment: '点击数' },
        { name: 'installs', type: 'bigint', comment: '安装数' },
        { name: 'registers', type: 'bigint', comment: '注册数' },
        { name: 'activated_users', type: 'bigint', comment: '激活用户数' },
        { name: 'total_cost', type: 'decimal', comment: '总成本' },
        { name: 'cpi', type: 'decimal', comment: '单次安装成本(CPI)' },
        { name: 'cpa', type: 'decimal', comment: '单次获客成本(CPA)' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'ab_experiment_result',
      'A/B实验结果汇总',
      'dws',
      [
        { name: 'experiment_key', comment: '实验标识' },
        { name: 'variant_key', comment: '分组标识' },
        { name: 'metric_name', comment: '指标名称' },
      ],
      [
        { name: 'sample_size', type: 'bigint', comment: '样本量' },
        { name: 'conversion_count', type: 'bigint', comment: '转化数' },
        { name: 'conversion_rate', type: 'decimal', comment: '转化率' },
        { name: 'metric_mean', type: 'decimal', comment: '指标均值' },
        { name: 'metric_stddev', type: 'decimal', comment: '指标标准差' },
        { name: 'p_value', type: 'decimal', comment: 'P值' },
        { name: 'ci_lower', type: 'decimal', comment: '置信区间下界' },
        { name: 'ci_upper', type: 'decimal', comment: '置信区间上界' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'push_task_summary',
      '推送任务汇总',
      'dws',
      [
        { name: 'push_type', comment: '推送类型' },
        { name: 'platform', comment: '平台' },
      ],
      [
        { name: 'target_count', type: 'bigint', comment: '目标用户数' },
        { name: 'sent_count', type: 'bigint', comment: '发送数' },
        { name: 'delivered_count', type: 'bigint', comment: '送达数' },
        { name: 'opened_count', type: 'bigint', comment: '打开数' },
        { name: 'clicked_count', type: 'bigint', comment: '点击数' },
        { name: 'delivery_rate', type: 'decimal', comment: '送达率' },
        { name: 'open_rate', type: 'decimal', comment: '打开率' },
        { name: 'click_rate', type: 'decimal', comment: '点击率' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'referral_program_summary',
      '裂变活动汇总',
      'dws',
      [
        { name: 'program_name', comment: '活动名称' },
        { name: 'invite_channel', comment: '邀请渠道' },
      ],
      [
        { name: 'total_invites', type: 'bigint', comment: '总邀请数' },
        { name: 'registered_invitees', type: 'bigint', comment: '注册被邀请人数' },
        { name: 'activated_invitees', type: 'bigint', comment: '激活被邀请人数' },
        { name: 'conversion_rate', type: 'decimal', comment: '转化率' },
        { name: 'total_reward_amount', type: 'decimal', comment: '总奖励金额' },
        { name: 'avg_invites_per_user', type: 'decimal', comment: '人均邀请数' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'onboarding_funnel',
      '新手引导漏斗汇总',
      'dws',
      [
        { name: 'platform', comment: '平台' },
        { name: 'register_channel', comment: '注册渠道' },
      ],
      [
        { name: 'total_users', type: 'bigint', comment: '总用户数' },
        { name: 'step1_completed', type: 'bigint', comment: '步骤1完成数' },
        { name: 'step2_completed', type: 'bigint', comment: '步骤2完成数' },
        { name: 'step3_completed', type: 'bigint', comment: '步骤3完成数' },
        { name: 'all_completed', type: 'bigint', comment: '全部完成数' },
        { name: 'completion_rate', type: 'decimal', comment: '完成率' },
        { name: 'avg_time_to_complete_sec', type: 'decimal', comment: '平均完成时长(秒)' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'engagement_level_daily',
      '每日活跃等级分布',
      'dws',
      [
        { name: 'engagement_level', comment: '活跃等级' },
        { name: 'platform', comment: '平台' },
      ],
      [
        { name: 'user_count', type: 'bigint', comment: '用户数' },
        { name: 'avg_score', type: 'decimal', comment: '平均得分' },
        { name: 'avg_sessions', type: 'decimal', comment: '平均会话数' },
        { name: 'avg_events', type: 'decimal', comment: '平均事件数' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'lifecycle_stage_daily',
      '每日生命周期阶段分布',
      'dws',
      [
        { name: 'lifecycle_stage', comment: '生命周期阶段' },
        { name: 'platform', comment: '平台' },
      ],
      [
        { name: 'user_count', type: 'bigint', comment: '用户数' },
        { name: 'pct_of_total', type: 'decimal', comment: '占总用户比例' },
        { name: 'avg_engagement_score', type: 'decimal', comment: '平均活跃得分' },
        { name: 'transition_in_count', type: 'bigint', comment: '流入用户数' },
        { name: 'transition_out_count', type: 'bigint', comment: '流出用户数' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'lifecycle_transition_matrix',
      '生命周期转移矩阵',
      'dws',
      [
        { name: 'from_stage', comment: '转移前阶段' },
        { name: 'to_stage', comment: '转移后阶段' },
      ],
      [
        { name: 'transition_count', type: 'bigint', comment: '转移用户数' },
        { name: 'avg_days_in_prev_stage', type: 'decimal', comment: '前阶段平均停留天数' },
        { name: 'transition_rate', type: 'decimal', comment: '转移率' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'nps_survey_summary',
      'NPS调查汇总',
      'dws',
      [
        { name: 'survey_name', comment: '调查名称' },
        { name: 'platform', comment: '平台' },
      ],
      [
        { name: 'response_count', type: 'bigint', comment: '回复数' },
        { name: 'promoter_count', type: 'bigint', comment: '推荐者数' },
        { name: 'passive_count', type: 'bigint', comment: '中立者数' },
        { name: 'detractor_count', type: 'bigint', comment: '贬损者数' },
        { name: 'nps_score', type: 'decimal', comment: 'NPS分数' },
        { name: 'avg_score', type: 'decimal', comment: '平均评分' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'feedback_category_summary',
      '反馈分类汇总',
      'dws',
      [
        { name: 'feedback_type', comment: '反馈类型' },
        { name: 'category', comment: '分类' },
        { name: 'sentiment', comment: '情感' },
      ],
      [
        { name: 'feedback_count', type: 'bigint', comment: '反馈数' },
        { name: 'avg_rating', type: 'decimal', comment: '平均评分' },
        { name: 'resolved_count', type: 'bigint', comment: '已解决数' },
        { name: 'avg_resolve_time_hour', type: 'decimal', comment: '平均解决时长(小时)' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'channel_roi_daily',
      '渠道ROI每日汇总',
      'dws',
      [
        { name: 'channel_name', comment: '渠道名称' },
        { name: 'campaign_name', comment: '活动名称' },
        { name: 'platform', comment: '平台' },
      ],
      [
        { name: 'impressions', type: 'bigint', comment: '曝光数' },
        { name: 'clicks', type: 'bigint', comment: '点击数' },
        { name: 'installs', type: 'bigint', comment: '安装数' },
        { name: 'registers', type: 'bigint', comment: '注册数' },
        { name: 'spend', type: 'decimal', comment: '花费' },
        { name: 'ctr', type: 'decimal', comment: '点击率(CTR)' },
        { name: 'cvr', type: 'decimal', comment: '转化率(CVR)' },
        { name: 'cpi', type: 'decimal', comment: '单次安装成本' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'segment_profile',
      '分群画像汇总',
      'dws',
      [
        { name: 'segment_name', comment: '分群名称' },
        { name: 'lifecycle_stage', comment: '生命周期阶段' },
      ],
      [
        { name: 'user_count', type: 'bigint', comment: '用户数' },
        { name: 'avg_engagement_score', type: 'decimal', comment: '平均活跃得分' },
        { name: 'avg_session_count_7d', type: 'decimal', comment: '近7日平均会话数' },
        { name: 'avg_retention_d7', type: 'decimal', comment: '7日留存率' },
        { name: 'avg_nps_score', type: 'decimal', comment: '平均NPS分数' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'churn_analysis',
      '流失分析汇总',
      'dws',
      [
        { name: 'register_channel', comment: '注册渠道' },
        { name: 'lifecycle_stage', comment: '流失前阶段' },
        { name: 'platform', comment: '平台' },
      ],
      [
        { name: 'churned_users', type: 'bigint', comment: '流失用户数' },
        { name: 'avg_active_days', type: 'decimal', comment: '平均活跃天数' },
        { name: 'avg_engagement_score', type: 'decimal', comment: '平均活跃得分' },
        { name: 'avg_session_count', type: 'decimal', comment: '平均会话数' },
        { name: 'churn_rate', type: 'decimal', comment: '流失率' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'activation_analysis',
      '激活分析汇总',
      'dws',
      [
        { name: 'register_channel', comment: '注册渠道' },
        { name: 'device_type', comment: '设备类型' },
        { name: 'platform', comment: '平台' },
      ],
      [
        { name: 'total_registers', type: 'bigint', comment: '注册用户数' },
        { name: 'activated_users', type: 'bigint', comment: '激活用户数' },
        { name: 'activation_rate', type: 'decimal', comment: '激活率' },
        { name: 'avg_time_to_activate_sec', type: 'decimal', comment: '平均激活时长(秒)' },
        { name: 'median_time_to_activate_sec', type: 'decimal', comment: '中位数激活时长(秒)' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'user_cohort_behavior',
      '用户Cohort行为汇总',
      'dws',
      [
        { name: 'cohort_date', comment: '注册日期(cohort)' },
        { name: 'days_since_register', comment: '注册后天数' },
      ],
      [
        { name: 'active_users', type: 'bigint', comment: '活跃用户数' },
        { name: 'avg_sessions', type: 'decimal', comment: '平均会话数' },
        { name: 'avg_events', type: 'decimal', comment: '平均事件数' },
        { name: 'avg_session_duration_sec', type: 'decimal', comment: '平均会话时长(秒)' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'push_effectiveness',
      '推送效果汇总',
      'dws',
      [
        { name: 'push_type', comment: '推送类型' },
        { name: 'audience_type', comment: '受众类型' },
      ],
      [
        { name: 'tasks_sent', type: 'bigint', comment: '发送任务数' },
        { name: 'total_recipients', type: 'bigint', comment: '总接收人数' },
        { name: 'avg_delivery_rate', type: 'decimal', comment: '平均送达率' },
        { name: 'avg_open_rate', type: 'decimal', comment: '平均打开率' },
        { name: 'avg_click_rate', type: 'decimal', comment: '平均点击率' },
        { name: 'reactivated_users', type: 'bigint', comment: '召回用户数' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'crash_stability',
      'App稳定性汇总',
      'dws',
      [
        { name: 'app_version', comment: 'App版本' },
        { name: 'platform', comment: '平台' },
      ],
      [
        { name: 'crash_count', type: 'bigint', comment: '崩溃次数' },
        { name: 'affected_users', type: 'bigint', comment: '受影响用户数' },
        { name: 'crash_rate', type: 'decimal', comment: '崩溃率' },
        { name: 'churn_after_crash_rate', type: 'decimal', comment: '崩溃后流失率' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'uninstall_analysis',
      '卸载分析汇总',
      'dws',
      [
        { name: 'register_channel', comment: '注册渠道' },
        { name: 'platform', comment: '平台' },
      ],
      [
        { name: 'uninstall_count', type: 'bigint', comment: '卸载数' },
        { name: 'avg_days_since_install', type: 'decimal', comment: '平均安装天数' },
        { name: 'avg_total_sessions', type: 'decimal', comment: '平均会话数' },
        { name: 'uninstall_rate', type: 'decimal', comment: '卸载率' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'event_frequency',
      '事件频次汇总',
      'dws',
      [
        { name: 'event_name', comment: '事件名称' },
        { name: 'event_category', comment: '事件类别' },
        { name: 'platform', comment: '平台' },
      ],
      [
        { name: 'trigger_count', type: 'bigint', comment: '触发次数' },
        { name: 'unique_users', type: 'bigint', comment: '独立用户数' },
        { name: 'avg_per_user', type: 'decimal', comment: '人均触发次数' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'deeplink_performance',
      '深链接效果汇总',
      'dws',
      [
        { name: 'source', comment: '来源' },
        { name: 'medium', comment: '媒介' },
      ],
      [
        { name: 'click_count', type: 'bigint', comment: '点击数' },
        { name: 'matched_count', type: 'bigint', comment: '匹配用户数' },
        { name: 'new_user_count', type: 'bigint', comment: '新用户数' },
        { name: 'reactivated_count', type: 'bigint', comment: '召回用户数' },
        { name: 'match_rate', type: 'decimal', comment: '匹配率' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'user_device_distribution',
      '用户设备分布汇总',
      'dws',
      [
        { name: 'device_model', comment: '设备型号' },
        { name: 'os_type', comment: '操作系统' },
        { name: 'os_version', comment: 'OS版本' },
      ],
      [
        { name: 'user_count', type: 'bigint', comment: '用户数' },
        { name: 'pct_of_total', type: 'decimal', comment: '占比' },
        { name: 'avg_session_duration_sec', type: 'decimal', comment: '平均会话时长(秒)' },
        { name: 'crash_rate', type: 'decimal', comment: '崩溃率' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'page_flow_analysis',
      '页面路径分析汇总',
      'dws',
      [
        { name: 'entry_page', comment: '入口页面' },
        { name: 'exit_page', comment: '退出页面' },
        { name: 'platform', comment: '平台' },
      ],
      [
        { name: 'session_count', type: 'bigint', comment: '会话数' },
        { name: 'avg_page_views', type: 'decimal', comment: '平均浏览页数' },
        { name: 'avg_duration_sec', type: 'decimal', comment: '平均时长(秒)' },
        { name: 'bounce_rate', type: 'decimal', comment: '跳出率' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'push_time_optimization',
      '推送时段优化汇总',
      'dws',
      [
        { name: 'hour_of_day', comment: '小时(0-23)' },
        { name: 'day_of_week', comment: '星期几(1-7)' },
        { name: 'push_type', comment: '推送类型' },
      ],
      [
        { name: 'sent_count', type: 'bigint', comment: '发送数' },
        { name: 'open_rate', type: 'decimal', comment: '打开率' },
        { name: 'click_rate', type: 'decimal', comment: '点击率' },
        { name: 'unsubscribe_rate', type: 'decimal', comment: '退订率' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'referral_chain_depth',
      '裂变链路深度分析',
      'dws',
      [
        { name: 'program_name', comment: '活动名称' },
        { name: 'chain_depth', comment: '链路层级' },
      ],
      [
        { name: 'invite_count', type: 'bigint', comment: '邀请数' },
        { name: 'register_count', type: 'bigint', comment: '注册数' },
        { name: 'activate_count', type: 'bigint', comment: '激活数' },
        { name: 'conversion_rate', type: 'decimal', comment: '转化率' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'reactivation_method_compare',
      '召回方式对比汇总',
      'dws',
      [
        { name: 'reactivation_method', comment: '召回方式' },
        { name: 'churned_days_bucket', comment: '流失天数分桶' },
      ],
      [
        { name: 'target_count', type: 'bigint', comment: '目标用户数' },
        { name: 'reactivated_count', type: 'bigint', comment: '召回用户数' },
        { name: 'reactivation_rate', type: 'decimal', comment: '召回率' },
        { name: 'retention_d7_after', type: 'decimal', comment: '召回后7日留存' },
        { name: 'cost_per_reactivation', type: 'decimal', comment: '单次召回成本' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'campaign_performance',
      '活动效果汇总',
      'dws',
      [
        { name: 'campaign_name', comment: '活动名称' },
        { name: 'campaign_type', comment: '活动类型' },
        { name: 'channel_name', comment: '渠道名称' },
      ],
      [
        { name: 'budget', type: 'decimal', comment: '预算' },
        { name: 'spent', type: 'decimal', comment: '花费' },
        { name: 'installs', type: 'bigint', comment: '安装数' },
        { name: 'registers', type: 'bigint', comment: '注册数' },
        { name: 'activations', type: 'bigint', comment: '激活数' },
        { name: 'cpa', type: 'decimal', comment: 'CPA' },
        { name: 'roi', type: 'decimal', comment: 'ROI' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'user_geo_distribution',
      '用户地域分布汇总',
      'dws',
      [
        { name: 'country', comment: '国家' },
        { name: 'city', comment: '城市' },
      ],
      [
        { name: 'total_users', type: 'bigint', comment: '总用户数' },
        { name: 'new_users', type: 'bigint', comment: '新用户数' },
        { name: 'active_users', type: 'bigint', comment: '活跃用户数' },
        { name: 'avg_retention_d7', type: 'decimal', comment: '平均7日留存' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'nps_lifecycle_correlation',
      'NPS与生命周期关联分析',
      'dws',
      [
        { name: 'lifecycle_stage', comment: '生命周期阶段' },
        { name: 'nps_category', comment: 'NPS分类' },
      ],
      [
        { name: 'user_count', type: 'bigint', comment: '用户数' },
        { name: 'avg_nps_score', type: 'decimal', comment: '平均NPS评分' },
        { name: 'churn_rate', type: 'decimal', comment: '流失率' },
        { name: 'avg_engagement_score', type: 'decimal', comment: '平均活跃得分' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'feature_adoption',
      '功能采纳率汇总',
      'dws',
      [
        { name: 'feature_name', comment: '功能名称' },
        { name: 'platform', comment: '平台' },
      ],
      [
        { name: 'total_users', type: 'bigint', comment: '可见用户数' },
        { name: 'adopted_users', type: 'bigint', comment: '使用用户数' },
        { name: 'adoption_rate', type: 'decimal', comment: '采纳率' },
        { name: 'avg_usage_count', type: 'decimal', comment: '人均使用次数' },
        { name: 'retention_lift', type: 'decimal', comment: '留存率提升' },
      ],
    ),
    generateSummaryTable(
      'dws',
      'engagement_score_trend',
      '活跃得分趋势汇总',
      'dws',
      [{ name: 'engagement_level', comment: '活跃等级' }],
      [
        { name: 'user_count', type: 'bigint', comment: '用户数' },
        { name: 'avg_score', type: 'decimal', comment: '平均得分' },
        { name: 'score_change_7d', type: 'decimal', comment: '7日得分变化' },
        { name: 'upgrade_count', type: 'bigint', comment: '等级上升用户数' },
        { name: 'downgrade_count', type: 'bigint', comment: '等级下降用户数' },
      ],
    ),

    // ============================================================
    //  ADS Layer  (~30 tables) — application / dashboard tables
    // ============================================================

    generateSummaryTable(
      'ads',
      'growth_overview',
      '增长总览看板',
      'ads',
      [{ name: 'platform', comment: '平台' }],
      [
        { name: 'dau', type: 'bigint', comment: '日活跃用户数' },
        { name: 'mau', type: 'bigint', comment: '月活跃用户数' },
        { name: 'new_registers', type: 'bigint', comment: '新注册用户数' },
        { name: 'retention_d1', type: 'decimal', comment: '次日留存率' },
        { name: 'retention_d7', type: 'decimal', comment: '7日留存率' },
        { name: 'retention_d30', type: 'decimal', comment: '30日留存率' },
        { name: 'activation_rate', type: 'decimal', comment: '激活率' },
        { name: 'churn_rate', type: 'decimal', comment: '流失率' },
        { name: 'nps_score', type: 'decimal', comment: 'NPS分数' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'dau_trend',
      'DAU趋势报表',
      'ads',
      [
        { name: 'platform', comment: '平台' },
        { name: 'country', comment: '国家' },
      ],
      [
        { name: 'dau', type: 'bigint', comment: '日活跃用户数' },
        { name: 'dau_wow_change', type: 'decimal', comment: 'DAU周同比变化' },
        { name: 'dau_mom_change', type: 'decimal', comment: 'DAU月环比变化' },
        { name: 'new_user_pct', type: 'decimal', comment: '新用户占比' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'mau_trend',
      'MAU趋势报表',
      'ads',
      [
        { name: 'month_id', comment: '月份' },
        { name: 'platform', comment: '平台' },
      ],
      [
        { name: 'mau', type: 'bigint', comment: '月活跃用户数' },
        { name: 'mau_mom_change', type: 'decimal', comment: '月环比变化' },
        { name: 'dau_mau_ratio', type: 'decimal', comment: 'DAU/MAU比值' },
        { name: 'avg_sessions_per_user', type: 'decimal', comment: '人均会话数' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'retention_report',
      '留存率报表',
      'ads',
      [
        { name: 'cohort_date', comment: '注册日期' },
        { name: 'register_channel', comment: '注册渠道' },
        { name: 'platform', comment: '平台' },
      ],
      [
        { name: 'cohort_size', type: 'bigint', comment: 'Cohort用户数' },
        { name: 'retention_d1', type: 'decimal', comment: '次日留存率' },
        { name: 'retention_d3', type: 'decimal', comment: '3日留存率' },
        { name: 'retention_d7', type: 'decimal', comment: '7日留存率' },
        { name: 'retention_d14', type: 'decimal', comment: '14日留存率' },
        { name: 'retention_d30', type: 'decimal', comment: '30日留存率' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'new_user_acquisition',
      '新用户获取报表',
      'ads',
      [
        { name: 'channel_name', comment: '渠道名称' },
        { name: 'campaign_name', comment: '活动名称' },
      ],
      [
        { name: 'new_registers', type: 'bigint', comment: '新注册数' },
        { name: 'activated_count', type: 'bigint', comment: '激活数' },
        { name: 'activation_rate', type: 'decimal', comment: '激活率' },
        { name: 'total_cost', type: 'decimal', comment: '总成本' },
        { name: 'cpa', type: 'decimal', comment: '单次获客成本' },
        { name: 'retention_d7', type: 'decimal', comment: '7日留存率' },
        { name: 'ltv_7d', type: 'decimal', comment: '7日LTV' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'activation_report',
      '激活率报表',
      'ads',
      [
        { name: 'register_channel', comment: '注册渠道' },
        { name: 'platform', comment: '平台' },
      ],
      [
        { name: 'total_registers', type: 'bigint', comment: '注册用户数' },
        { name: 'activated_users', type: 'bigint', comment: '激活用户数' },
        { name: 'activation_rate', type: 'decimal', comment: '激活率' },
        { name: 'avg_time_to_activate_min', type: 'decimal', comment: '平均激活时长(分钟)' },
        { name: 'onboarding_completion_rate', type: 'decimal', comment: '引导完成率' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'referral_report',
      '裂变报表',
      'ads',
      [{ name: 'program_name', comment: '活动名称' }],
      [
        { name: 'total_inviters', type: 'bigint', comment: '参与邀请人数' },
        { name: 'total_invites', type: 'bigint', comment: '总邀请数' },
        { name: 'registered_invitees', type: 'bigint', comment: '注册被邀请人' },
        { name: 'activated_invitees', type: 'bigint', comment: '激活被邀请人' },
        { name: 'referral_conversion_rate', type: 'decimal', comment: '裂变转化率' },
        { name: 'k_factor', type: 'decimal', comment: 'K-Factor(病毒系数)' },
        { name: 'total_reward_cost', type: 'decimal', comment: '总奖励成本' },
        { name: 'cost_per_referral', type: 'decimal', comment: '单次裂变成本' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'nps_report',
      'NPS报表',
      'ads',
      [
        { name: 'survey_name', comment: '调查名称' },
        { name: 'platform', comment: '平台' },
      ],
      [
        { name: 'total_responses', type: 'bigint', comment: '总回复数' },
        { name: 'promoter_pct', type: 'decimal', comment: '推荐者比例' },
        { name: 'passive_pct', type: 'decimal', comment: '中立者比例' },
        { name: 'detractor_pct', type: 'decimal', comment: '贬损者比例' },
        { name: 'nps_score', type: 'decimal', comment: 'NPS分数' },
        { name: 'nps_trend_mom', type: 'decimal', comment: 'NPS月环比趋势' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'ab_test_dashboard',
      'A/B实验看板',
      'ads',
      [
        { name: 'experiment_name', comment: '实验名称' },
        { name: 'experiment_key', comment: '实验标识' },
        { name: 'variant_key', comment: '分组标识' },
      ],
      [
        { name: 'sample_size', type: 'bigint', comment: '样本量' },
        { name: 'primary_metric_value', type: 'decimal', comment: '主指标值' },
        { name: 'primary_metric_lift', type: 'decimal', comment: '主指标提升' },
        { name: 'is_significant', type: 'bigint', comment: '是否显著(0/1)' },
        { name: 'p_value', type: 'decimal', comment: 'P值' },
        { name: 'confidence_level', type: 'decimal', comment: '置信度' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'push_roi_report',
      '推送ROI报表',
      'ads',
      [
        { name: 'push_type', comment: '推送类型' },
        { name: 'task_name', comment: '任务名称' },
      ],
      [
        { name: 'sent_count', type: 'bigint', comment: '发送数' },
        { name: 'delivered_count', type: 'bigint', comment: '送达数' },
        { name: 'open_rate', type: 'decimal', comment: '打开率' },
        { name: 'click_rate', type: 'decimal', comment: '点击率' },
        { name: 'reactivated_count', type: 'bigint', comment: '召回用户数' },
        { name: 'incremental_sessions', type: 'bigint', comment: '增量会话数' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'lifecycle_dashboard',
      '生命周期看板',
      'ads',
      [{ name: 'platform', comment: '平台' }],
      [
        { name: 'new_users', type: 'bigint', comment: '新用户数' },
        { name: 'active_users', type: 'bigint', comment: '活跃用户数' },
        { name: 'dormant_users', type: 'bigint', comment: '沉默用户数' },
        { name: 'churned_users', type: 'bigint', comment: '流失用户数' },
        { name: 'reactivated_users', type: 'bigint', comment: '召回用户数' },
        { name: 'new_pct', type: 'decimal', comment: '新用户占比' },
        { name: 'churn_rate', type: 'decimal', comment: '流失率' },
        { name: 'reactivation_rate', type: 'decimal', comment: '召回率' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'engagement_distribution',
      '活跃度分布报表',
      'ads',
      [
        { name: 'engagement_level', comment: '活跃等级' },
        { name: 'platform', comment: '平台' },
      ],
      [
        { name: 'user_count', type: 'bigint', comment: '用户数' },
        { name: 'pct_of_total', type: 'decimal', comment: '占比' },
        { name: 'avg_score', type: 'decimal', comment: '平均得分' },
        { name: 'avg_daily_sessions', type: 'decimal', comment: '日均会话数' },
        { name: 'avg_daily_duration_min', type: 'decimal', comment: '日均使用时长(分钟)' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'channel_comparison',
      '渠道对比报表',
      'ads',
      [
        { name: 'channel_name', comment: '渠道名称' },
        { name: 'channel_type', comment: '渠道类型' },
      ],
      [
        { name: 'new_registers', type: 'bigint', comment: '新注册数' },
        { name: 'activation_rate', type: 'decimal', comment: '激活率' },
        { name: 'retention_d7', type: 'decimal', comment: '7日留存率' },
        { name: 'cpa', type: 'decimal', comment: 'CPA' },
        { name: 'ltv_30d', type: 'decimal', comment: '30日LTV' },
        { name: 'roi', type: 'decimal', comment: '投入产出比(ROI)' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'segment_insight',
      '分群洞察报表',
      'ads',
      [{ name: 'segment_name', comment: '分群名称' }],
      [
        { name: 'user_count', type: 'bigint', comment: '用户数' },
        { name: 'avg_engagement_score', type: 'decimal', comment: '平均活跃得分' },
        { name: 'retention_d7', type: 'decimal', comment: '7日留存率' },
        { name: 'retention_d30', type: 'decimal', comment: '30日留存率' },
        { name: 'avg_nps_score', type: 'decimal', comment: '平均NPS' },
        { name: 'churn_risk_pct', type: 'decimal', comment: '流失风险比例' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'funnel_conversion',
      '漏斗转化报表',
      'ads',
      [
        { name: 'funnel_name', comment: '漏斗名称' },
        { name: 'channel', comment: '渠道' },
      ],
      [
        { name: 'step1_count', type: 'bigint', comment: '步骤1人数' },
        { name: 'step2_count', type: 'bigint', comment: '步骤2人数' },
        { name: 'step3_count', type: 'bigint', comment: '步骤3人数' },
        { name: 'step4_count', type: 'bigint', comment: '步骤4人数' },
        { name: 'overall_conversion', type: 'decimal', comment: '整体转化率' },
        { name: 'biggest_drop_step', type: 'bigint', comment: '最大流失步骤序号' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'user_quality_score',
      '用户质量评分报表',
      'ads',
      [
        { name: 'register_channel', comment: '注册渠道' },
        { name: 'platform', comment: '平台' },
      ],
      [
        { name: 'total_users', type: 'bigint', comment: '用户数' },
        { name: 'avg_quality_score', type: 'decimal', comment: '平均质量评分' },
        { name: 'high_quality_pct', type: 'decimal', comment: '高质量用户占比' },
        { name: 'avg_ltv_30d', type: 'decimal', comment: '平均30日LTV' },
        { name: 'avg_retention_d7', type: 'decimal', comment: '平均7日留存' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'weekly_growth_report',
      '周度增长报告',
      'ads',
      [{ name: 'week_start', comment: '周起始日期' }],
      [
        { name: 'wau', type: 'bigint', comment: '周活跃用户数' },
        { name: 'new_registers', type: 'bigint', comment: '新注册数' },
        { name: 'churned_users', type: 'bigint', comment: '流失用户数' },
        { name: 'reactivated_users', type: 'bigint', comment: '召回用户数' },
        { name: 'net_growth', type: 'bigint', comment: '净增长' },
        { name: 'growth_rate', type: 'decimal', comment: '增长率' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'monthly_growth_report',
      '月度增长报告',
      'ads',
      [{ name: 'month_id', comment: '月份' }],
      [
        { name: 'mau', type: 'bigint', comment: '月活跃用户数' },
        { name: 'new_registers', type: 'bigint', comment: '新注册数' },
        { name: 'churned_users', type: 'bigint', comment: '流失用户数' },
        { name: 'reactivated_users', type: 'bigint', comment: '召回用户数' },
        { name: 'net_growth', type: 'bigint', comment: '净增长' },
        { name: 'mom_growth_rate', type: 'decimal', comment: '月环比增长率' },
        { name: 'avg_nps', type: 'decimal', comment: '平均NPS' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'onboarding_effectiveness',
      '新手引导效果报表',
      'ads',
      [
        { name: 'platform', comment: '平台' },
        { name: 'register_channel', comment: '注册渠道' },
      ],
      [
        { name: 'total_new_users', type: 'bigint', comment: '新用户总数' },
        { name: 'completed_onboarding', type: 'bigint', comment: '完成引导数' },
        { name: 'completion_rate', type: 'decimal', comment: '引导完成率' },
        { name: 'activated_after_onboarding', type: 'bigint', comment: '引导后激活数' },
        { name: 'retention_d7_with_onboarding', type: 'decimal', comment: '完成引导用户7日留存' },
        {
          name: 'retention_d7_without_onboarding',
          type: 'decimal',
          comment: '未完成引导用户7日留存',
        },
      ],
    ),
    generateSummaryTable(
      'ads',
      'feedback_trend',
      '反馈趋势报表',
      'ads',
      [{ name: 'feedback_type', comment: '反馈类型' }],
      [
        { name: 'feedback_count', type: 'bigint', comment: '反馈数' },
        { name: 'avg_rating', type: 'decimal', comment: '平均评分' },
        { name: 'negative_pct', type: 'decimal', comment: '负面占比' },
        { name: 'resolution_rate', type: 'decimal', comment: '解决率' },
        { name: 'wow_change', type: 'decimal', comment: '周同比变化' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'crash_impact_report',
      '崩溃影响报表',
      'ads',
      [
        { name: 'app_version', comment: 'App版本' },
        { name: 'crash_type', comment: '崩溃类型' },
      ],
      [
        { name: 'crash_count', type: 'bigint', comment: '崩溃次数' },
        { name: 'affected_users', type: 'bigint', comment: '受影响用户' },
        { name: 'crash_rate', type: 'decimal', comment: '崩溃率' },
        { name: 'subsequent_churn_count', type: 'bigint', comment: '后续流失数' },
        { name: 'churn_rate_after_crash', type: 'decimal', comment: '崩溃后流失率' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'reactivation_report',
      '召回效果报表',
      'ads',
      [
        { name: 'reactivation_method', comment: '召回方式' },
        { name: 'platform', comment: '平台' },
      ],
      [
        { name: 'target_users', type: 'bigint', comment: '目标用户数' },
        { name: 'reactivated_users', type: 'bigint', comment: '召回用户数' },
        { name: 'reactivation_rate', type: 'decimal', comment: '召回率' },
        { name: 'retention_d7_after', type: 'decimal', comment: '召回后7日留存' },
        { name: 'avg_sessions_after', type: 'decimal', comment: '召回后平均会话数' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'arpu_report',
      'ARPU报表',
      'ads',
      [
        { name: 'platform', comment: '平台' },
        { name: 'lifecycle_stage', comment: '生命周期阶段' },
      ],
      [
        { name: 'total_users', type: 'bigint', comment: '用户数' },
        { name: 'total_revenue', type: 'decimal', comment: '总收入' },
        { name: 'arpu', type: 'decimal', comment: 'ARPU(每用户平均收入)' },
        { name: 'arppu', type: 'decimal', comment: 'ARPPU(每付费用户平均收入)' },
        { name: 'paying_user_rate', type: 'decimal', comment: '付费用户率' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'realtime_growth_monitor',
      '实时增长监控',
      'ads',
      [
        { name: 'hour_id', comment: '小时(HH)' },
        { name: 'platform', comment: '平台' },
      ],
      [
        { name: 'hourly_active_users', type: 'bigint', comment: '小时活跃用户数' },
        { name: 'hourly_registers', type: 'bigint', comment: '小时注册数' },
        { name: 'hourly_sessions', type: 'bigint', comment: '小时会话数' },
        { name: 'cumulative_dau', type: 'bigint', comment: '累计DAU' },
        { name: 'hour_over_hour_change', type: 'decimal', comment: '环比变化' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'growth_experiment_summary',
      '增长实验汇总报表',
      'ads',
      [
        { name: 'experiment_name', comment: '实验名称' },
        { name: 'experiment_status', comment: '实验状态' },
      ],
      [
        { name: 'total_experiments', type: 'bigint', comment: '实验数' },
        { name: 'significant_wins', type: 'bigint', comment: '显著胜出数' },
        { name: 'win_rate', type: 'decimal', comment: '胜出率' },
        { name: 'avg_lift', type: 'decimal', comment: '平均提升' },
        { name: 'cumulative_impact_users', type: 'bigint', comment: '累计影响用户数' },
      ],
    ),
    generateSummaryTable(
      'ads',
      'user_health_scorecard',
      '用户健康度评分卡',
      'ads',
      [{ name: 'platform', comment: '平台' }],
      [
        { name: 'total_users', type: 'bigint', comment: '总用户数' },
        { name: 'healthy_pct', type: 'decimal', comment: '健康用户占比' },
        { name: 'at_risk_pct', type: 'decimal', comment: '风险用户占比' },
        { name: 'critical_pct', type: 'decimal', comment: '高危用户占比' },
        { name: 'avg_health_score', type: 'decimal', comment: '平均健康评分' },
        { name: 'health_score_trend', type: 'decimal', comment: '健康评分趋势' },
      ],
    ),
    generateSummaryTable(
      'ads', 'geo_growth_report', '地域增长报表', 'ads',
      [
        { name: 'country', comment: '国家' },
        { name: 'city', comment: '城市' },
      ],
      [
        { name: 'total_users', type: 'bigint', comment: '总用户数' },
        { name: 'new_registers', type: 'bigint', comment: '新注册数' },
        { name: 'dau', type: 'bigint', comment: 'DAU' },
        { name: 'retention_d7', type: 'decimal', comment: '7日留存率' },
        { name: 'growth_rate', type: 'decimal', comment: '增长率' },
      ],
    ),
    generateSummaryTable(
      'ads', 'feature_impact_report', '功能影响力报表', 'ads',
      [
        { name: 'feature_name', comment: '功能名称' },
      ],
      [
        { name: 'adoption_rate', type: 'decimal', comment: '采纳率' },
        { name: 'retention_lift', type: 'decimal', comment: '留存提升' },
        { name: 'engagement_lift', type: 'decimal', comment: '活跃度提升' },
        { name: 'corr_with_retention', type: 'decimal', comment: '与留存相关性' },
      ],
    ),
    generateSummaryTable(
      'ads', 'device_performance_report', '设备性能报表', 'ads',
      [
        { name: 'device_model', comment: '设备型号' },
        { name: 'os_version', comment: 'OS版本' },
      ],
      [
        { name: 'user_count', type: 'bigint', comment: '用户数' },
        { name: 'avg_session_duration_sec', type: 'decimal', comment: '平均会话时长' },
        { name: 'crash_rate', type: 'decimal', comment: '崩溃率' },
        { name: 'retention_d7', type: 'decimal', comment: '7日留存率' },
        { name: 'uninstall_rate', type: 'decimal', comment: '卸载率' },
      ],
    ),
    generateSummaryTable(
      'ads', 'push_time_recommendation', '推送最佳时段推荐', 'ads',
      [
        { name: 'segment_name', comment: '分群名称' },
        { name: 'best_hour', comment: '最佳发送小时' },
        { name: 'best_day_of_week', comment: '最佳发送星期' },
      ],
      [
        { name: 'predicted_open_rate', type: 'decimal', comment: '预测打开率' },
        { name: 'historical_open_rate', type: 'decimal', comment: '历史打开率' },
        { name: 'sample_size', type: 'bigint', comment: '样本量' },
      ],
    ),
  ],

  /* ----------------------------------------------------------------
   * METRICS (8)
   * ---------------------------------------------------------------- */
  metrics: [
    {
      name: 'dau',
      displayName: '日活跃用户数(DAU)',
      expression: 'COUNT(DISTINCT user_id)',
      metricType: 'atomic',
      sourceTable: 'dws_daily_user_active',
      dimensions: ['platform', 'country'],
      granularity: ['day'],
      format: 'number',
      description: '当日至少有一次活跃行为的去重用户数',
    },
    {
      name: 'mau',
      displayName: '月活跃用户数(MAU)',
      expression: 'COUNT(DISTINCT user_id)',
      metricType: 'atomic',
      sourceTable: 'dws_monthly_user_active',
      dimensions: ['platform', 'country', 'month_id'],
      granularity: ['month'],
      format: 'number',
      description: '当月至少有一次活跃行为的去重用户数',
    },
    {
      name: 'retention_d1',
      displayName: '次日留存率',
      expression: 'retained_d1 * 1.0 / NULLIF(cohort_size, 0)',
      metricType: 'derived',
      sourceTable: 'dws_retention_cohort',
      dimensions: ['cohort_date', 'platform', 'register_channel'],
      granularity: ['day'],
      format: 'percentage',
      description: '注册次日仍有活跃行为的用户占新注册用户的比例',
    },
    {
      name: 'retention_d7',
      displayName: '7日留存率',
      expression: 'retained_d7 * 1.0 / NULLIF(cohort_size, 0)',
      metricType: 'derived',
      sourceTable: 'dws_retention_cohort',
      dimensions: ['cohort_date', 'platform', 'register_channel'],
      granularity: ['day'],
      format: 'percentage',
      description: '注册第7日仍有活跃行为的用户占新注册用户的比例',
    },
    {
      name: 'retention_d30',
      displayName: '30日留存率',
      expression: 'retained_d30 * 1.0 / NULLIF(cohort_size, 0)',
      metricType: 'derived',
      sourceTable: 'dws_retention_cohort',
      dimensions: ['cohort_date', 'platform', 'register_channel'],
      granularity: ['day'],
      format: 'percentage',
      description: '注册第30日仍有活跃行为的用户占新注册用户的比例',
    },
    {
      name: 'new_user_registration',
      displayName: '新用户注册数',
      expression: 'COUNT(DISTINCT user_id)',
      metricType: 'atomic',
      sourceTable: 'dwd_user_register_detail',
      dimensions: ['register_channel', 'device_type', 'country'],
      granularity: ['day', 'week', 'month'],
      format: 'number',
      description: '新完成注册的去重用户数',
    },
    {
      name: 'activation_rate',
      displayName: '激活率',
      expression: 'activated_users * 1.0 / NULLIF(total_registers, 0)',
      metricType: 'derived',
      sourceTable: 'dws_activation_analysis',
      dimensions: ['register_channel', 'device_type', 'platform'],
      granularity: ['day', 'week'],
      format: 'percentage',
      description: '注册后完成关键激活事件的用户占新注册用户的比例',
    },
    {
      name: 'referral_conversion_rate',
      displayName: '裂变转化率',
      expression: 'registered_invitees * 1.0 / NULLIF(total_invites, 0)',
      metricType: 'derived',
      sourceTable: 'dws_referral_program_summary',
      dimensions: ['program_name', 'invite_channel'],
      granularity: ['day', 'week'],
      format: 'percentage',
      description: '收到邀请后完成注册的被邀请人占总邀请数的比例',
    },
  ],

  /* ----------------------------------------------------------------
   * GLOSSARY (8)
   * ---------------------------------------------------------------- */
  glossary: [
    {
      term: '日活(DAU)',
      sqlExpression: 'COUNT(DISTINCT user_id) WHERE ds = <target_date>',
      description:
        'Daily Active Users — 当日至少产生一次有效会话或触发核心事件的去重用户数。' +
        '不含纯后台推送唤醒。',
    },
    {
      term: '月活(MAU)',
      sqlExpression:
        "COUNT(DISTINCT user_id) WHERE ds BETWEEN date_trunc('month', <target_date>) AND <target_date>",
      description:
        'Monthly Active Users — 当月至少有一天为活跃状态的去重用户数。' +
        '自然月口径，跨月不重复计数。',
    },
    {
      term: '留存率',
      sqlExpression:
        'COUNT(DISTINCT CASE WHEN active_on_day_n THEN user_id END) / NULLIF(cohort_size, 0)',
      description:
        '某一注册Cohort在第N日仍活跃的用户占该Cohort总人数的比例。' +
        '常见口径：D1(次日)、D7、D14、D30。',
    },
    {
      term: '激活率',
      sqlExpression:
        'COUNT(DISTINCT CASE WHEN has_activation_event THEN user_id END) / NULLIF(total_registers, 0)',
      description:
        '新注册用户在指定时间窗口内完成关键激活事件(如完成新手引导、首次核心操作)的比例。' +
        '激活事件由产品定义，通常为Aha Moment。',
    },
    {
      term: '拉新',
      sqlExpression: 'COUNT(DISTINCT user_id) WHERE is_new_register = true',
      description:
        '通过各渠道获取的新注册用户。包含自然流量(organic)和付费渠道(paid)。' +
        '拉新成本 = 渠道总投入 / 新注册用户数。',
    },
    {
      term: '裂变率',
      sqlExpression: 'SUM(registered_invitees) / NULLIF(SUM(total_inviters), 0)',
      description:
        '参与邀请的用户平均带来的新注册用户数(K-Factor)。裂变率 > 1 表示用户自增长。' +
        '病毒系数 K = 平均邀请数 x 邀请转化率。',
    },
    {
      term: '用户生命周期',
      sqlExpression:
        "CASE lifecycle_stage WHEN 'new' THEN '新用户' WHEN 'active' THEN '活跃' WHEN 'dormant' THEN '沉默' WHEN 'churned' THEN '流失' WHEN 'reactivated' THEN '召回' END",
      description:
        '用户从注册到流失/召回的完整阶段划分。通常为：新用户 → 活跃 → 沉默 → 流失，' +
        '以及流失后被召回。各阶段判定规则由生命周期规则表配置。',
    },
    {
      term: 'ARPU',
      sqlExpression: 'SUM(revenue) / NULLIF(COUNT(DISTINCT user_id), 0)',
      description:
        'Average Revenue Per User — 每用户平均收入。常按月计算。' +
        'ARPPU 为每付费用户平均收入(仅计付费用户分母)。',
    },
  ],

  /* ----------------------------------------------------------------
   * KNOWLEDGE DOCS (1)
   * ---------------------------------------------------------------- */
  knowledgeDocs: [
    {
      title: '用户增长指标体系与分析方法论',
      docType: 'document',
      content: `# 用户增长指标体系

## 北极星指标
- DAU/MAU 比值(粘性指标)：衡量用户使用频次，健康区间 0.2~0.5
- 新用户激活率：衡量产品 Aha Moment 触达效率

## AARRR 漏斗
1. **Acquisition(获客)**：渠道投放 → 安装 → 注册，核心指标 CPA/CPI
2. **Activation(激活)**：新手引导完成率 → 关键动作触发，核心指标激活率
3. **Retention(留存)**：D1/D7/D30 留存率 Cohort 分析，区分渠道质量
4. **Referral(裂变)**：K-Factor、邀请转化率，病毒系数 > 1 为自增长
5. **Revenue(变现)**：ARPU/ARPPU、LTV、付费转化率

## 留存分析方法
- **Cohort Analysis**：按注册日期分组，追踪后续留存曲线
- **Rolling Retention**：N日内任意一天活跃即算留存(宽口径)
- **Bracket Retention**：第N日当天活跃(严口径)
- 留存曲线拐点(通常 D7~D14)是产品体验优化的关键窗口

## A/B 实验规范
- 最小样本量：基于 MDE(最小可检测效应)和统计功效(Power ≥ 0.8)计算
- 实验周期：至少覆盖一个完整业务周期(通常 7~14 天)
- 多重比较校正：多指标同时检验时使用 Bonferroni 或 FDR 校正
- SRM 检查：实验前检查样本比例不匹配(Sample Ratio Mismatch)

## 生命周期管理
- 新用户(D0~D7)：引导优化 + 激活干预
- 成长期(D7~D30)：习惯养成 + 推送策略
- 成熟期(D30+)：价值深挖 + 裂变驱动
- 沉默期(连续7天未活跃)：召回推送 + 优惠触达
- 流失(连续30天未活跃)：重定向广告 + 深链接召回`,
    },
  ],

  /* ----------------------------------------------------------------
   * CONVERSATIONS (2)
   * ---------------------------------------------------------------- */
  conversations: [
    {
      title: '查询各渠道新用户次日留存率',
      messages: [
        {
          role: 'user',
          content: '帮我看看上周各注册渠道的新用户次日留存率是多少',
        },
        {
          role: 'assistant',
          content: '以下是上周各注册渠道的新用户次日留存率查询：',
          sql: `SELECT
  register_channel,
  SUM(cohort_size) AS total_new_users,
  SUM(retained_d1) AS retained_users,
  ROUND(SUM(retained_d1) * 1.0 / NULLIF(SUM(cohort_size), 0), 4) AS retention_d1_rate
FROM dws_retention_cohort
WHERE ds BETWEEN CURRENT_DATE - INTERVAL '8 days' AND CURRENT_DATE - INTERVAL '1 day'
GROUP BY register_channel
ORDER BY retention_d1_rate DESC;`,
          confidence: 0.95,
        },
      ],
    },
    {
      title: 'A/B实验结果对比分析',
      messages: [
        {
          role: 'user',
          content: '注册流程优化实验跑完了，帮我看看各分组的注册转化率和次日留存有没有显著差异',
        },
        {
          role: 'assistant',
          content: '查询注册流程优化实验的各分组转化率及统计显著性：',
          sql: `SELECT
  a.variant_key,
  a.sample_size,
  a.conversion_rate AS register_conversion_rate,
  a.p_value AS conversion_p_value,
  b.metric_mean AS retention_d1,
  b.p_value AS retention_p_value,
  CASE WHEN a.p_value < 0.05 THEN 'Significant' ELSE 'Not Significant' END AS conversion_significance,
  CASE WHEN b.p_value < 0.05 THEN 'Significant' ELSE 'Not Significant' END AS retention_significance
FROM dws_ab_experiment_result a
JOIN dws_ab_experiment_result b
  ON a.experiment_key = b.experiment_key
  AND a.variant_key = b.variant_key
  AND a.ds = b.ds
WHERE a.experiment_key = 'register_flow_optimization'
  AND a.metric_name = 'register_conversion'
  AND b.metric_name = 'retention_d1'
  AND a.ds = (SELECT MAX(ds) FROM dws_ab_experiment_result WHERE experiment_key = 'register_flow_optimization')
ORDER BY a.variant_key;`,
          confidence: 0.88,
        },
      ],
    },
  ],

  /* ----------------------------------------------------------------
   * QUERY HISTORY (4)
   * ---------------------------------------------------------------- */
  queryHistory: [
    {
      naturalLanguage: '最近30天每天的DAU和新注册用户数',
      generatedSql: `SELECT
  ds,
  dau,
  new_users
FROM dws_daily_user_active
WHERE ds >= CURRENT_DATE - INTERVAL '30 days'
  AND platform = 'all'
  AND country = 'all'
ORDER BY ds;`,
      status: 'accepted',
      isGolden: true,
      tablesUsed: ['dws_daily_user_active'],
    },
    {
      naturalLanguage: '各渠道获客成本和激活率对比',
      generatedSql: `SELECT
  c.channel_name,
  a.source,
  a.medium,
  SUM(a.total_cost) AS total_cost,
  SUM(a.registers) AS total_registers,
  ROUND(SUM(a.total_cost) / NULLIF(SUM(a.registers), 0), 2) AS cpa,
  act.activation_rate
FROM dws_attribution_channel a
JOIN ods_channel_config c ON a.source = c.channel_code
LEFT JOIN dws_activation_analysis act ON act.register_channel = c.channel_code AND act.ds = a.ds
WHERE a.ds >= CURRENT_DATE - INTERVAL '7 days'
GROUP BY c.channel_name, a.source, a.medium, act.activation_rate
ORDER BY cpa ASC;`,
      status: 'accepted',
      isGolden: false,
      tablesUsed: ['dws_attribution_channel', 'ods_channel_config', 'dws_activation_analysis'],
    },
    {
      naturalLanguage: '上月裂变活动的K-Factor和转化率',
      generatedSql: `SELECT
  program_name,
  SUM(total_invites) AS total_invites,
  SUM(registered_invitees) AS registered_invitees,
  ROUND(SUM(registered_invitees) * 1.0 / NULLIF(SUM(total_invites), 0), 4) AS conversion_rate,
  ROUND(SUM(registered_invitees) * 1.0 / NULLIF(SUM(total_invites / NULLIF(avg_invites_per_user, 0)), 0), 4) AS k_factor,
  SUM(total_reward_amount) AS total_reward_cost
FROM dws_referral_program_summary
WHERE ds >= date_trunc('month', CURRENT_DATE - INTERVAL '1 month')
  AND ds < date_trunc('month', CURRENT_DATE)
GROUP BY program_name
ORDER BY k_factor DESC;`,
      status: 'accepted',
      isGolden: true,
      tablesUsed: ['dws_referral_program_summary'],
    },
    {
      naturalLanguage: '新手引导完成率和对留存的影响',
      generatedSql: `SELECT
  platform,
  total_new_users,
  completed_onboarding,
  completion_rate,
  retention_d7_with_onboarding,
  retention_d7_without_onboarding,
  ROUND(retention_d7_with_onboarding - retention_d7_without_onboarding, 4) AS retention_d7_lift
FROM ads_onboarding_effectiveness
WHERE ds = (SELECT MAX(ds) FROM ads_onboarding_effectiveness)
ORDER BY retention_d7_lift DESC;`,
      status: 'pending',
      isGolden: false,
      tablesUsed: ['ads_onboarding_effectiveness'],
    },
  ],
};
