import type { EngineSeedDefinition, TableDef, MetricDef, GlossaryDef } from './types.js';

/* ================================================================
 * Apache Doris 实时 OLAP 引擎 — Seed Data
 *
 * Distribution: ADS(25) + DWS(20) + DWD(10) + DIM(5) = 60 tables
 * Domains:      trade / user / product / risk
 * Metrics:      30 (enterprise OLAP — highest metric density)
 * Glossary:     10 entries (OLAP-specific terms)
 * ================================================================ */

/* ─────────── helper: column shorthand ─────────── */

interface Col {
  name: string;
  dataType: string;
  comment: string;
  isPrimaryKey?: boolean;
  isNullable?: boolean;
  isPii?: boolean;
  sampleValues?: string[];
  referencesTable?: string;
  referencesColumn?: string;
}

const c = {
  pk: (name: string, comment: string): Col => ({
    name,
    dataType: 'BIGINT',
    comment,
    isPrimaryKey: true,
  }),
  ds: (): Col => ({
    name: 'ds',
    dataType: 'DATE',
    comment: '数据分区日期',
    isNullable: false,
  }),
  bigint: (name: string, comment: string): Col => ({
    name,
    dataType: 'BIGINT',
    comment,
  }),
  int: (name: string, comment: string): Col => ({
    name,
    dataType: 'INT',
    comment,
  }),
  varchar: (name: string, len: number, comment: string): Col => ({
    name,
    dataType: `VARCHAR(${len})`,
    comment,
  }),
  decimal: (name: string, comment: string): Col => ({
    name,
    dataType: 'DECIMAL(18,2)',
    comment,
  }),
  double: (name: string, comment: string): Col => ({
    name,
    dataType: 'DOUBLE',
    comment,
  }),
  datetime: (name: string, comment: string): Col => ({
    name,
    dataType: 'DATETIME',
    comment,
  }),
  date: (name: string, comment: string): Col => ({
    name,
    dataType: 'DATE',
    comment,
  }),
  bool: (name: string, comment: string): Col => ({
    name,
    dataType: 'BOOLEAN',
    comment,
  }),
};

/* ==============================================================
 *  ADS Layer — 25 tables (pre-computed metric / dashboard tables)
 * ============================================================== */

const adsTables: TableDef[] = [
  /* ── trade domain (8) ── */
  {
    name: 'ads_trade_gmv_dashboard',
    comment: 'GMV 看板指标（按日/渠道/品类聚合）',
    layer: 'ads',
    domain: 'trade',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('channel', 50, '渠道: app/web/h5/mini_program'),
      c.varchar('category_name', 100, '商品一级品类名'),
      c.decimal('gmv_amount', 'GMV 成交金额'),
      c.bigint('order_count', '订单数'),
      c.decimal('avg_order_value', '客单价'),
      c.decimal('refund_amount', '退款金额'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'ads_trade_conversion_funnel',
    comment: '交易转化漏斗（浏览→加购→下单→支付）',
    layer: 'ads',
    domain: 'trade',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('platform', 30, '平台: ios/android/web'),
      c.varchar('step_name', 50, '漏斗步骤名'),
      c.bigint('user_count', '该步骤用户数'),
      c.double('conversion_rate', '转化率(0-1)'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'ads_trade_seller_ranking',
    comment: '商家销售排行榜（按日聚合）',
    layer: 'ads',
    domain: 'trade',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('seller_id', '商家ID'),
      c.varchar('seller_name', 100, '商家名称'),
      c.decimal('gmv_amount', '商家GMV'),
      c.bigint('order_count', '商家订单数'),
      c.int('rank', '排名'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'ads_trade_refund_analysis',
    comment: '退款分析指标（按日/退款原因聚合）',
    layer: 'ads',
    domain: 'trade',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('refund_reason', 100, '退款原因'),
      c.varchar('category_name', 100, '品类名'),
      c.bigint('refund_count', '退款订单数'),
      c.decimal('refund_amount', '退款金额'),
      c.double('refund_rate', '退款率'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'ads_trade_hourly_trend',
    comment: '交易分时趋势（按小时粒度）',
    layer: 'ads',
    domain: 'trade',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.int('hour', '小时(0-23)'),
      c.varchar('channel', 50, '渠道'),
      c.decimal('gmv_amount', '该时段GMV'),
      c.bigint('order_count', '该时段订单数'),
      c.bigint('pay_user_count', '该时段支付人数'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'ads_trade_payment_analysis',
    comment: '支付方式分析（按日/支付渠道聚合）',
    layer: 'ads',
    domain: 'trade',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('payment_method', 50, '支付方式: alipay/wechat/card/balance'),
      c.bigint('pay_count', '支付笔数'),
      c.decimal('pay_amount', '支付金额'),
      c.double('pay_success_rate', '支付成功率'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'ads_trade_region_summary',
    comment: '区域交易汇总（按日/省份聚合）',
    layer: 'ads',
    domain: 'trade',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('province', 50, '省份'),
      c.varchar('city', 50, '城市'),
      c.decimal('gmv_amount', '区域GMV'),
      c.bigint('order_count', '区域订单数'),
      c.bigint('buyer_count', '购买人数'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'ads_trade_coupon_effect',
    comment: '优惠券核销效果分析',
    layer: 'ads',
    domain: 'trade',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('coupon_type', 50, '优惠券类型: full_reduction/discount/cashback'),
      c.bigint('issued_count', '发放张数'),
      c.bigint('used_count', '核销张数'),
      c.double('use_rate', '核销率'),
      c.decimal('discount_amount', '优惠减免金额'),
      c.decimal('driven_gmv', '带动GMV'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },

  /* ── user domain (7) ── */
  {
    name: 'ads_user_active_dashboard',
    comment: '用户活跃看板（DAU/WAU/MAU + 新增）',
    layer: 'ads',
    domain: 'user',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('platform', 30, '平台: ios/android/web'),
      c.varchar('region', 50, '地区'),
      c.bigint('dau', '日活跃用户数'),
      c.bigint('wau', '周活跃用户数'),
      c.bigint('mau', '月活跃用户数'),
      c.bigint('new_users', '当日新增用户'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'ads_user_retention_report',
    comment: '用户留存报表（按注册队列日期计算）',
    layer: 'ads',
    domain: 'user',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.date('cohort_date', '注册队列日期'),
      c.double('retention_1d', '次日留存率'),
      c.double('retention_7d', '7日留存率'),
      c.double('retention_30d', '30日留存率'),
      c.bigint('cohort_size', '队列用户数'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'ads_user_ltv_analysis',
    comment: '用户 LTV 分析（按用户层级聚合）',
    layer: 'ads',
    domain: 'user',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('user_tier', 30, '用户层级: new/active/loyal/vip'),
      c.decimal('avg_ltv', '平均 LTV'),
      c.decimal('total_revenue', '总收入'),
      c.bigint('user_count', '用户数'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'ads_user_churn_warning',
    comment: '用户流失预警（按日/风险等级聚合）',
    layer: 'ads',
    domain: 'user',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('risk_level', 20, '流失风险: high/medium/low'),
      c.bigint('user_count', '用户数'),
      c.double('avg_inactive_days', '平均未活跃天数'),
      c.decimal('potential_lost_revenue', '潜在流失收入'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'ads_user_channel_acquisition',
    comment: '渠道获客效果分析',
    layer: 'ads',
    domain: 'user',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('channel', 50, '获客渠道: organic/sem/social/referral'),
      c.bigint('new_user_count', '新增用户数'),
      c.decimal('acquisition_cost', '获客成本'),
      c.double('retention_7d', '7日留存率'),
      c.decimal('arpu_7d', '7日ARPU'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'ads_user_segment_profile',
    comment: '用户分群画像（按群体聚合特征）',
    layer: 'ads',
    domain: 'user',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('segment_name', 50, '分群名称'),
      c.bigint('user_count', '群体用户数'),
      c.decimal('avg_order_value', '群体平均客单价'),
      c.double('avg_purchase_frequency', '平均购买频次(月)'),
      c.varchar('top_category', 100, '偏好品类TOP1'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'ads_user_behavior_funnel',
    comment: '用户行为漏斗（注册→激活→首购→复购）',
    layer: 'ads',
    domain: 'user',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('step_name', 50, '漏斗步骤'),
      c.varchar('platform', 30, '平台'),
      c.bigint('user_count', '步骤用户数'),
      c.double('step_conversion_rate', '步骤转化率'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },

  /* ── product domain (6) ── */
  {
    name: 'ads_product_hot_ranking',
    comment: '热销商品排行（按日/品类聚合）',
    layer: 'ads',
    domain: 'product',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('product_id', '商品ID'),
      c.varchar('product_name', 200, '商品名称'),
      c.varchar('category_name', 100, '品类名'),
      c.decimal('sale_amount', '销售金额'),
      c.bigint('sale_count', '销售件数'),
      c.int('rank', '排名'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'ads_product_category_analysis',
    comment: '品类分析（按日/品类聚合）',
    layer: 'ads',
    domain: 'product',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('category_id', '品类ID'),
      c.varchar('category_name', 100, '品类名称'),
      c.decimal('gmv_amount', '品类GMV'),
      c.bigint('order_count', '品类订单数'),
      c.decimal('avg_price', '品类均价'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'ads_product_inventory_alert',
    comment: '商品库存预警（低库存/滞销）',
    layer: 'ads',
    domain: 'product',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('product_id', '商品ID'),
      c.varchar('product_name', 200, '商品名称'),
      c.bigint('current_stock', '当前库存'),
      c.bigint('avg_daily_sales', '日均销量'),
      c.int('days_of_supply', '可售天数'),
      c.varchar('alert_level', 20, '预警等级: critical/warning/normal'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'ads_product_review_summary',
    comment: '商品评价汇总（按品类/评分维度）',
    layer: 'ads',
    domain: 'product',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('category_name', 100, '品类名'),
      c.bigint('review_count', '评价总数'),
      c.double('avg_rating', '平均评分(1-5)'),
      c.double('positive_rate', '好评率'),
      c.bigint('with_image_count', '带图评价数'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'ads_product_price_monitor',
    comment: '商品价格监控（价格变动趋势）',
    layer: 'ads',
    domain: 'product',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('product_id', '商品ID'),
      c.varchar('product_name', 200, '商品名称'),
      c.decimal('current_price', '当前价格'),
      c.decimal('avg_price_7d', '近7日均价'),
      c.double('price_change_rate', '价格变动率'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'ads_product_return_analysis',
    comment: '商品退货分析（按品类/退货原因）',
    layer: 'ads',
    domain: 'product',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('category_name', 100, '品类名'),
      c.varchar('return_reason', 100, '退货原因'),
      c.bigint('return_count', '退货件数'),
      c.double('return_rate', '退货率'),
      c.decimal('return_amount', '退货金额'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },

  /* ── risk domain (4) ── */
  {
    name: 'ads_risk_fraud_monitor',
    comment: '欺诈监控指标（按日/风险类型聚合）',
    layer: 'ads',
    domain: 'risk',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('risk_type', 50, '风险类型: account_takeover/payment_fraud/promo_abuse'),
      c.bigint('alert_count', '告警次数'),
      c.bigint('confirmed_count', '确认欺诈数'),
      c.double('false_positive_rate', '误报率'),
      c.decimal('blocked_amount', '拦截金额'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'ads_risk_compliance_dashboard',
    comment: '合规看板（按检查类型聚合）',
    layer: 'ads',
    domain: 'risk',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('check_type', 50, '检查类型: kyc/aml/content_audit'),
      c.bigint('total_checks', '检查总数'),
      c.bigint('pass_count', '通过数'),
      c.bigint('fail_count', '未通过数'),
      c.double('pass_rate', '通过率'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'ads_risk_realtime_alert',
    comment: '实时风控告警汇总（按规则/等级聚合）',
    layer: 'ads',
    domain: 'risk',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('rule_name', 100, '规则名称'),
      c.varchar('severity', 20, '严重等级: critical/high/medium/low'),
      c.bigint('trigger_count', '触发次数'),
      c.bigint('block_count', '拦截次数'),
      c.double('block_rate', '拦截率'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'ads_risk_transaction_score',
    comment: '交易风险评分分布（按日/分数段聚合）',
    layer: 'ads',
    domain: 'risk',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('score_range', 30, '分数段: 0-20/20-40/40-60/60-80/80-100'),
      c.bigint('transaction_count', '交易笔数'),
      c.decimal('transaction_amount', '交易金额'),
      c.bigint('blocked_count', '拦截笔数'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
];

/* ==============================================================
 *  DWS Layer — 20 tables (real-time summary / aggregation)
 * ============================================================== */

const dwsTables: TableDef[] = [
  /* ── trade domain (6) ── */
  {
    name: 'dws_trade_order_1d',
    comment: '交易订单日汇总（按用户+渠道粒度）',
    layer: 'dws',
    domain: 'trade',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('user_id', '用户ID'),
      c.varchar('channel', 50, '渠道'),
      c.bigint('order_count', '订单数'),
      c.decimal('order_amount', '订单金额'),
      c.decimal('pay_amount', '实付金额'),
      c.bigint('product_count', '购买商品种数'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dws_trade_seller_1d',
    comment: '商家交易日汇总（按商家粒度）',
    layer: 'dws',
    domain: 'trade',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('seller_id', '商家ID'),
      c.bigint('order_count', '订单数'),
      c.decimal('gmv_amount', 'GMV'),
      c.bigint('buyer_count', '购买人数'),
      c.decimal('avg_order_value', '客单价'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dws_trade_refund_1d',
    comment: '退款日汇总（按原因+品类粒度）',
    layer: 'dws',
    domain: 'trade',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('refund_reason', 100, '退款原因'),
      c.varchar('category_name', 100, '品类名'),
      c.bigint('refund_count', '退款笔数'),
      c.decimal('refund_amount', '退款金额'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dws_trade_payment_1d',
    comment: '支付方式日汇总',
    layer: 'dws',
    domain: 'trade',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('payment_method', 50, '支付方式'),
      c.bigint('pay_count', '支付笔数'),
      c.decimal('pay_amount', '支付金额'),
      c.bigint('pay_user_count', '支付人数'),
      c.double('success_rate', '支付成功率'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dws_trade_coupon_1d',
    comment: '优惠券使用日汇总',
    layer: 'dws',
    domain: 'trade',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('coupon_type', 50, '优惠券类型'),
      c.bigint('used_count', '使用张数'),
      c.decimal('discount_amount', '优惠金额'),
      c.decimal('driven_gmv', '带动GMV'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dws_trade_region_1d',
    comment: '区域交易日汇总',
    layer: 'dws',
    domain: 'trade',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('province', 50, '省份'),
      c.varchar('city', 50, '城市'),
      c.decimal('gmv_amount', 'GMV'),
      c.bigint('order_count', '订单数'),
      c.bigint('buyer_count', '购买人数'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },

  /* ── user domain (5) ── */
  {
    name: 'dws_user_active_1d',
    comment: '用户活跃日汇总（按平台+地区粒度）',
    layer: 'dws',
    domain: 'user',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('platform', 30, '平台'),
      c.varchar('region', 50, '地区'),
      c.bigint('active_user_count', '活跃用户数'),
      c.bigint('new_user_count', '新增用户数'),
      c.bigint('login_count', '登录次数'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dws_user_retention_1d',
    comment: '用户留存日计算表（按注册队列粒度）',
    layer: 'dws',
    domain: 'user',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.date('cohort_date', '注册日期'),
      c.bigint('cohort_size', '队列人数'),
      c.bigint('retained_count', '留存人数'),
      c.int('days_since_register', '注册后天数'),
      c.double('retention_rate', '留存率'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dws_user_purchase_1d',
    comment: '用户购买行为日汇总',
    layer: 'dws',
    domain: 'user',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('user_id', '用户ID'),
      c.bigint('order_count', '下单数'),
      c.decimal('pay_amount', '支付金额'),
      c.bigint('product_count', '购买商品数'),
      c.varchar('top_category', 100, '偏好品类'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dws_user_session_1d',
    comment: '用户会话行为日汇总',
    layer: 'dws',
    domain: 'user',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('platform', 30, '平台'),
      c.bigint('session_count', '会话数'),
      c.double('avg_session_duration', '平均会话时长(秒)'),
      c.double('avg_page_views', '平均浏览页数'),
      c.double('bounce_rate', '跳出率'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dws_user_channel_1d',
    comment: '用户渠道来源日汇总',
    layer: 'dws',
    domain: 'user',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('channel', 50, '渠道来源'),
      c.bigint('new_user_count', '新增用户数'),
      c.decimal('acquisition_cost', '获客成本'),
      c.bigint('active_count', '活跃数'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },

  /* ── product domain (5) ── */
  {
    name: 'dws_product_sale_1d',
    comment: '商品销售日汇总',
    layer: 'dws',
    domain: 'product',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('product_id', '商品ID'),
      c.bigint('sale_count', '销售件数'),
      c.decimal('sale_amount', '销售金额'),
      c.bigint('buyer_count', '购买人数'),
      c.decimal('avg_price', '均价'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dws_product_category_1d',
    comment: '品类销售日汇总',
    layer: 'dws',
    domain: 'product',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('category_id', '品类ID'),
      c.varchar('category_name', 100, '品类名'),
      c.decimal('gmv_amount', '品类GMV'),
      c.bigint('order_count', '品类订单数'),
      c.bigint('product_count', '在售商品数'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dws_product_inventory_1d',
    comment: '库存快照日汇总',
    layer: 'dws',
    domain: 'product',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('product_id', '商品ID'),
      c.bigint('total_stock', '总库存'),
      c.bigint('available_stock', '可售库存'),
      c.bigint('locked_stock', '锁定库存'),
      c.bigint('daily_outbound', '日出库量'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dws_product_review_1d',
    comment: '商品评价日汇总',
    layer: 'dws',
    domain: 'product',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('product_id', '商品ID'),
      c.bigint('review_count', '评价数'),
      c.double('avg_rating', '平均评分'),
      c.bigint('positive_count', '好评数'),
      c.bigint('negative_count', '差评数'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dws_product_return_1d',
    comment: '商品退货日汇总',
    layer: 'dws',
    domain: 'product',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('product_id', '商品ID'),
      c.bigint('return_count', '退货件数'),
      c.decimal('return_amount', '退货金额'),
      c.varchar('top_reason', 100, '主要退货原因'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },

  /* ── risk domain (4) ── */
  {
    name: 'dws_risk_event_1d',
    comment: '风控事件日汇总（按规则聚合）',
    layer: 'dws',
    domain: 'risk',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('rule_name', 100, '规则名称'),
      c.varchar('risk_type', 50, '风险类型'),
      c.bigint('event_count', '事件数'),
      c.bigint('hit_count', '命中数'),
      c.double('hit_rate', '命中率'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dws_risk_user_score_1d',
    comment: '用户风险评分日快照',
    layer: 'dws',
    domain: 'risk',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('user_id', '用户ID'),
      c.double('risk_score', '风险分(0-100)'),
      c.varchar('risk_level', 20, '风险等级'),
      c.bigint('alert_count_7d', '近7日告警次数'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dws_risk_transaction_1d',
    comment: '交易风控日汇总（按风险等级聚合）',
    layer: 'dws',
    domain: 'risk',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('risk_level', 20, '风险等级'),
      c.bigint('transaction_count', '交易笔数'),
      c.decimal('transaction_amount', '交易金额'),
      c.bigint('blocked_count', '拦截笔数'),
      c.decimal('blocked_amount', '拦截金额'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dws_risk_compliance_1d',
    comment: '合规检查日汇总',
    layer: 'dws',
    domain: 'risk',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.varchar('check_type', 50, '检查类型'),
      c.bigint('total_checks', '检查总数'),
      c.bigint('pass_count', '通过数'),
      c.bigint('fail_count', '不通过数'),
      c.bigint('pending_count', '待审核数'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
];

/* ==============================================================
 *  DWD Layer — 10 tables (real-time detail event streams)
 * ============================================================== */

const dwdTables: TableDef[] = [
  /* ── trade domain (3) ── */
  {
    name: 'dwd_trade_order_detail',
    comment: '交易订单明细宽表（实时流）',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('order_id', '订单ID'),
      c.bigint('user_id', '用户ID'),
      c.bigint('seller_id', '商家ID'),
      c.bigint('product_id', '商品ID'),
      c.varchar('product_name', 200, '商品名称'),
      c.varchar('category_name', 100, '品类名'),
      c.int('quantity', '购买数量'),
      c.decimal('unit_price', '单价'),
      c.decimal('pay_amount', '实付金额'),
      c.decimal('discount_amount', '优惠金额'),
      c.varchar('payment_method', 50, '支付方式'),
      c.varchar('channel', 50, '渠道'),
      c.varchar('order_status', 30, '订单状态: created/paid/shipped/completed/cancelled'),
      c.datetime('order_time', '下单时间'),
      c.datetime('pay_time', '支付时间'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dwd_trade_refund_detail',
    comment: '退款明细宽表（实时流）',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('refund_id', '退款单ID'),
      c.bigint('order_id', '原始订单ID'),
      c.bigint('user_id', '用户ID'),
      c.bigint('product_id', '商品ID'),
      c.decimal('refund_amount', '退款金额'),
      c.varchar('refund_reason', 100, '退款原因'),
      c.varchar('refund_status', 30, '退款状态: pending/approved/rejected/completed'),
      c.datetime('apply_time', '申请时间'),
      c.datetime('complete_time', '完成时间'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dwd_trade_payment_detail',
    comment: '支付明细宽表（实时流）',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('payment_id', '支付单ID'),
      c.bigint('order_id', '订单ID'),
      c.bigint('user_id', '用户ID'),
      c.varchar('payment_method', 50, '支付方式'),
      c.decimal('pay_amount', '支付金额'),
      c.varchar('pay_status', 20, '支付状态: success/fail/pending'),
      c.varchar('pay_channel', 30, '支付通道'),
      c.datetime('pay_time', '支付时间'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },

  /* ── user domain (3) ── */
  {
    name: 'dwd_user_login_detail',
    comment: '用户登录明细宽表（实时流）',
    layer: 'dwd',
    domain: 'user',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('user_id', '用户ID'),
      c.varchar('platform', 30, '平台'),
      c.varchar('device_type', 30, '设备类型'),
      c.varchar('login_method', 30, '登录方式'),
      c.varchar('ip_address', 50, '登录IP'),
      c.varchar('region', 50, '登录地区'),
      c.bool('is_success', '是否登录成功'),
      c.datetime('login_time', '登录时间'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dwd_user_register_detail',
    comment: '用户注册明细宽表（实时流）',
    layer: 'dwd',
    domain: 'user',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('user_id', '用户ID'),
      c.varchar('channel', 50, '注册渠道'),
      c.varchar('platform', 30, '注册平台'),
      c.varchar('region', 50, '注册地区'),
      c.varchar('device_type', 30, '设备类型'),
      c.datetime('register_time', '注册时间'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dwd_user_behavior_detail',
    comment: '用户行为事件明细（页面浏览/点击/搜索）',
    layer: 'dwd',
    domain: 'user',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('user_id', '用户ID'),
      c.varchar('event_type', 30, '事件类型: page_view/click/search/add_cart'),
      c.varchar('page_name', 100, '页面名称'),
      c.varchar('element_id', 50, '元素ID'),
      c.varchar('platform', 30, '平台'),
      c.datetime('event_time', '事件时间'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },

  /* ── product domain (2) ── */
  {
    name: 'dwd_product_change_detail',
    comment: '商品变更明细（上下架/价格变动）',
    layer: 'dwd',
    domain: 'product',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('product_id', '商品ID'),
      c.varchar('change_type', 30, '变更类型: price/status/stock/info'),
      c.varchar('old_value', 200, '旧值'),
      c.varchar('new_value', 200, '新值'),
      c.bigint('operator_id', '操作人ID'),
      c.datetime('change_time', '变更时间'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dwd_product_review_detail',
    comment: '商品评价明细（实时流）',
    layer: 'dwd',
    domain: 'product',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('review_id', '评价ID'),
      c.bigint('product_id', '商品ID'),
      c.bigint('user_id', '用户ID'),
      c.int('rating', '评分(1-5)'),
      c.varchar('content', 500, '评价内容'),
      c.bool('has_image', '是否带图'),
      c.varchar('sentiment', 20, '情感: positive/neutral/negative'),
      c.datetime('review_time', '评价时间'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },

  /* ── risk domain (2) ── */
  {
    name: 'dwd_risk_event_detail',
    comment: '风控事件明细（实时流）',
    layer: 'dwd',
    domain: 'risk',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('event_id', '事件ID'),
      c.bigint('user_id', '触发用户ID'),
      c.varchar('risk_type', 50, '风险类型'),
      c.varchar('rule_name', 100, '命中规则'),
      c.double('risk_score', '风险分'),
      c.varchar('action_taken', 30, '处置动作: pass/block/review'),
      c.varchar('event_source', 50, '事件来源: payment/login/register'),
      c.datetime('event_time', '事件时间'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
  {
    name: 'dwd_risk_audit_detail',
    comment: '合规审核明细（实时流）',
    layer: 'dwd',
    domain: 'risk',
    columns: [
      c.pk('id', '主键ID'),
      c.ds(),
      c.bigint('audit_id', '审核单ID'),
      c.varchar('check_type', 50, '检查类型'),
      c.bigint('target_id', '审核对象ID'),
      c.varchar('target_type', 30, '对象类型: user/merchant/product'),
      c.varchar('audit_result', 20, '审核结果: pass/fail/pending'),
      c.varchar('fail_reason', 200, '不通过原因'),
      c.datetime('audit_time', '审核时间'),
      c.datetime('etl_time', 'ETL 处理时间'),
    ],
  },
];

/* ==============================================================
 *  DIM Layer — 5 tables (dimension tables)
 * ============================================================== */

const dimTables: TableDef[] = [
  {
    name: 'dim_product',
    comment: '商品维度表',
    layer: 'dim',
    domain: 'product',
    columns: [
      c.pk('product_id', '商品ID'),
      c.varchar('product_name', 200, '商品名称'),
      c.bigint('category_id', '品类ID'),
      c.varchar('category_name', 100, '品类名称'),
      c.varchar('brand_name', 100, '品牌名称'),
      c.bigint('seller_id', '商家ID'),
      c.varchar('seller_name', 100, '商家名称'),
      c.decimal('list_price', '标价'),
      c.varchar('status', 20, '状态: on_sale/off_shelf/deleted'),
      c.datetime('created_at', '创建时间'),
      c.datetime('updated_at', '更新时间'),
    ],
  },
  {
    name: 'dim_user',
    comment: '用户维度表',
    layer: 'dim',
    domain: 'user',
    columns: [
      c.pk('user_id', '用户ID'),
      c.varchar('nickname', 100, '昵称'),
      c.varchar('gender', 10, '性别'),
      c.varchar('age_group', 20, '年龄段: 18-24/25-34/35-44/45+'),
      c.varchar('province', 50, '省份'),
      c.varchar('city', 50, '城市'),
      c.varchar('register_channel', 50, '注册渠道'),
      c.varchar('user_tier', 30, '用户层级: new/active/loyal/vip'),
      c.date('register_date', '注册日期'),
      c.datetime('updated_at', '更新时间'),
    ],
  },
  {
    name: 'dim_seller',
    comment: '商家维度表',
    layer: 'dim',
    domain: 'trade',
    columns: [
      c.pk('seller_id', '商家ID'),
      c.varchar('seller_name', 100, '商家名称'),
      c.varchar('seller_type', 30, '商家类型: self/pop/flagship'),
      c.varchar('province', 50, '省份'),
      c.varchar('city', 50, '城市'),
      c.varchar('industry', 50, '行业'),
      c.varchar('status', 20, '状态: active/frozen/closed'),
      c.date('join_date', '入驻日期'),
      c.datetime('updated_at', '更新时间'),
    ],
  },
  {
    name: 'dim_category',
    comment: '品类维度表（三级品类树）',
    layer: 'dim',
    domain: 'product',
    columns: [
      c.pk('category_id', '品类ID'),
      c.varchar('category_name', 100, '品类名称'),
      c.int('level', '品类层级: 1/2/3'),
      c.bigint('parent_id', '父品类ID'),
      c.varchar('l1_name', 100, '一级品类名'),
      c.varchar('l2_name', 100, '二级品类名'),
      c.varchar('l3_name', 100, '三级品类名'),
      c.datetime('updated_at', '更新时间'),
    ],
  },
  {
    name: 'dim_region',
    comment: '地区维度表',
    layer: 'dim',
    domain: 'trade',
    columns: [
      c.pk('region_id', '地区ID'),
      c.varchar('province', 50, '省份'),
      c.varchar('city', 50, '城市'),
      c.varchar('district', 50, '区县'),
      c.varchar('region_tier', 20, '城市等级: tier1/tier2/tier3/tier4'),
      c.varchar('economic_zone', 50, '经济区: 长三角/珠三角/京津冀/成渝'),
      c.datetime('updated_at', '更新时间'),
    ],
  },
];

/* ==============================================================
 *  Metrics — 30 metric definitions
 * ============================================================== */

const metrics: MetricDef[] = [
  /* ── trade metrics (10) ── */
  {
    name: 'gmv_total',
    displayName: 'GMV 总额',
    expression: 'SUM(gmv_amount)',
    metricType: 'atomic',
    sourceTable: 'ads_trade_gmv_dashboard',
    dimensions: ['ds', 'channel', 'category_name'],
    granularity: ['day', 'week', 'month'],
    format: 'currency',
    description: '成交总金额（GMV），含退款前全量',
  },
  {
    name: 'order_count',
    displayName: '订单量',
    expression: 'SUM(order_count)',
    metricType: 'atomic',
    sourceTable: 'ads_trade_gmv_dashboard',
    dimensions: ['ds', 'channel', 'category_name'],
    granularity: ['day', 'week', 'month'],
    format: 'number',
    description: '下单数量，含所有状态订单',
  },
  {
    name: 'avg_order_value',
    displayName: '客单价',
    expression: 'SUM(gmv_amount) / NULLIF(SUM(order_count), 0)',
    metricType: 'derived',
    sourceTable: 'ads_trade_gmv_dashboard',
    dimensions: ['ds', 'channel', 'category_name'],
    granularity: ['day', 'week', 'month'],
    format: 'currency',
    description: '平均客单价 = GMV / 订单数',
  },
  {
    name: 'order_conversion_rate',
    displayName: '下单转化率',
    expression: 'AVG(conversion_rate)',
    metricType: 'derived',
    sourceTable: 'ads_trade_conversion_funnel',
    dimensions: ['ds', 'platform'],
    granularity: ['day', 'week'],
    format: 'percentage',
    description: '从浏览到下单的转化率',
  },
  {
    name: 'refund_amount_total',
    displayName: '退款总额',
    expression: 'SUM(refund_amount)',
    metricType: 'atomic',
    sourceTable: 'ads_trade_refund_analysis',
    dimensions: ['ds', 'refund_reason', 'category_name'],
    granularity: ['day', 'week', 'month'],
    format: 'currency',
    description: '退款金额合计',
  },
  {
    name: 'refund_rate',
    displayName: '退款率',
    expression: 'AVG(refund_rate)',
    metricType: 'derived',
    sourceTable: 'ads_trade_refund_analysis',
    dimensions: ['ds', 'category_name'],
    granularity: ['day', 'week'],
    format: 'percentage',
    description: '退款订单占比',
  },
  {
    name: 'pay_success_rate',
    displayName: '支付成功率',
    expression: 'AVG(pay_success_rate)',
    metricType: 'derived',
    sourceTable: 'ads_trade_payment_analysis',
    dimensions: ['ds', 'payment_method'],
    granularity: ['day', 'week'],
    format: 'percentage',
    description: '支付成功订单占比',
  },
  {
    name: 'coupon_use_rate',
    displayName: '优惠券核销率',
    expression: 'AVG(use_rate)',
    metricType: 'derived',
    sourceTable: 'ads_trade_coupon_effect',
    dimensions: ['ds', 'coupon_type'],
    granularity: ['day', 'week'],
    format: 'percentage',
    description: '优惠券核销率 = 使用张数 / 发放张数',
  },
  {
    name: 'coupon_driven_gmv',
    displayName: '优惠券带动GMV',
    expression: 'SUM(driven_gmv)',
    metricType: 'atomic',
    sourceTable: 'ads_trade_coupon_effect',
    dimensions: ['ds', 'coupon_type'],
    granularity: ['day', 'week', 'month'],
    format: 'currency',
    description: '使用优惠券的订单产生的GMV',
  },
  {
    name: 'seller_top_gmv',
    displayName: '商家 TOP GMV',
    expression: 'SUM(gmv_amount)',
    metricType: 'atomic',
    sourceTable: 'ads_trade_seller_ranking',
    dimensions: ['ds', 'seller_id', 'seller_name'],
    granularity: ['day', 'week', 'month'],
    format: 'currency',
    description: '单个商家 GMV（用于排行榜）',
  },

  /* ── user metrics (8) ── */
  {
    name: 'dau',
    displayName: '日活跃用户数',
    expression: 'SUM(dau)',
    metricType: 'atomic',
    sourceTable: 'ads_user_active_dashboard',
    dimensions: ['ds', 'platform', 'region'],
    granularity: ['day'],
    format: 'number',
    description: '日活跃用户数（DAU）',
  },
  {
    name: 'wau',
    displayName: '周活跃用户数',
    expression: 'SUM(wau)',
    metricType: 'atomic',
    sourceTable: 'ads_user_active_dashboard',
    dimensions: ['ds', 'platform', 'region'],
    granularity: ['week'],
    format: 'number',
    description: '周活跃用户数（WAU）',
  },
  {
    name: 'mau',
    displayName: '月活跃用户数',
    expression: 'SUM(mau)',
    metricType: 'atomic',
    sourceTable: 'ads_user_active_dashboard',
    dimensions: ['ds', 'platform', 'region'],
    granularity: ['month'],
    format: 'number',
    description: '月活跃用户数（MAU）',
  },
  {
    name: 'new_user_count',
    displayName: '新增用户数',
    expression: 'SUM(new_users)',
    metricType: 'atomic',
    sourceTable: 'ads_user_active_dashboard',
    dimensions: ['ds', 'platform', 'region'],
    granularity: ['day', 'week', 'month'],
    format: 'number',
    description: '当日新增注册用户数',
  },
  {
    name: 'retention_1d',
    displayName: '次日留存率',
    expression: 'AVG(retention_1d)',
    metricType: 'derived',
    sourceTable: 'ads_user_retention_report',
    dimensions: ['ds', 'cohort_date'],
    granularity: ['day'],
    format: 'percentage',
    description: '注册次日回访留存率',
  },
  {
    name: 'retention_7d',
    displayName: '7日留存率',
    expression: 'AVG(retention_7d)',
    metricType: 'derived',
    sourceTable: 'ads_user_retention_report',
    dimensions: ['ds', 'cohort_date'],
    granularity: ['week'],
    format: 'percentage',
    description: '注册7日后回访留存率',
  },
  {
    name: 'avg_ltv',
    displayName: '用户平均 LTV',
    expression: 'AVG(avg_ltv)',
    metricType: 'derived',
    sourceTable: 'ads_user_ltv_analysis',
    dimensions: ['ds', 'user_tier'],
    granularity: ['month'],
    format: 'currency',
    description: '用户生命周期价值平均值',
  },
  {
    name: 'churn_risk_user_count',
    displayName: '流失风险用户数',
    expression: 'SUM(user_count)',
    metricType: 'atomic',
    sourceTable: 'ads_user_churn_warning',
    dimensions: ['ds', 'risk_level'],
    granularity: ['day', 'week'],
    format: 'number',
    description: '按风险等级统计的流失预警用户数',
  },

  /* ── product metrics (7) ── */
  {
    name: 'product_sale_amount',
    displayName: '商品销售额',
    expression: 'SUM(sale_amount)',
    metricType: 'atomic',
    sourceTable: 'ads_product_hot_ranking',
    dimensions: ['ds', 'product_id', 'product_name', 'category_name'],
    granularity: ['day', 'week', 'month'],
    format: 'currency',
    description: '单品销售金额（用于排行）',
  },
  {
    name: 'product_sale_count',
    displayName: '商品销量',
    expression: 'SUM(sale_count)',
    metricType: 'atomic',
    sourceTable: 'ads_product_hot_ranking',
    dimensions: ['ds', 'product_id', 'product_name', 'category_name'],
    granularity: ['day', 'week', 'month'],
    format: 'number',
    description: '单品销售件数',
  },
  {
    name: 'category_gmv',
    displayName: '品类 GMV',
    expression: 'SUM(gmv_amount)',
    metricType: 'atomic',
    sourceTable: 'ads_product_category_analysis',
    dimensions: ['ds', 'category_id', 'category_name'],
    granularity: ['day', 'week', 'month'],
    format: 'currency',
    description: '品类维度成交金额',
  },
  {
    name: 'category_avg_price',
    displayName: '品类均价',
    expression: 'AVG(avg_price)',
    metricType: 'derived',
    sourceTable: 'ads_product_category_analysis',
    dimensions: ['ds', 'category_id', 'category_name'],
    granularity: ['day', 'week'],
    format: 'currency',
    description: '品类下商品平均成交价',
  },
  {
    name: 'product_return_rate',
    displayName: '商品退货率',
    expression: 'AVG(return_rate)',
    metricType: 'derived',
    sourceTable: 'ads_product_return_analysis',
    dimensions: ['ds', 'category_name', 'return_reason'],
    granularity: ['day', 'week'],
    format: 'percentage',
    description: '退货件数 / 销售件数',
  },
  {
    name: 'avg_product_rating',
    displayName: '商品平均评分',
    expression: 'AVG(avg_rating)',
    metricType: 'derived',
    sourceTable: 'ads_product_review_summary',
    dimensions: ['ds', 'category_name'],
    granularity: ['day', 'week'],
    format: 'number',
    description: '商品用户评分平均值(1-5分)',
  },
  {
    name: 'positive_review_rate',
    displayName: '好评率',
    expression: 'AVG(positive_rate)',
    metricType: 'derived',
    sourceTable: 'ads_product_review_summary',
    dimensions: ['ds', 'category_name'],
    granularity: ['day', 'week'],
    format: 'percentage',
    description: '4-5星评价占比',
  },

  /* ── risk metrics (5) ── */
  {
    name: 'fraud_alert_count',
    displayName: '欺诈告警次数',
    expression: 'SUM(alert_count)',
    metricType: 'atomic',
    sourceTable: 'ads_risk_fraud_monitor',
    dimensions: ['ds', 'risk_type'],
    granularity: ['day', 'week'],
    format: 'number',
    description: '欺诈风险告警总次数',
  },
  {
    name: 'fraud_false_positive_rate',
    displayName: '欺诈误报率',
    expression: 'AVG(false_positive_rate)',
    metricType: 'derived',
    sourceTable: 'ads_risk_fraud_monitor',
    dimensions: ['ds', 'risk_type'],
    granularity: ['day', 'week'],
    format: 'percentage',
    description: '欺诈检测的误报率',
  },
  {
    name: 'blocked_amount',
    displayName: '风控拦截金额',
    expression: 'SUM(blocked_amount)',
    metricType: 'atomic',
    sourceTable: 'ads_risk_fraud_monitor',
    dimensions: ['ds', 'risk_type'],
    granularity: ['day', 'week', 'month'],
    format: 'currency',
    description: '被风控拦截的交易金额',
  },
  {
    name: 'compliance_pass_rate',
    displayName: '合规通过率',
    expression: 'AVG(pass_rate)',
    metricType: 'derived',
    sourceTable: 'ads_risk_compliance_dashboard',
    dimensions: ['ds', 'check_type'],
    granularity: ['day', 'week'],
    format: 'percentage',
    description: '合规检查通过率',
  },
  {
    name: 'risk_block_rate',
    displayName: '风控拦截率',
    expression: 'AVG(block_rate)',
    metricType: 'derived',
    sourceTable: 'ads_risk_realtime_alert',
    dimensions: ['ds', 'rule_name', 'severity'],
    granularity: ['day', 'week'],
    format: 'percentage',
    description: '风控规则触发后的拦截比例',
  },
];

/* ==============================================================
 *  Glossary — 10 OLAP-specific terms
 * ============================================================== */

const glossary: GlossaryDef[] = [
  {
    term: 'GMV',
    sqlExpression: 'SUM(gmv_amount)',
    description: 'Gross Merchandise Volume，成交总额，含退款前全量订单金额',
  },
  {
    term: 'DAU',
    sqlExpression: 'SUM(dau)',
    description: 'Daily Active Users，日活跃用户数，去重统计当日有任何行为的用户',
  },
  {
    term: '客单价',
    sqlExpression: 'SUM(gmv_amount) / NULLIF(SUM(order_count), 0)',
    description: 'Average Order Value，每笔订单平均金额 = GMV / 订单数',
  },
  {
    term: '次留',
    sqlExpression: 'AVG(retention_1d)',
    description: '次日留存率，新注册用户次日回访占比',
  },
  {
    term: 'LTV',
    sqlExpression: 'AVG(avg_ltv)',
    description: 'Life Time Value，用户生命周期价值，用户从注册到流失的总贡献收入',
  },
  {
    term: '转化漏斗',
    sqlExpression: "SELECT step_name, user_count, conversion_rate FROM ads_trade_conversion_funnel WHERE ds = '${ds}'",
    description: '用户从浏览→加购→下单→支付的逐步转化过程，每步计算转化率',
  },
  {
    term: 'ARPU',
    sqlExpression: 'SUM(total_revenue) / NULLIF(SUM(user_count), 0)',
    description: 'Average Revenue Per User，每用户平均收入',
  },
  {
    term: '实时汇总层(DWS)',
    sqlExpression: "SELECT * FROM information_schema.tables WHERE table_name LIKE 'dws_%'",
    description: 'Data Warehouse Summary，按主题域+时间粒度预聚合的汇总层，是 ADS 层的数据来源',
  },
  {
    term: '误报率',
    sqlExpression: 'AVG(false_positive_rate)',
    description: 'False Positive Rate，风控系统将正常交易误判为欺诈的比例',
  },
  {
    term: '队列分析(Cohort)',
    sqlExpression: "SELECT cohort_date, retention_1d, retention_7d, retention_30d FROM ads_user_retention_report WHERE ds = '${ds}'",
    description: '按用户注册日期分组，追踪同一批用户在后续各时间点的留存表现',
  },
];

/* ==============================================================
 *  Export: dorisSeed
 * ============================================================== */

const tables: TableDef[] = [...adsTables, ...dwsTables, ...dwdTables, ...dimTables];

export const dorisSeed: EngineSeedDefinition = {
  engineType: 'doris',
  name: 'Doris OLAP 引擎',
  description: 'Apache Doris 实时 OLAP 分析引擎，承载 ADS 指标层和 DWS 实时汇总',
  dialect: 'mysql',
  pgSchema: 'dw_doris',
  tables,
  metrics,
  glossary,
};
