import type { EngineSeedDefinition, TableDef, MetricDef, GlossaryDef } from './types.js';

/* ═══════════════════════════════════════════════
 * Helper — shorthand column builders for Hive
 * ═══════════════════════════════════════════════ */

const pk = (name: string, comment: string) =>
  ({ name, dataType: 'BIGINT', comment, isPrimaryKey: true }) as const;

const bigint = (name: string, comment: string, extra: Record<string, unknown> = {}) =>
  ({ name, dataType: 'BIGINT', comment, ...extra }) as const;

const str = (name: string, comment: string, extra: Record<string, unknown> = {}) =>
  ({ name, dataType: 'STRING', comment, ...extra }) as const;

const dec = (name: string, comment: string) =>
  ({ name, dataType: 'DECIMAL(18,2)', comment }) as const;

const ts = (name: string, comment: string) =>
  ({ name, dataType: 'TIMESTAMP', comment }) as const;

const int = (name: string, comment: string, extra: Record<string, unknown> = {}) =>
  ({ name, dataType: 'INT', comment, ...extra }) as const;

const dbl = (name: string, comment: string) =>
  ({ name, dataType: 'DOUBLE', comment }) as const;

const bool = (name: string, comment: string) =>
  ({ name, dataType: 'BOOLEAN', comment }) as const;

const dt = (name: string, comment: string) =>
  ({ name, dataType: 'DATE', comment }) as const;

const ds = () => dt('ds', '数据分区日期');

const fk = (name: string, refTable: string, comment: string) =>
  ({ name, dataType: 'BIGINT', comment, referencesTable: refTable, referencesColumn: 'id' }) as const;

/* ═══════════════════════════════════════════════
 * DWD Layer — 30 detail fact tables
 * ═══════════════════════════════════════════════ */

const dwdTables: TableDef[] = [
  /* ── trade domain (10) ── */
  {
    name: 'dwd_trade_order_di',
    comment: '订单明细表-日增量',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      pk('order_id', '订单ID'),
      fk('user_id', 'dim_user_profile', '下单用户ID'),
      fk('merchant_id', 'dim_merchant', '商家ID'),
      str('order_no', '订单编号'),
      dec('order_amount', '订单金额'),
      dec('discount_amount', '优惠金额'),
      dec('pay_amount', '实付金额'),
      int('item_count', '商品件数'),
      str('order_status', '订单状态', { sampleValues: ['created', 'paid', 'shipped', 'completed', 'cancelled'] }),
      str('channel', '下单渠道', { sampleValues: ['app', 'h5', 'mini_program', 'pc'] }),
      ts('order_time', '下单时间'),
      str('platform', '平台', { sampleValues: ['ios', 'android', 'web'] }),
      ds(),
    ],
  },
  {
    name: 'dwd_trade_payment_di',
    comment: '支付流水明细-日增量',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      pk('payment_id', '支付流水ID'),
      fk('order_id', 'dwd_trade_order_di', '关联订单ID'),
      fk('user_id', 'dim_user_profile', '支付用户ID'),
      str('payment_no', '支付单号'),
      dec('pay_amount', '支付金额'),
      str('pay_method', '支付方式', { sampleValues: ['alipay', 'wechat_pay', 'bank_card', 'balance'] }),
      str('pay_status', '支付状态', { sampleValues: ['pending', 'success', 'failed', 'refunded'] }),
      str('third_party_no', '第三方流水号'),
      ts('pay_time', '支付完成时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_trade_refund_di',
    comment: '退款明细-日增量',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      pk('refund_id', '退款ID'),
      fk('order_id', 'dwd_trade_order_di', '原订单ID'),
      fk('user_id', 'dim_user_profile', '退款用户ID'),
      str('refund_no', '退款单号'),
      dec('refund_amount', '退款金额'),
      str('refund_reason', '退款原因', { sampleValues: ['quality_issue', 'wrong_item', 'not_needed', 'logistics_delay'] }),
      str('refund_status', '退款状态', { sampleValues: ['applied', 'approved', 'rejected', 'completed'] }),
      ts('apply_time', '申请时间'),
      ts('complete_time', '退款完成时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_trade_settlement_di',
    comment: '结算明细-日增量',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      pk('settlement_id', '结算ID'),
      fk('merchant_id', 'dim_merchant', '商家ID'),
      fk('order_id', 'dwd_trade_order_di', '订单ID'),
      dec('settlement_amount', '结算金额'),
      dec('commission_amount', '佣金金额'),
      dec('service_fee', '服务费'),
      str('settlement_status', '结算状态', { sampleValues: ['pending', 'settled', 'frozen'] }),
      dt('settlement_date', '结算日期'),
      ds(),
    ],
  },
  {
    name: 'dwd_trade_cart_di',
    comment: '购物车操作明细-日增量',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      pk('cart_id', '购物车记录ID'),
      fk('user_id', 'dim_user_profile', '用户ID'),
      fk('sku_id', 'dim_product_sku', '商品SKU ID'),
      int('quantity', '数量'),
      dec('unit_price', '加入时单价'),
      str('action', '操作类型', { sampleValues: ['add', 'remove', 'update_qty'] }),
      ts('action_time', '操作时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_trade_order_item_di',
    comment: '订单商品明细-日增量',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      pk('item_id', '订单项ID'),
      fk('order_id', 'dwd_trade_order_di', '订单ID'),
      fk('sku_id', 'dim_product_sku', '商品SKU ID'),
      str('sku_name', '商品名称'),
      int('quantity', '购买数量'),
      dec('unit_price', '商品单价'),
      dec('total_price', '小计金额'),
      dec('discount_amount', '优惠金额'),
      ds(),
    ],
  },
  {
    name: 'dwd_trade_coupon_use_di',
    comment: '优惠券使用明细-日增量',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      pk('record_id', '记录ID'),
      fk('user_id', 'dim_user_profile', '用户ID'),
      fk('order_id', 'dwd_trade_order_di', '关联订单ID'),
      str('coupon_id', '优惠券ID'),
      str('coupon_type', '优惠券类型', { sampleValues: ['full_reduction', 'discount', 'free_shipping'] }),
      dec('coupon_value', '优惠券面值'),
      dec('actual_discount', '实际抵扣金额'),
      ts('use_time', '使用时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_trade_logistics_di',
    comment: '物流跟踪明细-日增量',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      pk('logistics_id', '物流记录ID'),
      fk('order_id', 'dwd_trade_order_di', '订单ID'),
      str('tracking_no', '运单号'),
      str('carrier', '物流公司', { sampleValues: ['sf_express', 'yto', 'zto', 'yunda', 'jd_logistics'] }),
      str('logistics_status', '物流状态', { sampleValues: ['collected', 'in_transit', 'delivering', 'signed'] }),
      ts('status_time', '状态更新时间'),
      str('current_city', '当前所在城市'),
      ds(),
    ],
  },
  {
    name: 'dwd_trade_review_di',
    comment: '交易评价明细-日增量',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      pk('review_id', '评价ID'),
      fk('order_id', 'dwd_trade_order_di', '订单ID'),
      fk('user_id', 'dim_user_profile', '评价用户ID'),
      fk('sku_id', 'dim_product_sku', '商品SKU ID'),
      int('rating', '评分1-5'),
      str('review_content', '评价内容'),
      bool('has_image', '是否含图'),
      ts('review_time', '评价时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_trade_invoice_di',
    comment: '发票明细-日增量',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      pk('invoice_id', '发票ID'),
      fk('order_id', 'dwd_trade_order_di', '关联订单ID'),
      fk('user_id', 'dim_user_profile', '申请用户ID'),
      str('invoice_type', '发票类型', { sampleValues: ['personal', 'company'] }),
      str('invoice_title', '发票抬头'),
      dec('invoice_amount', '发票金额'),
      str('tax_no', '税号'),
      str('invoice_status', '开票状态', { sampleValues: ['pending', 'issued', 'cancelled'] }),
      ts('apply_time', '申请时间'),
      ds(),
    ],
  },

  /* ── user domain (8) ── */
  {
    name: 'dwd_user_login_di',
    comment: '用户登录明细-日增量',
    layer: 'dwd',
    domain: 'user',
    columns: [
      pk('login_id', '登录记录ID'),
      fk('user_id', 'dim_user_profile', '用户ID'),
      str('login_method', '登录方式', { sampleValues: ['password', 'sms', 'wechat', 'fingerprint'] }),
      str('device_type', '设备类型', { sampleValues: ['ios', 'android', 'web', 'h5'] }),
      str('device_model', '设备型号'),
      str('ip_address', '登录IP'),
      str('city', '登录城市'),
      bool('is_success', '是否成功'),
      ts('login_time', '登录时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_user_register_di',
    comment: '用户注册明细-日增量',
    layer: 'dwd',
    domain: 'user',
    columns: [
      pk('register_id', '注册记录ID'),
      bigint('user_id', '新用户ID'),
      str('register_channel', '注册渠道', { sampleValues: ['organic', 'invite', 'ad_campaign', 'social'] }),
      str('register_source', '注册来源', { sampleValues: ['app', 'wechat_mini', 'h5', 'pc'] }),
      str('device_type', '设备类型', { sampleValues: ['ios', 'android', 'web'] }),
      str('ip_address', '注册IP'),
      str('city', '注册城市'),
      ts('register_time', '注册时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_user_behavior_di',
    comment: '用户行为埋点-日增量',
    layer: 'dwd',
    domain: 'user',
    columns: [
      pk('event_id', '事件ID'),
      fk('user_id', 'dim_user_profile', '用户ID'),
      str('event_type', '事件类型', { sampleValues: ['click', 'expose', 'scroll', 'share', 'search'] }),
      str('page_id', '页面ID'),
      str('element_id', '元素ID'),
      str('session_id', '会话ID'),
      str('device_type', '设备类型', { sampleValues: ['ios', 'android', 'web'] }),
      int('duration_ms', '停留时长(毫秒)'),
      ts('event_time', '事件时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_user_share_di',
    comment: '用户分享明细-日增量',
    layer: 'dwd',
    domain: 'user',
    columns: [
      pk('share_id', '分享ID'),
      fk('user_id', 'dim_user_profile', '分享用户ID'),
      str('share_type', '分享类型', { sampleValues: ['product', 'article', 'coupon', 'invite'] }),
      str('share_channel', '分享渠道', { sampleValues: ['wechat', 'weibo', 'qq', 'link'] }),
      str('target_id', '被分享对象ID'),
      int('click_count', '被点击次数'),
      ts('share_time', '分享时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_user_feedback_di',
    comment: '用户反馈明细-日增量',
    layer: 'dwd',
    domain: 'user',
    columns: [
      pk('feedback_id', '反馈ID'),
      fk('user_id', 'dim_user_profile', '用户ID'),
      str('feedback_type', '反馈类型', { sampleValues: ['bug', 'suggestion', 'complaint', 'praise'] }),
      str('content', '反馈内容'),
      str('feedback_status', '处理状态', { sampleValues: ['pending', 'processing', 'resolved', 'closed'] }),
      int('priority', '优先级1-5'),
      ts('submit_time', '提交时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_user_search_di',
    comment: '用户搜索明细-日增量',
    layer: 'dwd',
    domain: 'user',
    columns: [
      pk('search_id', '搜索ID'),
      fk('user_id', 'dim_user_profile', '用户ID'),
      str('keyword', '搜索关键词'),
      int('result_count', '搜索结果数'),
      bool('has_click', '是否点击结果'),
      str('search_source', '搜索来源', { sampleValues: ['homepage', 'category', 'search_box'] }),
      ts('search_time', '搜索时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_user_address_change_di',
    comment: '用户地址变更明细-日增量',
    layer: 'dwd',
    domain: 'user',
    columns: [
      pk('change_id', '变更ID'),
      fk('user_id', 'dim_user_profile', '用户ID'),
      str('action', '操作类型', { sampleValues: ['add', 'update', 'delete', 'set_default'] }),
      str('province', '省份'),
      str('city', '城市'),
      str('district', '区县'),
      ts('change_time', '变更时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_user_point_change_di',
    comment: '用户积分变动明细-日增量',
    layer: 'dwd',
    domain: 'user',
    columns: [
      pk('record_id', '记录ID'),
      fk('user_id', 'dim_user_profile', '用户ID'),
      str('change_type', '变动类型', { sampleValues: ['earn_purchase', 'earn_sign_in', 'spend', 'expire'] }),
      int('point_change', '积分变动量'),
      int('balance_after', '变动后余额'),
      str('source', '来源', { sampleValues: ['order', 'activity', 'sign_in', 'admin'] }),
      ts('change_time', '变动时间'),
      ds(),
    ],
  },

  /* ── product domain (6) ── */
  {
    name: 'dwd_product_view_di',
    comment: '商品浏览明细-日增量',
    layer: 'dwd',
    domain: 'product',
    columns: [
      pk('view_id', '浏览ID'),
      fk('user_id', 'dim_user_profile', '用户ID'),
      fk('sku_id', 'dim_product_sku', '商品SKU ID'),
      fk('category_id', 'dim_product_category', '品类ID'),
      str('source_page', '来源页面', { sampleValues: ['search', 'recommend', 'category', 'ad'] }),
      int('stay_duration_ms', '停留时长(毫秒)'),
      bool('is_add_cart', '是否加购'),
      str('device_type', '设备类型', { sampleValues: ['ios', 'android', 'web'] }),
      ts('view_time', '浏览时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_product_click_di',
    comment: '商品点击明细-日增量',
    layer: 'dwd',
    domain: 'product',
    columns: [
      pk('click_id', '点击ID'),
      fk('user_id', 'dim_user_profile', '用户ID'),
      fk('sku_id', 'dim_product_sku', '商品SKU ID'),
      str('click_position', '点击位置', { sampleValues: ['banner', 'recommend_list', 'search_result', 'flash_sale'] }),
      int('rank_position', '排序位置'),
      str('page_id', '页面ID'),
      ts('click_time', '点击时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_product_inventory_change_di',
    comment: '库存变动明细-日增量',
    layer: 'dwd',
    domain: 'product',
    columns: [
      pk('change_id', '变动ID'),
      fk('sku_id', 'dim_product_sku', '商品SKU ID'),
      str('change_type', '变动类型', { sampleValues: ['inbound', 'outbound', 'adjust', 'return'] }),
      int('change_qty', '变动数量'),
      int('stock_after', '变动后库存'),
      str('warehouse_id', '仓库ID'),
      ts('change_time', '变动时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_product_price_change_di',
    comment: '商品价格变动明细-日增量',
    layer: 'dwd',
    domain: 'product',
    columns: [
      pk('change_id', '变动ID'),
      fk('sku_id', 'dim_product_sku', '商品SKU ID'),
      dec('old_price', '原价'),
      dec('new_price', '新价'),
      str('change_reason', '调价原因', { sampleValues: ['promotion', 'cost_adjust', 'competitor', 'clearance'] }),
      str('operator', '操作人'),
      ts('change_time', '变动时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_product_collect_di',
    comment: '商品收藏明细-日增量',
    layer: 'dwd',
    domain: 'product',
    columns: [
      pk('collect_id', '收藏ID'),
      fk('user_id', 'dim_user_profile', '用户ID'),
      fk('sku_id', 'dim_product_sku', '商品SKU ID'),
      str('action', '操作', { sampleValues: ['collect', 'cancel'] }),
      ts('action_time', '操作时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_product_publish_di',
    comment: '商品上下架明细-日增量',
    layer: 'dwd',
    domain: 'product',
    columns: [
      pk('record_id', '记录ID'),
      fk('sku_id', 'dim_product_sku', '商品SKU ID'),
      fk('merchant_id', 'dim_merchant', '商家ID'),
      str('action', '操作', { sampleValues: ['publish', 'unpublish', 'force_offline'] }),
      str('reason', '原因'),
      str('operator', '操作人'),
      ts('action_time', '操作时间'),
      ds(),
    ],
  },

  /* ── risk domain (6) ── */
  {
    name: 'dwd_risk_alert_di',
    comment: '风控告警明细-日增量',
    layer: 'dwd',
    domain: 'risk',
    columns: [
      pk('alert_id', '告警ID'),
      fk('user_id', 'dim_user_profile', '关联用户ID'),
      str('alert_type', '告警类型', { sampleValues: ['fraud', 'abnormal_login', 'money_laundering', 'bot_traffic'] }),
      str('risk_level', '风险等级', { sampleValues: ['low', 'medium', 'high', 'critical'] }),
      str('alert_source', '告警来源', { sampleValues: ['rule_engine', 'ml_model', 'manual'] }),
      str('alert_detail', '告警详情'),
      str('alert_status', '处理状态', { sampleValues: ['open', 'investigating', 'resolved', 'dismissed'] }),
      dbl('risk_score', '风险评分(0-100)'),
      ts('alert_time', '告警时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_risk_kyc_di',
    comment: 'KYC认证明细-日增量',
    layer: 'dwd',
    domain: 'risk',
    columns: [
      pk('kyc_id', '认证ID'),
      fk('user_id', 'dim_user_profile', '用户ID'),
      str('kyc_level', '认证级别', { sampleValues: ['L1_basic', 'L2_id_verify', 'L3_face_verify'] }),
      str('kyc_status', '认证状态', { sampleValues: ['pending', 'approved', 'rejected', 'expired'] }),
      str('reject_reason', '拒绝原因'),
      str('id_type', '证件类型', { sampleValues: ['id_card', 'passport', 'business_license'] }),
      ts('submit_time', '提交时间'),
      ts('review_time', '审核时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_risk_transaction_check_di',
    comment: '交易风控核查明细-日增量',
    layer: 'dwd',
    domain: 'risk',
    columns: [
      pk('check_id', '核查ID'),
      fk('order_id', 'dwd_trade_order_di', '关联订单ID'),
      fk('user_id', 'dim_user_profile', '用户ID'),
      str('check_result', '核查结果', { sampleValues: ['pass', 'block', 'review'] }),
      str('rule_hit', '命中规则'),
      dbl('model_score', '模型评分'),
      int('latency_ms', '检测耗时(毫秒)'),
      ts('check_time', '核查时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_risk_blacklist_change_di',
    comment: '黑名单变更明细-日增量',
    layer: 'dwd',
    domain: 'risk',
    columns: [
      pk('record_id', '记录ID'),
      str('entity_type', '实体类型', { sampleValues: ['user', 'device', 'ip', 'phone'] }),
      str('entity_id', '实体ID'),
      str('action', '操作', { sampleValues: ['add', 'remove'] }),
      str('reason', '原因'),
      str('operator', '操作人'),
      ts('action_time', '操作时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_risk_device_fingerprint_di',
    comment: '设备指纹采集明细-日增量',
    layer: 'dwd',
    domain: 'risk',
    columns: [
      pk('fingerprint_id', '指纹ID'),
      fk('user_id', 'dim_user_profile', '关联用户ID'),
      str('device_id', '设备唯一ID'),
      str('device_type', '设备类型', { sampleValues: ['ios', 'android', 'web'] }),
      str('os_version', '操作系统版本'),
      str('browser_ua', '浏览器User-Agent'),
      str('ip_address', 'IP地址'),
      bool('is_emulator', '是否模拟器'),
      ts('collect_time', '采集时间'),
      ds(),
    ],
  },
  {
    name: 'dwd_risk_compliance_event_di',
    comment: '合规事件明细-日增量',
    layer: 'dwd',
    domain: 'risk',
    columns: [
      pk('event_id', '事件ID'),
      str('event_type', '事件类型', { sampleValues: ['data_breach', 'regulation_violation', 'policy_update', 'audit_finding'] }),
      str('severity', '严重级别', { sampleValues: ['info', 'warning', 'critical'] }),
      str('description', '事件描述'),
      str('affected_scope', '影响范围'),
      str('status', '处理状态', { sampleValues: ['open', 'mitigating', 'resolved'] }),
      str('handler', '处理人'),
      ts('event_time', '事件时间'),
      ds(),
    ],
  },
];

/* ═══════════════════════════════════════════════
 * DWS Layer — 20 aggregate/summary tables
 * ═══════════════════════════════════════════════ */

const dwsTables: TableDef[] = [
  /* ── trade (6) ── */
  {
    name: 'dws_trade_order_1d',
    comment: '订单日汇总',
    layer: 'dws',
    domain: 'trade',
    columns: [
      pk('id', '主键ID'),
      str('channel', '下单渠道', { sampleValues: ['app', 'h5', 'mini_program', 'pc'] }),
      str('platform', '平台', { sampleValues: ['ios', 'android', 'web'] }),
      bigint('order_count', '订单数'),
      dec('order_amount', '订单总金额'),
      dec('pay_amount', '实付总金额'),
      bigint('pay_user_count', '支付用户数'),
      dec('avg_order_amount', '客单价'),
      bigint('cancel_count', '取消订单数'),
      ds(),
    ],
  },
  {
    name: 'dws_trade_seller_1d',
    comment: '商家交易日汇总',
    layer: 'dws',
    domain: 'trade',
    columns: [
      pk('id', '主键ID'),
      fk('merchant_id', 'dim_merchant', '商家ID'),
      bigint('order_count', '订单数'),
      dec('gmv_amount', 'GMV金额'),
      dec('refund_amount', '退款金额'),
      dbl('refund_rate', '退款率'),
      bigint('buyer_count', '买家数'),
      bigint('sku_count', '动销SKU数'),
      ds(),
    ],
  },
  {
    name: 'dws_trade_payment_1d',
    comment: '支付日汇总',
    layer: 'dws',
    domain: 'trade',
    columns: [
      pk('id', '主键ID'),
      str('pay_method', '支付方式', { sampleValues: ['alipay', 'wechat_pay', 'bank_card', 'balance'] }),
      bigint('pay_count', '支付笔数'),
      dec('pay_amount', '支付总额'),
      bigint('success_count', '成功笔数'),
      bigint('fail_count', '失败笔数'),
      dbl('success_rate', '支付成功率'),
      ds(),
    ],
  },
  {
    name: 'dws_trade_refund_1d',
    comment: '退款日汇总',
    layer: 'dws',
    domain: 'trade',
    columns: [
      pk('id', '主键ID'),
      str('refund_reason', '退款原因', { sampleValues: ['quality_issue', 'wrong_item', 'not_needed', 'logistics_delay'] }),
      bigint('refund_count', '退款笔数'),
      dec('refund_amount', '退款总额'),
      bigint('user_count', '退款用户数'),
      dbl('avg_process_hours', '平均处理时长(小时)'),
      ds(),
    ],
  },
  {
    name: 'dws_trade_category_1d',
    comment: '品类交易日汇总',
    layer: 'dws',
    domain: 'trade',
    columns: [
      pk('id', '主键ID'),
      fk('category_id', 'dim_product_category', '品类ID'),
      str('category_name', '品类名称'),
      bigint('order_count', '订单数'),
      dec('gmv_amount', 'GMV金额'),
      bigint('buyer_count', '买家数'),
      bigint('sku_sold_count', '动销SKU数'),
      ds(),
    ],
  },
  {
    name: 'dws_trade_region_1d',
    comment: '地区交易日汇总',
    layer: 'dws',
    domain: 'trade',
    columns: [
      pk('id', '主键ID'),
      str('region', '地区', { sampleValues: ['华东', '华南', '华北', '西南', '东北'] }),
      str('province', '省份'),
      bigint('order_count', '订单数'),
      dec('gmv_amount', 'GMV金额'),
      bigint('user_count', '下单用户数'),
      ds(),
    ],
  },

  /* ── user (6) ── */
  {
    name: 'dws_user_active_1d',
    comment: '用户活跃日汇总',
    layer: 'dws',
    domain: 'user',
    columns: [
      pk('id', '主键ID'),
      str('platform', '平台', { sampleValues: ['ios', 'android', 'web', 'h5'] }),
      bigint('dau', '日活跃用户数'),
      bigint('new_user_count', '新增用户数'),
      bigint('login_count', '登录次数'),
      dbl('avg_session_duration', '平均会话时长(秒)'),
      bigint('bounce_count', '跳出用户数'),
      ds(),
    ],
  },
  {
    name: 'dws_user_retention_7d',
    comment: '用户7日留存',
    layer: 'dws',
    domain: 'user',
    columns: [
      pk('id', '主键ID'),
      str('register_channel', '注册渠道', { sampleValues: ['organic', 'invite', 'ad_campaign', 'social'] }),
      dt('cohort_date', '注册日期'),
      bigint('cohort_size', '注册人数'),
      bigint('retained_d1', '次日留存数'),
      bigint('retained_d3', '3日留存数'),
      bigint('retained_d7', '7日留存数'),
      dbl('retention_rate_d7', '7日留存率'),
      ds(),
    ],
  },
  {
    name: 'dws_user_retention_30d',
    comment: '用户30日留存',
    layer: 'dws',
    domain: 'user',
    columns: [
      pk('id', '主键ID'),
      str('register_channel', '注册渠道', { sampleValues: ['organic', 'invite', 'ad_campaign', 'social'] }),
      dt('cohort_date', '注册日期'),
      bigint('cohort_size', '注册人数'),
      bigint('retained_d14', '14日留存数'),
      bigint('retained_d30', '30日留存数'),
      dbl('retention_rate_d30', '30日留存率'),
      ds(),
    ],
  },
  {
    name: 'dws_user_behavior_1d',
    comment: '用户行为日汇总',
    layer: 'dws',
    domain: 'user',
    columns: [
      pk('id', '主键ID'),
      str('event_type', '事件类型', { sampleValues: ['click', 'expose', 'scroll', 'share', 'search'] }),
      str('platform', '平台', { sampleValues: ['ios', 'android', 'web'] }),
      bigint('event_count', '事件总数'),
      bigint('user_count', '触发用户数'),
      dbl('avg_duration_ms', '平均时长(毫秒)'),
      ds(),
    ],
  },
  {
    name: 'dws_user_channel_1d',
    comment: '用户渠道日汇总',
    layer: 'dws',
    domain: 'user',
    columns: [
      pk('id', '主键ID'),
      str('channel', '渠道', { sampleValues: ['organic', 'sem', 'social', 'referral', 'email'] }),
      bigint('new_user_count', '新增用户数'),
      bigint('active_user_count', '活跃用户数'),
      dec('acquisition_cost', '获客成本'),
      dbl('conversion_rate', '转化率'),
      ds(),
    ],
  },
  {
    name: 'dws_user_lifetime_value_30d',
    comment: '用户LTV 30日汇总',
    layer: 'dws',
    domain: 'user',
    columns: [
      pk('id', '主键ID'),
      str('user_segment', '用户分层', { sampleValues: ['high_value', 'medium_value', 'low_value', 'dormant'] }),
      bigint('user_count', '用户数'),
      dec('avg_ltv', '平均LTV'),
      dec('total_revenue', '总收入'),
      bigint('avg_order_count', '平均订单数'),
      ds(),
    ],
  },

  /* ── product (4) ── */
  {
    name: 'dws_product_sale_1d',
    comment: '商品销售日汇总',
    layer: 'dws',
    domain: 'product',
    columns: [
      pk('id', '主键ID'),
      fk('sku_id', 'dim_product_sku', '商品SKU ID'),
      str('category_name', '品类名称'),
      bigint('order_count', '订单数'),
      bigint('sale_qty', '销量'),
      dec('sale_amount', '销售金额'),
      bigint('view_count', '浏览量'),
      dbl('conversion_rate', '浏览-下单转化率'),
      ds(),
    ],
  },
  {
    name: 'dws_product_inventory_1d',
    comment: '商品库存日汇总',
    layer: 'dws',
    domain: 'product',
    columns: [
      pk('id', '主键ID'),
      fk('sku_id', 'dim_product_sku', '商品SKU ID'),
      str('warehouse_id', '仓库ID'),
      int('stock_qty', '库存数量'),
      int('inbound_qty', '入库数量'),
      int('outbound_qty', '出库数量'),
      dbl('turnover_rate', '库存周转率'),
      ds(),
    ],
  },
  {
    name: 'dws_product_category_1d',
    comment: '品类维度商品日汇总',
    layer: 'dws',
    domain: 'product',
    columns: [
      pk('id', '主键ID'),
      fk('category_id', 'dim_product_category', '品类ID'),
      str('category_name', '品类名称'),
      bigint('active_sku_count', '在售SKU数'),
      bigint('total_view_count', '总浏览量'),
      bigint('total_sale_qty', '总销量'),
      dec('total_sale_amount', '总销售金额'),
      ds(),
    ],
  },
  {
    name: 'dws_product_review_1d',
    comment: '商品评价日汇总',
    layer: 'dws',
    domain: 'product',
    columns: [
      pk('id', '主键ID'),
      fk('sku_id', 'dim_product_sku', '商品SKU ID'),
      bigint('review_count', '评价数'),
      dbl('avg_rating', '平均评分'),
      bigint('good_count', '好评数'),
      bigint('bad_count', '差评数'),
      dbl('good_rate', '好评率'),
      ds(),
    ],
  },

  /* ── risk (4) ── */
  {
    name: 'dws_risk_score_1d',
    comment: '风控评分日汇总',
    layer: 'dws',
    domain: 'risk',
    columns: [
      pk('id', '主键ID'),
      str('risk_level', '风险等级', { sampleValues: ['low', 'medium', 'high', 'critical'] }),
      bigint('alert_count', '告警数'),
      bigint('resolved_count', '已处理数'),
      dbl('avg_risk_score', '平均风险评分'),
      bigint('blocked_count', '拦截数'),
      dbl('false_positive_rate', '误报率'),
      ds(),
    ],
  },
  {
    name: 'dws_risk_rule_hit_1d',
    comment: '风控规则命中日汇总',
    layer: 'dws',
    domain: 'risk',
    columns: [
      pk('id', '主键ID'),
      str('rule_id', '规则ID'),
      str('rule_name', '规则名称'),
      bigint('trigger_count', '触发次数'),
      bigint('block_count', '拦截次数'),
      bigint('pass_count', '放行次数'),
      dbl('precision_rate', '准确率'),
      ds(),
    ],
  },
  {
    name: 'dws_risk_kyc_1d',
    comment: 'KYC认证日汇总',
    layer: 'dws',
    domain: 'risk',
    columns: [
      pk('id', '主键ID'),
      str('kyc_level', 'KYC级别', { sampleValues: ['L1_basic', 'L2_id_verify', 'L3_face_verify'] }),
      bigint('submit_count', '提交数'),
      bigint('approved_count', '通过数'),
      bigint('rejected_count', '拒绝数'),
      dbl('approval_rate', '通过率'),
      dbl('avg_review_hours', '平均审核时长(小时)'),
      ds(),
    ],
  },
  {
    name: 'dws_risk_fraud_1d',
    comment: '欺诈检测日汇总',
    layer: 'dws',
    domain: 'risk',
    columns: [
      pk('id', '主键ID'),
      str('fraud_type', '欺诈类型', { sampleValues: ['card_fraud', 'identity_theft', 'account_takeover', 'promo_abuse'] }),
      bigint('detected_count', '检测数'),
      bigint('confirmed_count', '确认数'),
      dec('loss_amount', '损失金额'),
      dec('prevented_amount', '止损金额'),
      dbl('detection_rate', '检出率'),
      ds(),
    ],
  },
];

/* ═══════════════════════════════════════════════
 * DIM Layer — 10 dimension tables
 * ═══════════════════════════════════════════════ */

const dimTables: TableDef[] = [
  {
    name: 'dim_user_profile',
    comment: '用户画像维度表',
    layer: 'dim',
    domain: 'user',
    columns: [
      pk('user_id', '用户ID'),
      str('nickname', '昵称'),
      str('gender', '性别', { sampleValues: ['male', 'female', 'unknown'] }),
      int('age', '年龄'),
      str('city', '所在城市'),
      str('province', '所在省份'),
      str('membership_level', '会员等级', { sampleValues: ['normal', 'silver', 'gold', 'platinum', 'diamond'] }),
      str('user_tag', '用户标签', { sampleValues: ['high_value', 'price_sensitive', 'new_user', 'dormant'] }),
      str('register_channel', '注册渠道', { sampleValues: ['organic', 'invite', 'ad_campaign', 'social'] }),
      dt('register_date', '注册日期'),
      dt('last_active_date', '最近活跃日期'),
      ts('etl_time', 'ETL更新时间'),
    ],
  },
  {
    name: 'dim_product_sku',
    comment: '商品SKU维度表',
    layer: 'dim',
    domain: 'product',
    columns: [
      pk('sku_id', 'SKU ID'),
      str('sku_name', 'SKU名称'),
      str('spu_id', 'SPU ID'),
      str('spu_name', 'SPU名称'),
      fk('category_id', 'dim_product_category', '品类ID'),
      str('category_name', '品类名称'),
      str('brand_name', '品牌名称'),
      dec('price', '售价'),
      dec('cost_price', '成本价'),
      str('status', 'SKU状态', { sampleValues: ['on_sale', 'off_shelf', 'sold_out'] }),
      fk('merchant_id', 'dim_merchant', '所属商家ID'),
      ts('etl_time', 'ETL更新时间'),
    ],
  },
  {
    name: 'dim_product_category',
    comment: '商品品类维度表',
    layer: 'dim',
    domain: 'product',
    columns: [
      pk('category_id', '品类ID'),
      str('category_name', '品类名称'),
      int('category_level', '品类层级1-3'),
      bigint('parent_category_id', '父品类ID'),
      str('category_path', '品类路径', { sampleValues: ['数码/手机/智能手机', '服装/女装/连衣裙', '食品/零食/坚果'] }),
      bool('is_leaf', '是否叶子节点'),
      int('sort_order', '排序权重'),
      ts('etl_time', 'ETL更新时间'),
    ],
  },
  {
    name: 'dim_merchant',
    comment: '商家维度表',
    layer: 'dim',
    domain: 'trade',
    columns: [
      pk('merchant_id', '商家ID'),
      str('merchant_name', '商家名称'),
      str('merchant_type', '商家类型', { sampleValues: ['self_operated', 'third_party', 'flagship'] }),
      str('industry', '行业', { sampleValues: ['electronics', 'fashion', 'food', 'home_appliance'] }),
      str('province', '所在省份'),
      str('city', '所在城市'),
      str('status', '商家状态', { sampleValues: ['active', 'suspended', 'closed'] }),
      int('service_score', '服务评分'),
      dt('join_date', '入驻日期'),
      ts('etl_time', 'ETL更新时间'),
    ],
  },
  {
    name: 'dim_region',
    comment: '地区维度表',
    layer: 'dim',
    domain: 'trade',
    columns: [
      pk('region_id', '地区ID'),
      str('region_name', '大区名称', { sampleValues: ['华东', '华南', '华北', '西南', '东北', '西北', '华中'] }),
      str('province', '省份'),
      str('city', '城市'),
      str('district', '区县'),
      int('tier', '城市等级1-5', { sampleValues: ['1', '2', '3', '4', '5'] }),
      str('zipcode', '邮编'),
      ts('etl_time', 'ETL更新时间'),
    ],
  },
  {
    name: 'dim_channel',
    comment: '渠道维度表',
    layer: 'dim',
    domain: 'user',
    columns: [
      pk('channel_id', '渠道ID'),
      str('channel_name', '渠道名称', { sampleValues: ['app_store', 'google_play', 'wechat_mini', 'h5', 'pc_web'] }),
      str('channel_type', '渠道类型', { sampleValues: ['organic', 'paid', 'social', 'direct'] }),
      str('medium', '媒介', { sampleValues: ['cpc', 'cpm', 'referral', 'organic'] }),
      str('source', '来源', { sampleValues: ['baidu', 'toutiao', 'wechat', 'douyin'] }),
      bool('is_active', '是否启用'),
      ts('etl_time', 'ETL更新时间'),
    ],
  },
  {
    name: 'dim_warehouse',
    comment: '仓库维度表',
    layer: 'dim',
    domain: 'product',
    columns: [
      pk('warehouse_id', '仓库ID'),
      str('warehouse_name', '仓库名称'),
      str('warehouse_type', '仓库类型', { sampleValues: ['central', 'regional', 'bonded', 'front'] }),
      str('province', '所在省份'),
      str('city', '所在城市'),
      int('capacity', '库容(件)'),
      bool('is_active', '是否启用'),
      ts('etl_time', 'ETL更新时间'),
    ],
  },
  {
    name: 'dim_coupon',
    comment: '优惠券维度表',
    layer: 'dim',
    domain: 'trade',
    columns: [
      pk('coupon_id', '优惠券ID'),
      str('coupon_name', '优惠券名称'),
      str('coupon_type', '优惠券类型', { sampleValues: ['full_reduction', 'discount', 'free_shipping'] }),
      dec('face_value', '面值'),
      dec('min_order_amount', '使用门槛'),
      dt('start_date', '生效日期'),
      dt('end_date', '失效日期'),
      str('status', '状态', { sampleValues: ['active', 'expired', 'disabled'] }),
      ts('etl_time', 'ETL更新时间'),
    ],
  },
  {
    name: 'dim_risk_rule',
    comment: '风控规则维度表',
    layer: 'dim',
    domain: 'risk',
    columns: [
      pk('rule_id', '规则ID'),
      str('rule_name', '规则名称'),
      str('rule_type', '规则类型', { sampleValues: ['threshold', 'velocity', 'pattern', 'ml_model'] }),
      str('target_event', '目标事件', { sampleValues: ['login', 'payment', 'register', 'withdraw'] }),
      str('risk_level', '对应风险等级', { sampleValues: ['low', 'medium', 'high', 'critical'] }),
      bool('is_enabled', '是否启用'),
      str('description', '规则描述'),
      ts('etl_time', 'ETL更新时间'),
    ],
  },
  {
    name: 'dim_date',
    comment: '日期维度表',
    layer: 'dim',
    domain: 'trade',
    columns: [
      pk('date_key', '日期主键(YYYYMMDD)'),
      dt('cal_date', '日期'),
      int('year', '年'),
      int('quarter', '季度'),
      int('month', '月'),
      int('week_of_year', '年内周数'),
      int('day_of_week', '周几(1=周一)'),
      bool('is_weekend', '是否周末'),
      bool('is_holiday', '是否节假日'),
      str('holiday_name', '节假日名称'),
    ],
  },
];

/* ═══════════════════════════════════════════════
 * ADS Layer — 10 metric/dashboard tables
 * ═══════════════════════════════════════════════ */

const adsTables: TableDef[] = [
  {
    name: 'ads_trade_gmv_dashboard',
    comment: 'GMV看板指标表',
    layer: 'ads',
    domain: 'trade',
    columns: [
      pk('id', '主键ID'),
      ds(),
      str('channel', '渠道', { sampleValues: ['app', 'h5', 'mini_program', 'pc'] }),
      str('category_name', '品类名称'),
      str('platform', '平台', { sampleValues: ['ios', 'android', 'web'] }),
      dec('gmv_amount', 'GMV金额'),
      bigint('order_count', '订单数'),
      bigint('pay_user_count', '支付用户数'),
      dec('avg_order_amount', '客单价'),
      dbl('pay_conversion_rate', '支付转化率'),
    ],
  },
  {
    name: 'ads_trade_conversion_funnel',
    comment: '交易转化漏斗',
    layer: 'ads',
    domain: 'trade',
    columns: [
      pk('id', '主键ID'),
      ds(),
      str('channel', '渠道', { sampleValues: ['app', 'h5', 'mini_program', 'pc'] }),
      str('platform', '平台', { sampleValues: ['ios', 'android', 'web'] }),
      bigint('uv_count', '页面UV'),
      bigint('product_view_count', '商品详情页UV'),
      bigint('cart_add_count', '加购UV'),
      bigint('order_submit_count', '提交订单UV'),
      bigint('pay_success_count', '支付成功UV'),
      dbl('view_to_cart_rate', '浏览-加购转化率'),
      dbl('cart_to_order_rate', '加购-下单转化率'),
      dbl('order_to_pay_rate', '下单-支付转化率'),
    ],
  },
  {
    name: 'ads_trade_merchant_rank',
    comment: '商家排行榜指标表',
    layer: 'ads',
    domain: 'trade',
    columns: [
      pk('id', '主键ID'),
      ds(),
      fk('merchant_id', 'dim_merchant', '商家ID'),
      str('merchant_name', '商家名称'),
      dec('gmv_amount', 'GMV金额'),
      bigint('order_count', '订单数'),
      bigint('buyer_count', '买家数'),
      dbl('refund_rate', '退款率'),
      int('service_score', '服务评分'),
      int('rank_position', '排名位置'),
    ],
  },
  {
    name: 'ads_user_growth_dashboard',
    comment: '用户增长看板',
    layer: 'ads',
    domain: 'user',
    columns: [
      pk('id', '主键ID'),
      ds(),
      str('channel', '渠道', { sampleValues: ['organic', 'sem', 'social', 'referral'] }),
      str('platform', '平台', { sampleValues: ['ios', 'android', 'web'] }),
      bigint('dau', '日活用户数'),
      bigint('wau', '周活用户数'),
      bigint('mau', '月活用户数'),
      bigint('new_user_count', '新增用户数'),
      dbl('d1_retention_rate', '次日留存率'),
      dbl('d7_retention_rate', '7日留存率'),
      dbl('d30_retention_rate', '30日留存率'),
    ],
  },
  {
    name: 'ads_user_segment_profile',
    comment: '用户分层画像指标',
    layer: 'ads',
    domain: 'user',
    columns: [
      pk('id', '主键ID'),
      ds(),
      str('user_segment', '用户分层', { sampleValues: ['high_value', 'medium_value', 'low_value', 'dormant', 'churned'] }),
      str('membership_level', '会员等级', { sampleValues: ['normal', 'silver', 'gold', 'platinum'] }),
      bigint('user_count', '用户数'),
      dec('avg_order_amount', '平均客单价'),
      dbl('avg_order_frequency', '平均月下单频次'),
      dec('avg_ltv', '平均LTV'),
      dbl('churn_rate', '流失率'),
    ],
  },
  {
    name: 'ads_product_top_seller',
    comment: '热销商品排行指标',
    layer: 'ads',
    domain: 'product',
    columns: [
      pk('id', '主键ID'),
      ds(),
      fk('sku_id', 'dim_product_sku', '商品SKU ID'),
      str('sku_name', 'SKU名称'),
      str('category_name', '品类名称'),
      bigint('sale_qty', '销量'),
      dec('sale_amount', '销售金额'),
      bigint('view_count', '浏览量'),
      dbl('conversion_rate', '转化率'),
      int('rank_position', '排名位置'),
    ],
  },
  {
    name: 'ads_product_category_analysis',
    comment: '品类分析指标表',
    layer: 'ads',
    domain: 'product',
    columns: [
      pk('id', '主键ID'),
      ds(),
      str('category_name', '品类名称'),
      int('category_level', '品类层级'),
      bigint('sku_count', '在售SKU数'),
      dec('gmv_amount', 'GMV金额'),
      bigint('order_count', '订单数'),
      dbl('gmv_share', 'GMV占比'),
      dbl('yoy_growth_rate', '同比增长率'),
    ],
  },
  {
    name: 'ads_risk_overview',
    comment: '风控总览指标',
    layer: 'ads',
    domain: 'risk',
    columns: [
      pk('id', '主键ID'),
      ds(),
      str('risk_type', '风险类型', { sampleValues: ['fraud', 'abnormal_login', 'money_laundering', 'bot_traffic'] }),
      bigint('alert_count', '告警数'),
      bigint('blocked_count', '拦截数'),
      bigint('resolved_count', '已处理数'),
      dec('loss_amount', '损失金额'),
      dec('prevented_amount', '止损金额'),
      dbl('block_rate', '拦截率'),
      dbl('false_positive_rate', '误报率'),
    ],
  },
  {
    name: 'ads_risk_realtime_monitor',
    comment: '风控实时监控指标',
    layer: 'ads',
    domain: 'risk',
    columns: [
      pk('id', '主键ID'),
      ds(),
      str('monitor_item', '监控项', { sampleValues: ['transaction_qps', 'block_rate', 'model_latency', 'rule_hit_rate'] }),
      str('risk_level', '风险等级', { sampleValues: ['low', 'medium', 'high', 'critical'] }),
      dbl('current_value', '当前值'),
      dbl('threshold_value', '阈值'),
      bool('is_alarm', '是否告警'),
      bigint('affected_user_count', '影响用户数'),
      ts('snapshot_time', '快照时间'),
    ],
  },
  {
    name: 'ads_trade_hourly_trend',
    comment: '交易小时趋势指标',
    layer: 'ads',
    domain: 'trade',
    columns: [
      pk('id', '主键ID'),
      ds(),
      int('hour', '小时(0-23)'),
      str('channel', '渠道', { sampleValues: ['app', 'h5', 'mini_program', 'pc'] }),
      dec('gmv_amount', 'GMV金额'),
      bigint('order_count', '订单数'),
      bigint('pay_user_count', '支付用户数'),
      dec('avg_order_amount', '客单价'),
    ],
  },
];

/* ═══════════════════════════════════════════════
 * Metrics — 24 metrics from ADS tables
 * ═══════════════════════════════════════════════ */

const metrics: MetricDef[] = [
  /* ── trade metrics ── */
  {
    name: 'gmv_total',
    displayName: 'GMV 总额',
    expression: 'SUM(gmv_amount)',
    metricType: 'atomic',
    sourceTable: 'ads_trade_gmv_dashboard',
    dimensions: ['ds', 'channel', 'category_name', 'platform'],
    granularity: ['day', 'week', 'month'],
    format: 'currency',
    description: '成交总金额(GMV)',
  },
  {
    name: 'order_count',
    displayName: '订单量',
    expression: 'SUM(order_count)',
    metricType: 'atomic',
    sourceTable: 'ads_trade_gmv_dashboard',
    dimensions: ['ds', 'channel', 'platform'],
    granularity: ['day', 'week', 'month'],
    format: 'number',
    description: '总订单数',
  },
  {
    name: 'avg_order_amount',
    displayName: '客单价',
    expression: 'SUM(gmv_amount) / SUM(order_count)',
    metricType: 'derived',
    sourceTable: 'ads_trade_gmv_dashboard',
    dimensions: ['ds', 'channel', 'category_name'],
    granularity: ['day', 'week', 'month'],
    format: 'currency',
    description: '平均每笔订单金额',
  },
  {
    name: 'pay_user_count',
    displayName: '支付用户数',
    expression: 'SUM(pay_user_count)',
    metricType: 'atomic',
    sourceTable: 'ads_trade_gmv_dashboard',
    dimensions: ['ds', 'channel', 'platform'],
    granularity: ['day', 'week', 'month'],
    format: 'number',
    description: '完成支付的独立用户数',
  },
  {
    name: 'pay_conversion_rate',
    displayName: '支付转化率',
    expression: 'SUM(pay_success_count) / SUM(uv_count)',
    metricType: 'derived',
    sourceTable: 'ads_trade_conversion_funnel',
    dimensions: ['ds', 'channel', 'platform'],
    granularity: ['day', 'week'],
    format: 'percentage',
    description: '从页面UV到支付成功的整体转化率',
  },
  {
    name: 'view_to_cart_rate',
    displayName: '浏览加购率',
    expression: 'SUM(cart_add_count) / SUM(product_view_count)',
    metricType: 'derived',
    sourceTable: 'ads_trade_conversion_funnel',
    dimensions: ['ds', 'channel', 'platform'],
    granularity: ['day', 'week'],
    format: 'percentage',
    description: '商品浏览到加购的转化率',
  },
  {
    name: 'merchant_gmv',
    displayName: '商家GMV',
    expression: 'SUM(gmv_amount)',
    metricType: 'atomic',
    sourceTable: 'ads_trade_merchant_rank',
    dimensions: ['ds', 'merchant_name'],
    granularity: ['day', 'week', 'month'],
    format: 'currency',
    description: '按商家维度的GMV',
  },
  {
    name: 'hourly_gmv',
    displayName: '小时GMV趋势',
    expression: 'SUM(gmv_amount)',
    metricType: 'atomic',
    sourceTable: 'ads_trade_hourly_trend',
    dimensions: ['ds', 'hour', 'channel'],
    granularity: ['hour', 'day'],
    format: 'currency',
    description: '按小时维度的GMV趋势',
  },

  /* ── user metrics ── */
  {
    name: 'dau',
    displayName: '日活用户数',
    expression: 'SUM(dau)',
    metricType: 'atomic',
    sourceTable: 'ads_user_growth_dashboard',
    dimensions: ['ds', 'channel', 'platform'],
    granularity: ['day'],
    format: 'number',
    description: '每日活跃用户数(DAU)',
  },
  {
    name: 'mau',
    displayName: '月活用户数',
    expression: 'SUM(mau)',
    metricType: 'atomic',
    sourceTable: 'ads_user_growth_dashboard',
    dimensions: ['ds', 'channel', 'platform'],
    granularity: ['month'],
    format: 'number',
    description: '月度活跃用户数(MAU)',
  },
  {
    name: 'new_user_count',
    displayName: '新增用户数',
    expression: 'SUM(new_user_count)',
    metricType: 'atomic',
    sourceTable: 'ads_user_growth_dashboard',
    dimensions: ['ds', 'channel', 'platform'],
    granularity: ['day', 'week', 'month'],
    format: 'number',
    description: '新注册用户数',
  },
  {
    name: 'd1_retention_rate',
    displayName: '次日留存率',
    expression: 'AVG(d1_retention_rate)',
    metricType: 'atomic',
    sourceTable: 'ads_user_growth_dashboard',
    dimensions: ['ds', 'channel', 'platform'],
    granularity: ['day'],
    format: 'percentage',
    description: '新用户次日留存率',
  },
  {
    name: 'd7_retention_rate',
    displayName: '7日留存率',
    expression: 'AVG(d7_retention_rate)',
    metricType: 'atomic',
    sourceTable: 'ads_user_growth_dashboard',
    dimensions: ['ds', 'channel'],
    granularity: ['day', 'week'],
    format: 'percentage',
    description: '新用户7日留存率',
  },
  {
    name: 'd30_retention_rate',
    displayName: '30日留存率',
    expression: 'AVG(d30_retention_rate)',
    metricType: 'atomic',
    sourceTable: 'ads_user_growth_dashboard',
    dimensions: ['ds', 'channel'],
    granularity: ['month'],
    format: 'percentage',
    description: '新用户30日留存率',
  },
  {
    name: 'user_segment_count',
    displayName: '分层用户数',
    expression: 'SUM(user_count)',
    metricType: 'atomic',
    sourceTable: 'ads_user_segment_profile',
    dimensions: ['ds', 'user_segment', 'membership_level'],
    granularity: ['day', 'month'],
    format: 'number',
    description: '各用户分层下的用户数量',
  },
  {
    name: 'avg_ltv',
    displayName: '平均用户LTV',
    expression: 'AVG(avg_ltv)',
    metricType: 'atomic',
    sourceTable: 'ads_user_segment_profile',
    dimensions: ['ds', 'user_segment'],
    granularity: ['month'],
    format: 'currency',
    description: '用户平均生命周期价值',
  },
  {
    name: 'churn_rate',
    displayName: '用户流失率',
    expression: 'AVG(churn_rate)',
    metricType: 'atomic',
    sourceTable: 'ads_user_segment_profile',
    dimensions: ['ds', 'user_segment'],
    granularity: ['month'],
    format: 'percentage',
    description: '用户流失率',
  },

  /* ── product metrics ── */
  {
    name: 'top_sku_sales',
    displayName: '热销SKU销量',
    expression: 'SUM(sale_qty)',
    metricType: 'atomic',
    sourceTable: 'ads_product_top_seller',
    dimensions: ['ds', 'category_name'],
    granularity: ['day', 'week', 'month'],
    format: 'number',
    description: '热销商品总销量',
  },
  {
    name: 'product_conversion_rate',
    displayName: '商品转化率',
    expression: 'AVG(conversion_rate)',
    metricType: 'atomic',
    sourceTable: 'ads_product_top_seller',
    dimensions: ['ds', 'category_name'],
    granularity: ['day', 'week'],
    format: 'percentage',
    description: '商品浏览到下单的转化率',
  },
  {
    name: 'category_gmv',
    displayName: '品类GMV',
    expression: 'SUM(gmv_amount)',
    metricType: 'atomic',
    sourceTable: 'ads_product_category_analysis',
    dimensions: ['ds', 'category_name', 'category_level'],
    granularity: ['day', 'week', 'month'],
    format: 'currency',
    description: '按品类维度的GMV',
  },
  {
    name: 'category_yoy_growth',
    displayName: '品类同比增长率',
    expression: 'AVG(yoy_growth_rate)',
    metricType: 'atomic',
    sourceTable: 'ads_product_category_analysis',
    dimensions: ['ds', 'category_name'],
    granularity: ['month'],
    format: 'percentage',
    description: '品类GMV同比增长率',
  },

  /* ── risk metrics ── */
  {
    name: 'risk_alert_count',
    displayName: '风控告警数',
    expression: 'SUM(alert_count)',
    metricType: 'atomic',
    sourceTable: 'ads_risk_overview',
    dimensions: ['ds', 'risk_type'],
    granularity: ['day', 'week'],
    format: 'number',
    description: '风控告警总数',
  },
  {
    name: 'risk_block_rate',
    displayName: '风控拦截率',
    expression: 'SUM(blocked_count) / SUM(alert_count)',
    metricType: 'derived',
    sourceTable: 'ads_risk_overview',
    dimensions: ['ds', 'risk_type'],
    granularity: ['day', 'week'],
    format: 'percentage',
    description: '告警事件拦截率',
  },
  {
    name: 'risk_prevented_amount',
    displayName: '风控止损金额',
    expression: 'SUM(prevented_amount)',
    metricType: 'atomic',
    sourceTable: 'ads_risk_overview',
    dimensions: ['ds', 'risk_type'],
    granularity: ['day', 'week', 'month'],
    format: 'currency',
    description: '风控系统止损总金额',
  },
];

/* ═══════════════════════════════════════════════
 * Glossary — 10 business terms
 * ═══════════════════════════════════════════════ */

const glossary: GlossaryDef[] = [
  {
    term: '活跃用户',
    sqlExpression: "COUNT(DISTINCT user_id) WHERE last_active_date >= CURRENT_DATE - INTERVAL '30' DAY",
    description: '最近30天有登录行为的用户',
  },
  {
    term: 'GMV',
    sqlExpression: "SUM(gmv_amount) FROM ads_trade_gmv_dashboard WHERE ds = '${target_date}'",
    description: '成交总额(Gross Merchandise Volume)，含未付款订单',
  },
  {
    term: '客单价',
    sqlExpression: 'SUM(gmv_amount) / COUNT(DISTINCT order_id)',
    description: '平均每笔订单金额，反映用户消费能力',
  },
  {
    term: '次日留存率',
    sqlExpression: 'COUNT(DISTINCT d1_user) / COUNT(DISTINCT new_user) * 100',
    description: '新用户注册次日再次登录的比例',
  },
  {
    term: '支付转化率',
    sqlExpression: 'COUNT(DISTINCT pay_user) / COUNT(DISTINCT visit_user) * 100',
    description: '访问用户中完成支付的比例',
  },
  {
    term: '动销率',
    sqlExpression: 'COUNT(DISTINCT CASE WHEN sale_qty > 0 THEN sku_id END) / COUNT(DISTINCT sku_id) * 100',
    description: '有销量的SKU占总在售SKU的比例',
  },
  {
    term: '退款率',
    sqlExpression: 'SUM(refund_amount) / SUM(pay_amount) * 100',
    description: '退款金额占支付金额的比例',
  },
  {
    term: '用户LTV',
    sqlExpression: "SUM(pay_amount) FROM dwd_trade_payment_di WHERE user_id = ? AND pay_status = 'success'",
    description: '用户生命周期价值(Life-Time Value)，用户历史累计付费金额',
  },
  {
    term: '风控拦截率',
    sqlExpression: 'SUM(blocked_count) / SUM(alert_count) * 100',
    description: '风控系统告警后成功拦截的比例',
  },
  {
    term: '库存周转率',
    sqlExpression: 'SUM(outbound_qty) / AVG(stock_qty)',
    description: '一定周期内库存出库量与平均库存的比值，反映库存流转效率',
  },
];

/* ═══════════════════════════════════════════════
 * Export
 * ═══════════════════════════════════════════════ */

export const hiveSeed: EngineSeedDefinition = {
  engineType: 'hive',
  name: 'Hive 离线数仓',
  description: '基于 Hive 的离线数据仓库，承载 DWD/DWS 核心明细和汇总层数据',
  dialect: 'hive',
  pgSchema: 'dw_hive',
  tables: [...dwdTables, ...dwsTables, ...dimTables, ...adsTables],
  metrics,
  glossary,
};
