import type { EngineSeedDefinition, TableDef, MetricDef, GlossaryDef } from './types.js';

/* ========================================================================== */
/*  Helper — keep column definitions concise                                   */
/* ========================================================================== */

type Col = TableDef['columns'][number];

const pk = (comment: string): Col => ({
  name: 'id',
  dataType: 'BIGINT',
  comment,
  isPrimaryKey: true,
});

const fk = (name: string, refTable: string, comment: string, refCol = 'id'): Col => ({
  name,
  dataType: 'BIGINT',
  comment,
  isNullable: false,
  referencesTable: refTable,
  referencesColumn: refCol,
});

const str = (name: string, comment: string, opts: Partial<Col> = {}): Col => ({
  name,
  dataType: 'STRING',
  comment,
  ...opts,
});

const bigint = (name: string, comment: string, opts: Partial<Col> = {}): Col => ({
  name,
  dataType: 'BIGINT',
  comment,
  ...opts,
});

const int = (name: string, comment: string): Col => ({
  name,
  dataType: 'INT',
  comment,
});

const dec = (name: string, comment: string): Col => ({
  name,
  dataType: 'DECIMAL(18,2)',
  comment,
});

const ts = (name: string, comment: string): Col => ({
  name,
  dataType: 'TIMESTAMP',
  comment,
});

const dbl = (name: string, comment: string): Col => ({
  name,
  dataType: 'DOUBLE',
  comment,
});

const bool = (name: string, comment: string): Col => ({
  name,
  dataType: 'BOOLEAN',
  comment,
});

const dt = (name: string, comment: string): Col => ({
  name,
  dataType: 'DATE',
  comment,
});

/** Partition date column — almost every Iceberg table uses this */
const ds: Col = { name: 'ds', dataType: 'DATE', comment: '数据分区日期', isNullable: false };
const etl: Col = { name: 'etl_time', dataType: 'TIMESTAMP', comment: 'ETL 处理时间' };

/* ========================================================================== */
/*  DWD Layer — 25 tables (core detail facts with time-travel snapshots)       */
/* ========================================================================== */

const dwdTables: TableDef[] = [
  /* ---- trade domain ---- */
  {
    name: 'dwd_trade_order_di',
    comment: '交易订单明细表（日增量）',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      pk('订单ID'),
      str('order_no', '订单编号', { isNullable: false }),
      fk('user_id', 'dim_user_tag', '买家用户ID'),
      fk('product_id', 'dim_product_brand', '商品ID'),
      str('order_type', '订单类型: normal/pre_sale/group_buy'),
      str('channel', '下单渠道: app/web/h5/mini_program'),
      dec('order_amount', '订单金额'),
      dec('discount_amount', '优惠金额'),
      dec('pay_amount', '实付金额'),
      int('item_count', '商品件数'),
      str('currency', '币种'),
      str('status', '订单状态: created/paid/shipped/completed/cancelled'),
      ts('order_time', '下单时间'),
      ds, etl,
    ],
  },
  {
    name: 'dwd_trade_settlement_di',
    comment: '交易结算明细表（日增量）',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      pk('结算ID'),
      str('settle_no', '结算单号', { isNullable: false }),
      fk('order_id', 'dwd_trade_order_di', '关联订单ID'),
      fk('merchant_id', 'dim_merchant', '商户ID'),
      str('settle_type', '结算类型: t0/t1/t7'),
      dec('settle_amount', '结算金额'),
      dec('commission_amount', '佣金金额'),
      dec('tax_amount', '税费'),
      str('currency', '币种'),
      str('status', '结算状态: pending/processing/completed/failed'),
      ts('settle_time', '结算时间'),
      ds, etl,
    ],
  },
  {
    name: 'dwd_trade_payment_di',
    comment: '支付流水明细表（日增量）',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      pk('支付ID'),
      str('pay_no', '支付单号', { isNullable: false }),
      fk('order_id', 'dwd_trade_order_di', '关联订单ID'),
      fk('user_id', 'dim_user_tag', '付款用户ID'),
      str('pay_method', '支付方式: alipay/wechat/card/balance'),
      dec('pay_amount', '支付金额'),
      str('currency', '币种'),
      str('status', '支付状态: init/success/fail/refund'),
      ts('pay_time', '支付时间'),
      str('third_party_no', '第三方流水号'),
      ds, etl,
    ],
  },
  {
    name: 'dwd_trade_refund_di',
    comment: '退款明细表（日增量）',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      pk('退款ID'),
      str('refund_no', '退款单号', { isNullable: false }),
      fk('order_id', 'dwd_trade_order_di', '原订单ID'),
      fk('user_id', 'dim_user_tag', '退款用户ID'),
      str('refund_reason', '退款原因'),
      dec('refund_amount', '退款金额'),
      str('status', '退款状态: applied/approved/completed/rejected'),
      ts('apply_time', '申请时间'),
      ts('complete_time', '完成时间'),
      ds, etl,
    ],
  },
  {
    name: 'dwd_trade_logistics_di',
    comment: '物流轨迹明细表（日增量）',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      pk('物流ID'),
      fk('order_id', 'dwd_trade_order_di', '关联订单ID'),
      str('tracking_no', '物流单号', { isNullable: false }),
      str('carrier', '物流公司'),
      str('status', '物流状态: picked/in_transit/delivered/returned'),
      str('current_city', '当前所在城市'),
      ts('ship_time', '发货时间'),
      ts('deliver_time', '签收时间'),
      int('transit_days', '运输天数'),
      ds, etl,
    ],
  },
  {
    name: 'dwd_trade_cart_di',
    comment: '购物车事件明细表（日增量）',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      pk('事件ID'),
      fk('user_id', 'dim_user_tag', '用户ID'),
      fk('product_id', 'dim_product_brand', '商品ID'),
      str('action', '操作: add/remove/update_qty'),
      int('quantity', '数量'),
      dec('unit_price', '单价'),
      str('source', '来源页面'),
      ts('event_time', '事件时间'),
      ds, etl,
    ],
  },
  /* ---- user domain ---- */
  {
    name: 'dwd_user_event_di',
    comment: '用户行为事件明细表（日增量）',
    layer: 'dwd',
    domain: 'user',
    columns: [
      pk('事件ID'),
      fk('user_id', 'dim_user_tag', '用户ID'),
      str('event_type', '事件类型: page_view/click/scroll/search/share'),
      str('page_id', '页面标识'),
      str('element_id', '元素标识'),
      str('device_type', '设备类型: ios/android/web'),
      str('os_version', '系统版本'),
      str('app_version', 'App 版本'),
      str('ip', '客户端IP', { isPii: true }),
      ts('event_time', '事件时间'),
      bigint('duration_ms', '停留时长（毫秒）'),
      ds, etl,
    ],
  },
  {
    name: 'dwd_user_login_di',
    comment: '用户登录明细表（日增量）',
    layer: 'dwd',
    domain: 'user',
    columns: [
      pk('登录ID'),
      fk('user_id', 'dim_user_tag', '用户ID'),
      str('login_method', '登录方式: password/sms/wechat/apple'),
      str('device_id', '设备标识'),
      str('device_model', '设备型号'),
      str('ip', '登录IP', { isPii: true }),
      str('city', '登录城市'),
      bool('is_new_device', '是否新设备'),
      ts('login_time', '登录时间'),
      ds, etl,
    ],
  },
  {
    name: 'dwd_user_register_di',
    comment: '用户注册明细表（日增量）',
    layer: 'dwd',
    domain: 'user',
    columns: [
      pk('注册ID'),
      fk('user_id', 'dim_user_tag', '用户ID'),
      str('register_channel', '注册渠道: organic/paid/referral'),
      str('register_source', '注册来源: app_store/web/share_link'),
      str('device_type', '设备类型'),
      str('invite_code', '邀请码'),
      ts('register_time', '注册时间'),
      ds, etl,
    ],
  },
  {
    name: 'dwd_user_profile_change_di',
    comment: '用户资料变更明细表（日增量）',
    layer: 'dwd',
    domain: 'user',
    columns: [
      pk('变更ID'),
      fk('user_id', 'dim_user_tag', '用户ID'),
      str('field_name', '变更字段: nickname/avatar/phone/email'),
      str('old_value', '变更前值', { isPii: true }),
      str('new_value', '变更后值', { isPii: true }),
      str('change_source', '变更来源: user/admin/system'),
      ts('change_time', '变更时间'),
      ds, etl,
    ],
  },
  {
    name: 'dwd_user_feedback_di',
    comment: '用户反馈明细表（日增量）',
    layer: 'dwd',
    domain: 'user',
    columns: [
      pk('反馈ID'),
      fk('user_id', 'dim_user_tag', '用户ID'),
      str('feedback_type', '反馈类型: bug/suggestion/complaint/praise'),
      str('content', '反馈内容'),
      str('category', '反馈分类'),
      int('rating', '评分 1-5'),
      str('status', '处理状态: pending/processing/resolved/closed'),
      ts('submit_time', '提交时间'),
      ds, etl,
    ],
  },
  {
    name: 'dwd_user_session_di',
    comment: '用户会话明细表（日增量）',
    layer: 'dwd',
    domain: 'user',
    columns: [
      pk('会话ID'),
      fk('user_id', 'dim_user_tag', '用户ID'),
      str('session_id', '会话标识', { isNullable: false }),
      str('device_type', '设备类型'),
      bigint('duration_sec', '会话时长（秒）'),
      int('page_count', '浏览页面数'),
      int('event_count', '事件数'),
      str('entry_page', '入口页面'),
      str('exit_page', '退出页面'),
      ts('start_time', '会话开始时间'),
      ts('end_time', '会话结束时间'),
      ds, etl,
    ],
  },
  /* ---- product domain ---- */
  {
    name: 'dwd_product_click_di',
    comment: '商品点击明细表（日增量）',
    layer: 'dwd',
    domain: 'product',
    columns: [
      pk('点击ID'),
      fk('user_id', 'dim_user_tag', '用户ID'),
      fk('product_id', 'dim_product_brand', '商品ID'),
      str('scene', '曝光场景: search/recommend/category/promotion'),
      int('position', '展示位置'),
      str('device_type', '设备类型'),
      ts('click_time', '点击时间'),
      str('referrer', '来源页'),
      ds, etl,
    ],
  },
  {
    name: 'dwd_product_exposure_di',
    comment: '商品曝光明细表（日增量）',
    layer: 'dwd',
    domain: 'product',
    columns: [
      pk('曝光ID'),
      fk('user_id', 'dim_user_tag', '用户ID'),
      fk('product_id', 'dim_product_brand', '商品ID'),
      str('scene', '曝光场景: search/recommend/category/ad'),
      int('position', '展示位置'),
      bigint('stay_ms', '可见停留毫秒'),
      bool('is_visible', '是否有效曝光'),
      ts('exposure_time', '曝光时间'),
      ds, etl,
    ],
  },
  {
    name: 'dwd_product_review_di',
    comment: '商品评价明细表（日增量）',
    layer: 'dwd',
    domain: 'product',
    columns: [
      pk('评价ID'),
      fk('user_id', 'dim_user_tag', '评价用户ID'),
      fk('product_id', 'dim_product_brand', '商品ID'),
      fk('order_id', 'dwd_trade_order_di', '关联订单ID'),
      int('rating', '评分 1-5'),
      str('content', '评价内容'),
      int('image_count', '图片数'),
      bool('is_top', '是否置顶'),
      str('sentiment', '情感标签: positive/neutral/negative'),
      ts('review_time', '评价时间'),
      ds, etl,
    ],
  },
  {
    name: 'dwd_product_collect_di',
    comment: '商品收藏明细表（日增量）',
    layer: 'dwd',
    domain: 'product',
    columns: [
      pk('收藏ID'),
      fk('user_id', 'dim_user_tag', '用户ID'),
      fk('product_id', 'dim_product_brand', '商品ID'),
      str('action', '操作: collect/cancel'),
      str('source', '来源: detail_page/list/recommendation'),
      ts('action_time', '操作时间'),
      ds, etl,
    ],
  },
  {
    name: 'dwd_product_price_change_di',
    comment: '商品价格变动明细表（日增量）',
    layer: 'dwd',
    domain: 'product',
    columns: [
      pk('变动ID'),
      fk('product_id', 'dim_product_brand', '商品ID'),
      dec('old_price', '变动前价格'),
      dec('new_price', '变动后价格'),
      dbl('change_ratio', '变动比例'),
      str('reason', '调价原因: promotion/cost/competitor/clearance'),
      str('operator', '操作人'),
      ts('change_time', '变动时间'),
      ds, etl,
    ],
  },
  /* ---- risk domain ---- */
  {
    name: 'dwd_risk_transaction_di',
    comment: '风控交易检测明细表（日增量）',
    layer: 'dwd',
    domain: 'risk',
    columns: [
      pk('检测ID'),
      fk('order_id', 'dwd_trade_order_di', '关联订单ID'),
      fk('user_id', 'dim_user_tag', '用户ID'),
      str('rule_code', '触发规则编码'),
      str('risk_level', '风险等级: low/medium/high/critical'),
      dbl('risk_score', '风险评分 0-100'),
      str('action', '处置动作: pass/review/block/freeze'),
      str('hit_detail', '命中明细 JSON'),
      ts('detect_time', '检测时间'),
      ds, etl,
    ],
  },
  {
    name: 'dwd_risk_login_audit_di',
    comment: '登录风控审计明细表（日增量）',
    layer: 'dwd',
    domain: 'risk',
    columns: [
      pk('审计ID'),
      fk('user_id', 'dim_user_tag', '用户ID'),
      str('ip', '登录IP', { isPii: true }),
      str('device_fingerprint', '设备指纹'),
      str('geo_location', '地理位置'),
      dbl('risk_score', '风险评分'),
      str('risk_label', '风险标签: normal/suspicious/blocked'),
      bool('is_proxy', '是否代理IP'),
      bool('is_new_device', '是否新设备'),
      ts('login_time', '登录时间'),
      ds, etl,
    ],
  },
  {
    name: 'dwd_risk_rule_hit_di',
    comment: '风控规则命中明细表（日增量）',
    layer: 'dwd',
    domain: 'risk',
    columns: [
      pk('命中ID'),
      str('rule_id', '规则ID'),
      str('rule_name', '规则名称'),
      str('scene', '风控场景: payment/login/register/withdraw'),
      fk('user_id', 'dim_user_tag', '关联用户ID'),
      str('entity_type', '实体类型: order/user/device/ip'),
      str('entity_id', '实体ID'),
      dbl('score', '规则得分'),
      str('action', '处置动作: alert/block/freeze'),
      ts('hit_time', '命中时间'),
      ds, etl,
    ],
  },
  {
    name: 'dwd_risk_blacklist_di',
    comment: '黑名单变更明细表（日增量）',
    layer: 'dwd',
    domain: 'risk',
    columns: [
      pk('记录ID'),
      str('list_type', '名单类型: user/device/ip/phone'),
      str('list_value', '名单值', { isPii: true }),
      str('reason', '加入原因'),
      str('source', '来源: rule/manual/external'),
      str('action', '操作: add/remove'),
      str('operator', '操作人'),
      ts('effective_time', '生效时间'),
      ts('expire_time', '过期时间'),
      ds, etl,
    ],
  },
  {
    name: 'dwd_risk_fraud_case_di',
    comment: '欺诈案件明细表（日增量）',
    layer: 'dwd',
    domain: 'risk',
    columns: [
      pk('案件ID'),
      str('case_no', '案件编号', { isNullable: false }),
      fk('user_id', 'dim_user_tag', '涉案用户ID'),
      str('fraud_type', '欺诈类型: account_takeover/fake_order/money_laundering/promotion_abuse'),
      dec('loss_amount', '损失金额'),
      dec('recovered_amount', '追回金额'),
      str('status', '案件状态: investigating/confirmed/closed'),
      str('handler', '处理人'),
      ts('report_time', '上报时间'),
      ts('close_time', '结案时间'),
      ds, etl,
    ],
  },
  {
    name: 'dwd_risk_device_fingerprint_di',
    comment: '设备指纹采集明细表（日增量）',
    layer: 'dwd',
    domain: 'risk',
    columns: [
      pk('采集ID'),
      fk('user_id', 'dim_user_tag', '关联用户ID'),
      str('device_id', '设备唯一标识'),
      str('device_model', '设备型号'),
      str('os', '操作系统: ios/android/windows/macos'),
      str('os_version', '系统版本'),
      str('browser', '浏览器'),
      str('screen_resolution', '屏幕分辨率'),
      str('ip', '采集IP', { isPii: true }),
      bool('is_emulator', '是否模拟器'),
      bool('is_rooted', '是否 Root/越狱'),
      ts('collect_time', '采集时间'),
      ds, etl,
    ],
  },
  {
    name: 'dwd_trade_coupon_usage_di',
    comment: '优惠券使用明细表（日增量）',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      pk('使用ID'),
      fk('order_id', 'dwd_trade_order_di', '关联订单ID'),
      fk('user_id', 'dim_user_tag', '使用用户ID'),
      str('coupon_id', '优惠券ID'),
      str('coupon_type', '券类型: full_reduction/discount/cashback'),
      dec('face_value', '面值'),
      dec('actual_deduction', '实际抵扣'),
      ts('use_time', '使用时间'),
      ds, etl,
    ],
  },
  {
    name: 'dwd_user_search_di',
    comment: '用户搜索明细表（日增量）',
    layer: 'dwd',
    domain: 'user',
    columns: [
      pk('搜索ID'),
      fk('user_id', 'dim_user_tag', '用户ID'),
      str('keyword', '搜索关键词'),
      int('result_count', '结果数量'),
      str('category_filter', '分类筛选'),
      str('sort_type', '排序方式: relevance/price_asc/price_desc/sales'),
      bool('has_click', '是否有点击'),
      ts('search_time', '搜索时间'),
      ds, etl,
    ],
  },
];

/* ========================================================================== */
/*  DWS Layer — 15 tables (pre-aggregated summaries)                           */
/* ========================================================================== */

const dwsTables: TableDef[] = [
  {
    name: 'dws_trade_daily_summary',
    comment: '交易日汇总表',
    layer: 'dws',
    domain: 'trade',
    columns: [
      pk('汇总ID'),
      ds,
      str('channel', '渠道'),
      str('order_type', '订单类型'),
      bigint('order_count', '订单数'),
      dec('gmv', 'GMV 总额'),
      dec('pay_amount', '实付总额'),
      dec('refund_amount', '退款总额'),
      bigint('pay_user_count', '付费用户数'),
      dbl('avg_order_value', '客单价'),
      dbl('pay_rate', '支付转化率'),
      etl,
    ],
  },
  {
    name: 'dws_trade_merchant_daily',
    comment: '商户交易日汇总表',
    layer: 'dws',
    domain: 'trade',
    columns: [
      pk('汇总ID'),
      ds,
      fk('merchant_id', 'dim_merchant', '商户ID'),
      bigint('order_count', '订单数'),
      dec('gmv', 'GMV'),
      dec('settle_amount', '结算金额'),
      dec('commission', '佣金'),
      bigint('buyer_count', '买家数'),
      dbl('refund_rate', '退款率'),
      etl,
    ],
  },
  {
    name: 'dws_trade_category_daily',
    comment: '品类交易日汇总表',
    layer: 'dws',
    domain: 'trade',
    columns: [
      pk('汇总ID'),
      ds,
      str('category_l1', '一级品类'),
      str('category_l2', '二级品类'),
      bigint('order_count', '订单数'),
      dec('gmv', 'GMV'),
      bigint('product_count', '动销商品数'),
      bigint('buyer_count', '买家数'),
      dbl('avg_price', '均价'),
      etl,
    ],
  },
  {
    name: 'dws_user_active_daily',
    comment: '用户活跃日汇总表',
    layer: 'dws',
    domain: 'user',
    columns: [
      pk('汇总ID'),
      ds,
      str('platform', '平台: ios/android/web'),
      bigint('dau', '日活用户数'),
      bigint('new_user_count', '新增用户数'),
      bigint('login_count', '登录次数'),
      dbl('avg_session_duration', '平均会话时长（秒）'),
      dbl('avg_page_views', '平均浏览页数'),
      bigint('bounce_count', '跳出用户数'),
      etl,
    ],
  },
  {
    name: 'dws_user_cohort_7d',
    comment: '用户7日留存分群表',
    layer: 'dws',
    domain: 'user',
    columns: [
      pk('分群ID'),
      dt('cohort_date', '注册日期'),
      str('register_channel', '注册渠道'),
      bigint('cohort_size', '分群人数'),
      bigint('day1_retained', '次日留存人数'),
      bigint('day3_retained', '3日留存人数'),
      bigint('day7_retained', '7日留存人数'),
      dbl('day1_rate', '次日留存率'),
      dbl('day7_rate', '7日留存率'),
      etl,
    ],
  },
  {
    name: 'dws_user_lifecycle_daily',
    comment: '用户生命周期日汇总表',
    layer: 'dws',
    domain: 'user',
    columns: [
      pk('汇总ID'),
      ds,
      str('lifecycle_stage', '生命周期: new/active/dormant/lost/reactivated'),
      bigint('user_count', '用户数'),
      bigint('transition_in', '流入人数'),
      bigint('transition_out', '流出人数'),
      dbl('avg_lifetime_days', '平均生命周期天数'),
      etl,
    ],
  },
  {
    name: 'dws_product_conversion_1d',
    comment: '商品转化日汇总表',
    layer: 'dws',
    domain: 'product',
    columns: [
      pk('汇总ID'),
      ds,
      fk('product_id', 'dim_product_brand', '商品ID'),
      bigint('exposure_count', '曝光次数'),
      bigint('click_count', '点击次数'),
      bigint('cart_count', '加购次数'),
      bigint('order_count', '下单次数'),
      dbl('click_rate', '点击率'),
      dbl('cart_rate', '加购率'),
      dbl('order_rate', '下单转化率'),
      etl,
    ],
  },
  {
    name: 'dws_product_review_daily',
    comment: '商品评价日汇总表',
    layer: 'dws',
    domain: 'product',
    columns: [
      pk('汇总ID'),
      ds,
      fk('product_id', 'dim_product_brand', '商品ID'),
      bigint('review_count', '评价数'),
      dbl('avg_rating', '平均评分'),
      bigint('positive_count', '好评数'),
      bigint('negative_count', '差评数'),
      dbl('positive_rate', '好评率'),
      etl,
    ],
  },
  {
    name: 'dws_product_inventory_daily',
    comment: '商品库存日快照表',
    layer: 'dws',
    domain: 'product',
    columns: [
      pk('快照ID'),
      ds,
      fk('product_id', 'dim_product_brand', '商品ID'),
      bigint('stock_qty', '库存数量'),
      bigint('locked_qty', '锁定数量'),
      bigint('available_qty', '可用数量'),
      bigint('inbound_qty', '入库数量'),
      bigint('outbound_qty', '出库数量'),
      int('turnover_days', '库存周转天数'),
      etl,
    ],
  },
  {
    name: 'dws_risk_alert_daily',
    comment: '风控告警日汇总表',
    layer: 'dws',
    domain: 'risk',
    columns: [
      pk('汇总ID'),
      ds,
      str('risk_scene', '风控场景'),
      str('risk_level', '风险等级'),
      bigint('alert_count', '告警数'),
      bigint('block_count', '拦截数'),
      bigint('review_count', '人工审核数'),
      dbl('block_rate', '拦截率'),
      dec('loss_prevented', '预防损失金额'),
      etl,
    ],
  },
  {
    name: 'dws_risk_user_score_daily',
    comment: '用户风险评分日快照表',
    layer: 'dws',
    domain: 'risk',
    columns: [
      pk('快照ID'),
      ds,
      fk('user_id', 'dim_user_tag', '用户ID'),
      dbl('credit_score', '信用评分'),
      dbl('fraud_score', '欺诈评分'),
      int('hit_rule_count', '命中规则数'),
      str('risk_tier', '风险分层: safe/watch/danger'),
      ts('last_alert_time', '最近告警时间'),
      etl,
    ],
  },
  {
    name: 'dws_trade_hourly_trend',
    comment: '交易小时级趋势表',
    layer: 'dws',
    domain: 'trade',
    columns: [
      pk('趋势ID'),
      ds,
      int('hour', '小时 0-23'),
      bigint('order_count', '订单数'),
      dec('gmv', 'GMV'),
      bigint('pay_count', '支付笔数'),
      dbl('avg_pay_time_sec', '平均支付耗时（秒）'),
      etl,
    ],
  },
  {
    name: 'dws_user_retention_monthly',
    comment: '用户月留存汇总表',
    layer: 'dws',
    domain: 'user',
    columns: [
      pk('汇总ID'),
      str('month', '月份 yyyy-MM'),
      str('register_month', '注册月份'),
      bigint('cohort_size', '注册人数'),
      bigint('retained_count', '留存人数'),
      dbl('retention_rate', '留存率'),
      dbl('avg_orders', '平均下单数'),
      dec('avg_arpu', '平均 ARPU'),
      etl,
    ],
  },
  {
    name: 'dws_product_search_daily',
    comment: '商品搜索日汇总表',
    layer: 'dws',
    domain: 'product',
    columns: [
      pk('汇总ID'),
      ds,
      str('keyword', '搜索词'),
      bigint('search_count', '搜索次数'),
      bigint('click_count', '点击次数'),
      bigint('order_count', '成交笔数'),
      dbl('ctr', '搜索点击率'),
      dbl('cvr', '搜索转化率'),
      etl,
    ],
  },
  {
    name: 'dws_risk_case_monthly',
    comment: '风控案件月汇总表',
    layer: 'dws',
    domain: 'risk',
    columns: [
      pk('汇总ID'),
      str('month', '月份 yyyy-MM'),
      str('fraud_type', '欺诈类型'),
      bigint('case_count', '案件数'),
      dec('total_loss', '总损失'),
      dec('total_recovered', '总追回'),
      dbl('recovery_rate', '追回率'),
      bigint('affected_users', '受影响用户数'),
      etl,
    ],
  },
];

/* ========================================================================== */
/*  DIM Layer — 8 tables (slowly changing dimensions)                          */
/* ========================================================================== */

const dimTables: TableDef[] = [
  {
    name: 'dim_date',
    comment: '日期维度表',
    layer: 'dim',
    domain: 'trade',
    columns: [
      pk('日期ID'),
      dt('date_value', '日期'),
      int('year', '年份'),
      int('quarter', '季度'),
      int('month', '月份'),
      int('week_of_year', '年内周数'),
      int('day_of_week', '星期几 1=周一'),
      bool('is_weekend', '是否周末'),
      bool('is_holiday', '是否节假日'),
      str('holiday_name', '节假日名称'),
      str('fiscal_year', '财年'),
      str('fiscal_quarter', '财季'),
    ],
  },
  {
    name: 'dim_user_tag',
    comment: '用户标签维度表（SCD2）',
    layer: 'dim',
    domain: 'user',
    columns: [
      pk('用户ID'),
      str('user_name', '用户名'),
      str('phone', '手机号', { isPii: true }),
      str('gender', '性别: M/F/unknown'),
      str('age_group', '年龄段: 18-24/25-34/35-44/45+'),
      str('city', '城市'),
      str('province', '省份'),
      str('member_level', '会员等级: bronze/silver/gold/platinum/diamond'),
      str('lifecycle_stage', '生命周期: new/active/dormant/lost'),
      dt('first_order_date', '首购日期'),
      ts('valid_from', 'SCD2 生效时间'),
      ts('valid_to', 'SCD2 失效时间'),
      bool('is_current', '是否当前有效记录'),
    ],
  },
  {
    name: 'dim_product_brand',
    comment: '商品品牌维度表',
    layer: 'dim',
    domain: 'product',
    columns: [
      pk('商品ID'),
      str('product_name', '商品名称'),
      str('spu_id', 'SPU 编码'),
      str('brand_name', '品牌名称'),
      str('category_l1', '一级品类'),
      str('category_l2', '二级品类'),
      str('category_l3', '三级品类'),
      dec('price', '标价'),
      str('status', '商品状态: on_sale/off_shelf/deleted'),
      ts('online_time', '上架时间'),
    ],
  },
  {
    name: 'dim_merchant',
    comment: '商户维度表',
    layer: 'dim',
    domain: 'trade',
    columns: [
      pk('商户ID'),
      str('merchant_name', '商户名称'),
      str('merchant_type', '商户类型: self/pop/brand_direct'),
      str('industry', '所属行业'),
      str('city', '所在城市'),
      str('province', '所在省份'),
      str('settle_cycle', '结算周期: t0/t1/t7'),
      dbl('commission_rate', '佣金费率'),
      str('status', '商户状态: active/suspended/closed'),
      dt('join_date', '入驻日期'),
    ],
  },
  {
    name: 'dim_channel',
    comment: '渠道维度表',
    layer: 'dim',
    domain: 'trade',
    columns: [
      pk('渠道ID'),
      str('channel_code', '渠道编码', { isNullable: false }),
      str('channel_name', '渠道名称'),
      str('channel_type', '渠道类型: online/offline/partner'),
      str('platform', '平台: app/web/h5/mini_program'),
      str('parent_channel', '上级渠道'),
      str('status', '渠道状态: active/inactive'),
    ],
  },
  {
    name: 'dim_region',
    comment: '地区维度表',
    layer: 'dim',
    domain: 'user',
    columns: [
      pk('地区ID'),
      str('country', '国家'),
      str('province', '省份'),
      str('city', '城市'),
      str('district', '区县'),
      str('city_tier', '城市等级: tier1/tier2/tier3/tier4'),
      dbl('latitude', '纬度'),
      dbl('longitude', '经度'),
    ],
  },
  {
    name: 'dim_promotion',
    comment: '促销活动维度表',
    layer: 'dim',
    domain: 'product',
    columns: [
      pk('活动ID'),
      str('promo_name', '活动名称'),
      str('promo_type', '活动类型: flash_sale/coupon/bundle/loyalty'),
      dt('start_date', '开始日期'),
      dt('end_date', '结束日期'),
      dec('budget', '预算金额'),
      dec('spent', '已花费金额'),
      str('status', '活动状态: draft/active/paused/completed'),
      str('target_audience', '目标人群: all/new/vip/dormant'),
    ],
  },
  {
    name: 'dim_risk_rule',
    comment: '风控规则维度表',
    layer: 'dim',
    domain: 'risk',
    columns: [
      pk('规则ID'),
      str('rule_code', '规则编码', { isNullable: false }),
      str('rule_name', '规则名称'),
      str('scene', '应用场景: payment/login/register/withdraw'),
      str('risk_level', '风险等级: low/medium/high/critical'),
      str('action', '默认处置: pass/review/block'),
      dbl('threshold', '阈值'),
      bool('is_enabled', '是否启用'),
      str('description', '规则描述'),
      ts('last_updated', '最近更新时间'),
    ],
  },
];

/* ========================================================================== */
/*  ADS Layer — 7 tables (application-level metrics)                           */
/* ========================================================================== */

const adsTables: TableDef[] = [
  {
    name: 'ads_trade_realtime_monitor',
    comment: '交易实时监控看板表',
    layer: 'ads',
    domain: 'trade',
    columns: [
      pk('记录ID'),
      ts('snapshot_time', '快照时间'),
      bigint('order_count_1h', '近1小时订单数'),
      dec('gmv_1h', '近1小时 GMV'),
      bigint('pay_count_1h', '近1小时支付笔数'),
      dbl('pay_success_rate', '支付成功率'),
      dbl('avg_pay_time_sec', '平均支付耗时（秒）'),
      bigint('refund_count_1h', '近1小时退款数'),
      dbl('gmv_mom', 'GMV 环比增长率'),
    ],
  },
  {
    name: 'ads_user_segment_profile',
    comment: '用户分群画像表',
    layer: 'ads',
    domain: 'user',
    columns: [
      pk('画像ID'),
      ds,
      str('segment_name', '分群名称'),
      str('segment_rule', '分群规则描述'),
      bigint('user_count', '人群规模'),
      dbl('avg_order_count', '平均订单数'),
      dec('avg_gmv', '平均消费金额'),
      dbl('avg_login_freq', '平均登录频次'),
      str('top_category', '偏好品类 Top1'),
      str('top_channel', '偏好渠道 Top1'),
      etl,
    ],
  },
  {
    name: 'ads_product_ranking_daily',
    comment: '商品排行日报表',
    layer: 'ads',
    domain: 'product',
    columns: [
      pk('排行ID'),
      ds,
      fk('product_id', 'dim_product_brand', '商品ID'),
      str('ranking_type', '排行类型: sales/gmv/click/review'),
      int('rank_position', '排名'),
      bigint('metric_value', '指标值'),
      dbl('metric_change', '指标变化率'),
      str('category_l1', '一级品类'),
      etl,
    ],
  },
  {
    name: 'ads_risk_dashboard',
    comment: '风控大盘日报表',
    layer: 'ads',
    domain: 'risk',
    columns: [
      pk('记录ID'),
      ds,
      bigint('total_alerts', '总告警数'),
      bigint('blocked_count', '拦截数'),
      bigint('review_count', '人工审核数'),
      dbl('auto_block_rate', '自动拦截率'),
      dec('prevented_loss', '预防损失金额'),
      bigint('new_blacklist', '新增黑名单数'),
      bigint('active_cases', '进行中案件数'),
      etl,
    ],
  },
  {
    name: 'ads_trade_funnel_daily',
    comment: '交易漏斗日报表',
    layer: 'ads',
    domain: 'trade',
    columns: [
      pk('记录ID'),
      ds,
      str('channel', '渠道'),
      bigint('visit_uv', '访问UV'),
      bigint('product_view_uv', '商详UV'),
      bigint('cart_uv', '加购UV'),
      bigint('order_uv', '下单UV'),
      bigint('pay_uv', '支付UV'),
      dbl('view_to_cart_rate', '商详→加购率'),
      dbl('cart_to_pay_rate', '加购→支付率'),
      dbl('overall_cvr', '总体转化率'),
      etl,
    ],
  },
  {
    name: 'ads_user_value_tier',
    comment: '用户价值分层表',
    layer: 'ads',
    domain: 'user',
    columns: [
      pk('记录ID'),
      ds,
      str('value_tier', '价值层级: high/medium/low/negative'),
      bigint('user_count', '用户数'),
      dec('total_gmv', '总消费金额'),
      dbl('avg_frequency', '平均购买频次'),
      dbl('avg_recency_days', '平均最近购买天数'),
      dec('avg_monetary', '平均客单价'),
      dbl('churn_prob', '流失概率'),
      etl,
    ],
  },
  {
    name: 'ads_product_opportunity',
    comment: '商品机会发现表',
    layer: 'ads',
    domain: 'product',
    columns: [
      pk('记录ID'),
      ds,
      fk('product_id', 'dim_product_brand', '商品ID'),
      str('opportunity_type', '机会类型: underpriced/trending/gap/seasonal'),
      dbl('opportunity_score', '机会评分'),
      bigint('search_demand', '搜索需求量'),
      bigint('supply_count', '供给量'),
      dbl('demand_supply_ratio', '供需比'),
      str('recommendation', '建议: increase_stock/promote/bundle'),
      etl,
    ],
  },
];

/* ========================================================================== */
/*  Metrics — 12 Iceberg-specific analytics metrics                            */
/* ========================================================================== */

const metrics: MetricDef[] = [
  {
    name: 'iceberg_gmv',
    displayName: 'GMV（总成交额）',
    expression: 'SUM(pay_amount)',
    metricType: 'atomic',
    sourceTable: 'dwd_trade_order_di',
    dimensions: ['channel', 'order_type'],
    granularity: ['day', 'week', 'month'],
    format: 'currency',
    description: '所有已支付订单的实付总金额',
  },
  {
    name: 'iceberg_order_count',
    displayName: '订单量',
    expression: 'COUNT(DISTINCT order_no)',
    metricType: 'atomic',
    sourceTable: 'dwd_trade_order_di',
    dimensions: ['channel', 'order_type', 'status'],
    granularity: ['hour', 'day', 'week'],
    format: 'number',
    description: '去重订单数量',
  },
  {
    name: 'iceberg_avg_order_value',
    displayName: '客单价',
    expression: 'SUM(pay_amount) / COUNT(DISTINCT order_no)',
    metricType: 'derived',
    sourceTable: 'dwd_trade_order_di',
    dimensions: ['channel'],
    granularity: ['day', 'month'],
    format: 'currency',
    description: '平均每单实付金额',
  },
  {
    name: 'iceberg_dau',
    displayName: 'DAU（日活跃用户）',
    expression: 'COUNT(DISTINCT user_id)',
    metricType: 'atomic',
    sourceTable: 'dwd_user_event_di',
    dimensions: ['device_type', 'event_type'],
    granularity: ['day'],
    format: 'number',
    description: '当日有行为事件的去重用户数',
  },
  {
    name: 'iceberg_retention_day7',
    displayName: '7日留存率',
    expression: 'day7_retained / cohort_size',
    metricType: 'derived',
    sourceTable: 'dws_user_cohort_7d',
    dimensions: ['register_channel'],
    granularity: ['day'],
    format: 'percentage',
    description: '注册后第7日仍活跃的用户比例',
  },
  {
    name: 'iceberg_refund_rate',
    displayName: '退款率',
    expression: 'COUNT(DISTINCT refund_no) / COUNT(DISTINCT o.order_no)',
    metricType: 'derived',
    sourceTable: 'dwd_trade_refund_di',
    dimensions: ['refund_reason'],
    granularity: ['day', 'week'],
    format: 'percentage',
    description: '退款订单占总订单比例',
  },
  {
    name: 'iceberg_product_ctr',
    displayName: '商品点击率',
    expression: 'click_count / exposure_count',
    metricType: 'derived',
    sourceTable: 'dws_product_conversion_1d',
    dimensions: ['product_id'],
    granularity: ['day'],
    format: 'percentage',
    description: '商品点击次数 / 曝光次数',
  },
  {
    name: 'iceberg_risk_block_rate',
    displayName: '风控拦截率',
    expression: 'block_count / alert_count',
    metricType: 'derived',
    sourceTable: 'dws_risk_alert_daily',
    dimensions: ['risk_scene', 'risk_level'],
    granularity: ['day'],
    format: 'percentage',
    description: '风控自动拦截占总告警比例',
  },
  {
    name: 'iceberg_pay_success_rate',
    displayName: '支付成功率',
    expression: "COUNT(CASE WHEN status='success' THEN 1 END) / COUNT(*)",
    metricType: 'derived',
    sourceTable: 'dwd_trade_payment_di',
    dimensions: ['pay_method'],
    granularity: ['hour', 'day'],
    format: 'percentage',
    description: '支付成功笔数 / 总支付发起笔数',
  },
  {
    name: 'iceberg_fraud_loss',
    displayName: '欺诈损失金额',
    expression: 'SUM(loss_amount)',
    metricType: 'atomic',
    sourceTable: 'dwd_risk_fraud_case_di',
    filters: [{ column: 'status', op: '=', value: 'confirmed' }],
    dimensions: ['fraud_type'],
    granularity: ['month'],
    format: 'currency',
    description: '已确认欺诈案件的总损失金额',
  },
  {
    name: 'iceberg_search_cvr',
    displayName: '搜索转化率',
    expression: 'order_count / search_count',
    metricType: 'derived',
    sourceTable: 'dws_product_search_daily',
    dimensions: ['keyword'],
    granularity: ['day', 'week'],
    format: 'percentage',
    description: '搜索后产生成交的比例',
  },
  {
    name: 'iceberg_user_ltv_30d',
    displayName: '用户30日 LTV',
    expression: 'SUM(pay_amount) FILTER (WHERE DATEDIFF(ds, first_order_date) <= 30)',
    metricType: 'composite',
    sourceTable: 'dwd_trade_order_di',
    dimensions: ['register_channel'],
    granularity: ['month'],
    format: 'currency',
    description: '用户首单后30天内累计消费金额',
  },
];

/* ========================================================================== */
/*  Glossary — 8 lakehouse-specific terms                                      */
/* ========================================================================== */

const glossary: GlossaryDef[] = [
  {
    term: '时间旅行 (Time Travel)',
    sqlExpression: "SELECT * FROM table TIMESTAMP AS OF '2024-01-01 00:00:00'",
    description:
      'Iceberg 支持通过快照ID或时间戳查询历史版本数据，用于数据回溯和审计',
  },
  {
    term: '快照 (Snapshot)',
    sqlExpression: 'SELECT * FROM iceberg_table.snapshots',
    description:
      '每次写入操作生成一个不可变快照，记录表在某一时刻的完整状态，支持原子性读写',
  },
  {
    term: '分区演化 (Partition Evolution)',
    sqlExpression: "ALTER TABLE t SET PARTITION SPEC (days(ts), bucket(16, user_id))",
    description:
      'Iceberg 支持在不重写历史数据的前提下变更分区策略，新数据按新分区写入，旧数据保持原分区',
  },
  {
    term: '隐式分区 (Hidden Partitioning)',
    sqlExpression: 'PARTITIONED BY (days(order_time), bucket(32, user_id))',
    description:
      '用户查询时无需感知分区列，Iceberg 自动根据分区规范进行剪裁，避免手动指定分区过滤',
  },
  {
    term: '写时复制 (Copy-on-Write)',
    sqlExpression: "TBLPROPERTIES ('write.update.mode'='copy-on-write')",
    description:
      '更新时重写整个数据文件，读取性能最优，适合读多写少场景',
  },
  {
    term: '读时合并 (Merge-on-Read)',
    sqlExpression: "TBLPROPERTIES ('write.update.mode'='merge-on-read')",
    description:
      '更新时写入删除文件和新增文件，读取时合并，写入快但读取需额外开销，适合写多读少场景',
  },
  {
    term: 'ACID 事务',
    sqlExpression: 'INSERT OVERWRITE TABLE t PARTITION (ds) SELECT ...',
    description:
      'Iceberg 通过乐观并发控制保证多写者场景下的原子性、一致性、隔离性和持久性',
  },
  {
    term: 'Schema 演化 (Schema Evolution)',
    sqlExpression: 'ALTER TABLE t ADD COLUMNS (new_col STRING COMMENT "新字段")',
    description:
      '支持安全地添加、删除、重命名、重排列，通过列ID追踪保证兼容性，无需重写数据文件',
  },
];

/* ========================================================================== */
/*  Export                                                                     */
/* ========================================================================== */

export const icebergSeed: EngineSeedDefinition = {
  engineType: 'iceberg',
  name: 'Iceberg 湖仓',
  description:
    'Apache Iceberg 湖仓一体存储，支持 ACID 事务和时间旅行，承载核心明细数据',
  dialect: 'sparksql',
  pgSchema: 'dw_iceberg',
  tables: [...dwdTables, ...dwsTables, ...dimTables, ...adsTables],
  metrics,
  glossary,
};
