import type { EngineSeedDefinition, TableDef, MetricDef, GlossaryDef } from './types.js';

/* ═══════════════════════════════════════════════════════════════
 * Helper — tiny column builder scoped to engine ColumnDef
 * (engine types have no defaultValue, different from domain col)
 * ═══════════════════════════════════════════════════════════════ */
const c = {
  pk: (name: string, comment: string) =>
    ({ name, dataType: 'BIGINT', comment, isPrimaryKey: true }) as const,
  bigint: (name: string, comment: string) => ({ name, dataType: 'BIGINT', comment }) as const,
  int: (name: string, comment: string) => ({ name, dataType: 'INT', comment }) as const,
  tinyint: (name: string, comment: string, sampleValues?: string[]) =>
    ({ name, dataType: 'TINYINT', comment, ...(sampleValues ? { sampleValues } : {}) }) as const,
  varchar: (name: string, comment: string, opts?: { sampleValues?: string[]; isPii?: boolean }) =>
    ({ name, dataType: 'VARCHAR(255)', comment, ...opts }) as const,
  decimal: (name: string, comment: string) =>
    ({ name, dataType: 'DECIMAL(18,2)', comment }) as const,
  double: (name: string, comment: string) => ({ name, dataType: 'DOUBLE', comment }) as const,
  datetime: (name: string, comment: string) => ({ name, dataType: 'DATETIME', comment }) as const,
  date: (name: string, comment: string) => ({ name, dataType: 'DATE', comment }) as const,
  text: (name: string, comment: string) => ({ name, dataType: 'TEXT', comment }) as const,
  enumCol: (name: string, comment: string, sampleValues: string[]) =>
    ({ name, dataType: 'ENUM', comment, sampleValues }) as const,
  fk: (name: string, refTable: string, comment: string) =>
    ({
      name,
      dataType: 'BIGINT',
      comment,
      isNullable: false,
      referencesTable: refTable,
      referencesColumn: 'id',
    }) as const,
};

/* ═══════════════════════════════════════════════════════════════
 * ODS Layer — 20 tables (raw operational mirrors)
 * ═══════════════════════════════════════════════════════════════ */
const odsTables: TableDef[] = [
  // ── Trade Domain ──
  {
    name: 'ods_trade_order_df',
    comment: '订单原始表-日全量',
    layer: 'ods',
    domain: 'trade',
    columns: [
      c.pk('order_id', '订单ID'),
      c.fk('user_id', 'ods_user_register_df', '下单用户ID'),
      c.fk('merchant_id', 'dim_merchant', '商家ID'),
      c.varchar('order_no', '订单编号', {
        sampleValues: ['ORD20250101000001', 'ORD20250101000002'],
      }),
      c.varchar('order_status', '订单状态', {
        sampleValues: ['pending', 'paid', 'shipped', 'completed', 'cancelled'],
      }),
      c.decimal('total_amount', '订单总金额'),
      c.decimal('discount_amount', '优惠金额'),
      c.decimal('actual_amount', '实付金额'),
      c.int('item_count', '商品件数'),
      c.varchar('channel', '下单渠道', { sampleValues: ['app', 'h5', 'mini_program', 'web'] }),
      c.varchar('device_type', '设备类型', { sampleValues: ['ios', 'android', 'pc'] }),
      c.datetime('order_time', '下单时间'),
      c.datetime('pay_time', '支付时间'),
      c.datetime('created_at', '记录创建时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'ods_trade_payment_df',
    comment: '支付原始表-日全量',
    layer: 'ods',
    domain: 'trade',
    columns: [
      c.pk('payment_id', '支付ID'),
      c.fk('order_id', 'ods_trade_order_df', '关联订单ID'),
      c.fk('user_id', 'ods_user_register_df', '支付用户ID'),
      c.varchar('payment_no', '支付流水号'),
      c.fk('payment_method_id', 'dim_payment_method', '支付方式ID'),
      c.decimal('payment_amount', '支付金额'),
      c.varchar('payment_status', '支付状态', {
        sampleValues: ['pending', 'success', 'failed', 'refunded'],
      }),
      c.varchar('third_party_trade_no', '第三方交易号'),
      c.datetime('payment_time', '支付完成时间'),
      c.datetime('created_at', '记录创建时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'ods_trade_refund_df',
    comment: '退款原始表-日全量',
    layer: 'ods',
    domain: 'trade',
    columns: [
      c.pk('refund_id', '退款ID'),
      c.fk('order_id', 'ods_trade_order_df', '原始订单ID'),
      c.fk('user_id', 'ods_user_register_df', '退款用户ID'),
      c.varchar('refund_no', '退款编号'),
      c.varchar('refund_reason', '退款原因', {
        sampleValues: ['商品质量问题', '发错货', '不想要了', '未按时发货'],
      }),
      c.decimal('refund_amount', '退款金额'),
      c.varchar('refund_status', '退款状态', {
        sampleValues: ['applying', 'approved', 'rejected', 'completed'],
      }),
      c.datetime('apply_time', '申请时间'),
      c.datetime('complete_time', '退款完成时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'ods_trade_order_item_df',
    comment: '订单明细行原始表-日全量',
    layer: 'ods',
    domain: 'trade',
    columns: [
      c.pk('item_id', '明细行ID'),
      c.fk('order_id', 'ods_trade_order_df', '订单ID'),
      c.fk('sku_id', 'dim_product_sku', 'SKU ID'),
      c.fk('product_id', 'ods_product_info_df', '商品ID'),
      c.varchar('product_name', '商品名称'),
      c.int('quantity', '购买数量'),
      c.decimal('unit_price', '单价'),
      c.decimal('subtotal', '小计金额'),
      c.decimal('discount', '优惠分摊金额'),
      c.datetime('created_at', '记录创建时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'ods_trade_cart_df',
    comment: '购物车原始表-日全量',
    layer: 'ods',
    domain: 'trade',
    columns: [
      c.pk('cart_id', '购物车记录ID'),
      c.fk('user_id', 'ods_user_register_df', '用户ID'),
      c.fk('sku_id', 'dim_product_sku', 'SKU ID'),
      c.int('quantity', '商品数量'),
      c.decimal('unit_price', '加入时单价'),
      c.tinyint('is_checked', '是否选中', ['0', '1']),
      c.datetime('add_time', '加入购物车时间'),
      c.datetime('updated_at', '更新时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'ods_trade_logistics_df',
    comment: '物流信息原始表-日全量',
    layer: 'ods',
    domain: 'trade',
    columns: [
      c.pk('logistics_id', '物流ID'),
      c.fk('order_id', 'ods_trade_order_df', '订单ID'),
      c.varchar('logistics_no', '物流单号'),
      c.varchar('carrier', '承运商', {
        sampleValues: ['顺丰', '中通', '圆通', '韵达', '京东物流'],
      }),
      c.varchar('logistics_status', '物流状态', {
        sampleValues: ['shipping', 'in_transit', 'delivered', 'signed'],
      }),
      c.datetime('ship_time', '发货时间'),
      c.datetime('sign_time', '签收时间'),
      c.varchar('receiver_province', '收件省份'),
      c.varchar('receiver_city', '收件城市'),
      c.date('ds', '数据分区日期'),
    ],
  },

  // ── User Domain ──
  {
    name: 'ods_user_register_df',
    comment: '注册原始表-日全量',
    layer: 'ods',
    domain: 'user',
    columns: [
      c.pk('user_id', '用户ID'),
      c.varchar('username', '用户名'),
      c.varchar('nickname', '昵称'),
      c.varchar('phone', '手机号', { isPii: true }),
      c.varchar('email', '邮箱', { isPii: true }),
      c.varchar('gender', '性别', { sampleValues: ['male', 'female', 'unknown'] }),
      c.date('birthday', '出生日期'),
      c.varchar('register_source', '注册来源', { sampleValues: ['app', 'wechat', 'web', 'h5'] }),
      c.varchar('register_ip', '注册IP'),
      c.tinyint('status', '账号状态: 1-正常 2-冻结 3-注销', ['1', '2', '3']),
      c.datetime('register_time', '注册时间'),
      c.datetime('created_at', '记录创建时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'ods_user_login_log_di',
    comment: '登录日志原始表-日增量',
    layer: 'ods',
    domain: 'user',
    columns: [
      c.pk('log_id', '日志ID'),
      c.fk('user_id', 'ods_user_register_df', '用户ID'),
      c.datetime('login_time', '登录时间'),
      c.varchar('login_ip', '登录IP'),
      c.varchar('device_type', '设备类型', { sampleValues: ['ios', 'android', 'web'] }),
      c.varchar('device_model', '设备型号'),
      c.varchar('app_version', '应用版本'),
      c.varchar('login_method', '登录方式', {
        sampleValues: ['password', 'sms', 'wechat', 'fingerprint'],
      }),
      c.tinyint('login_result', '登录结果: 1-成功 0-失败', ['0', '1']),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'ods_user_address_df',
    comment: '用户地址原始表-日全量',
    layer: 'ods',
    domain: 'user',
    columns: [
      c.pk('address_id', '地址ID'),
      c.fk('user_id', 'ods_user_register_df', '用户ID'),
      c.varchar('receiver_name', '收件人姓名', { isPii: true }),
      c.varchar('receiver_phone', '收件人手机号', { isPii: true }),
      c.varchar('province', '省份'),
      c.varchar('city', '城市'),
      c.varchar('district', '区县'),
      c.text('detail_address', '详细地址'),
      c.tinyint('is_default', '是否默认地址', ['0', '1']),
      c.datetime('created_at', '创建时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'ods_user_feedback_di',
    comment: '用户反馈原始表-日增量',
    layer: 'ods',
    domain: 'user',
    columns: [
      c.pk('feedback_id', '反馈ID'),
      c.fk('user_id', 'ods_user_register_df', '用户ID'),
      c.varchar('feedback_type', '反馈类型', {
        sampleValues: ['complaint', 'suggestion', 'bug_report', 'praise'],
      }),
      c.text('content', '反馈内容'),
      c.varchar('feedback_status', '处理状态', {
        sampleValues: ['open', 'processing', 'resolved', 'closed'],
      }),
      c.int('priority', '优先级: 1-低 2-中 3-高'),
      c.datetime('submit_time', '提交时间'),
      c.date('ds', '数据分区日期'),
    ],
  },

  // ── Product Domain ──
  {
    name: 'ods_product_info_df',
    comment: '商品信息原始表-日全量',
    layer: 'ods',
    domain: 'product',
    columns: [
      c.pk('product_id', '商品ID'),
      c.fk('merchant_id', 'dim_merchant', '所属商家ID'),
      c.fk('category_id', 'dim_product_category', '类目ID'),
      c.varchar('product_name', '商品名称'),
      c.varchar('brand', '品牌'),
      c.decimal('original_price', '原价'),
      c.decimal('selling_price', '售价'),
      c.int('stock_quantity', '库存数量'),
      c.varchar('product_status', '商品状态', {
        sampleValues: ['on_sale', 'off_sale', 'pre_sale', 'deleted'],
      }),
      c.tinyint('is_featured', '是否推荐', ['0', '1']),
      c.datetime('publish_time', '上架时间'),
      c.datetime('created_at', '创建时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'ods_product_review_di',
    comment: '商品评价原始表-日增量',
    layer: 'ods',
    domain: 'product',
    columns: [
      c.pk('review_id', '评价ID'),
      c.fk('product_id', 'ods_product_info_df', '商品ID'),
      c.fk('user_id', 'ods_user_register_df', '评价用户ID'),
      c.fk('order_id', 'ods_trade_order_df', '关联订单ID'),
      c.int('rating', '评分: 1-5'),
      c.text('review_content', '评价内容'),
      c.int('image_count', '图片数量'),
      c.tinyint('is_anonymous', '是否匿名', ['0', '1']),
      c.datetime('review_time', '评价时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'ods_product_inventory_log_di',
    comment: '库存变动日志原始表-日增量',
    layer: 'ods',
    domain: 'product',
    columns: [
      c.pk('log_id', '日志ID'),
      c.fk('sku_id', 'dim_product_sku', 'SKU ID'),
      c.fk('product_id', 'ods_product_info_df', '商品ID'),
      c.varchar('change_type', '变动类型', {
        sampleValues: ['purchase', 'sale', 'return', 'adjust', 'transfer'],
      }),
      c.int('change_quantity', '变动数量'),
      c.int('stock_after', '变动后库存'),
      c.varchar('operator', '操作人'),
      c.datetime('change_time', '变动时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'ods_product_price_log_di',
    comment: '商品价格变动日志原始表-日增量',
    layer: 'ods',
    domain: 'product',
    columns: [
      c.pk('log_id', '价格变动ID'),
      c.fk('product_id', 'ods_product_info_df', '商品ID'),
      c.decimal('old_price', '调整前价格'),
      c.decimal('new_price', '调整后价格'),
      c.varchar('change_reason', '调价原因', {
        sampleValues: ['promotion', 'cost_change', 'market_adjust', 'clearance'],
      }),
      c.varchar('operator', '操作人'),
      c.datetime('change_time', '变动时间'),
      c.date('ds', '数据分区日期'),
    ],
  },

  // ── Risk Domain ──
  {
    name: 'ods_risk_event_di',
    comment: '风控事件原始表-日增量',
    layer: 'ods',
    domain: 'risk',
    columns: [
      c.pk('event_id', '事件ID'),
      c.fk('user_id', 'ods_user_register_df', '触发用户ID'),
      c.fk('rule_id', 'dim_risk_rule', '触发规则ID'),
      c.varchar('event_type', '事件类型', {
        sampleValues: ['login_anomaly', 'payment_fraud', 'bot_attack', 'identity_theft'],
      }),
      c.varchar('risk_level', '风险等级', { sampleValues: ['low', 'medium', 'high', 'critical'] }),
      c.int('risk_score', '风险评分 0-100'),
      c.varchar('event_detail', '事件详情'),
      c.varchar('action_taken', '处置动作', {
        sampleValues: ['pass', 'captcha', 'sms_verify', 'block', 'freeze'],
      }),
      c.varchar('ip_address', 'IP地址'),
      c.datetime('event_time', '事件时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'ods_risk_blacklist_df',
    comment: '黑名单原始表-日全量',
    layer: 'ods',
    domain: 'risk',
    columns: [
      c.pk('blacklist_id', '黑名单ID'),
      c.varchar('target_type', '目标类型', { sampleValues: ['user', 'ip', 'device', 'phone'] }),
      c.varchar('target_value', '目标值'),
      c.varchar('reason', '拉黑原因'),
      c.varchar('source', '来源', { sampleValues: ['manual', 'rule_engine', 'third_party'] }),
      c.tinyint('is_active', '是否生效', ['0', '1']),
      c.datetime('expire_time', '过期时间'),
      c.datetime('created_at', '创建时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'ods_risk_audit_log_di',
    comment: '风控审核日志原始表-日增量',
    layer: 'ods',
    domain: 'risk',
    columns: [
      c.pk('audit_id', '审核ID'),
      c.fk('event_id', 'ods_risk_event_di', '关联事件ID'),
      c.varchar('auditor', '审核人'),
      c.varchar('audit_result', '审核结果', {
        sampleValues: ['approved', 'rejected', 'escalated'],
      }),
      c.text('audit_comment', '审核备注'),
      c.datetime('audit_time', '审核时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'ods_risk_device_fingerprint_df',
    comment: '设备指纹原始表-日全量',
    layer: 'ods',
    domain: 'risk',
    columns: [
      c.pk('fingerprint_id', '指纹ID'),
      c.fk('user_id', 'ods_user_register_df', '关联用户ID'),
      c.varchar('device_id', '设备标识'),
      c.varchar('device_type', '设备类型', { sampleValues: ['ios', 'android', 'pc', 'tablet'] }),
      c.varchar('os_version', '操作系统版本'),
      c.varchar('browser_type', '浏览器类型'),
      c.varchar('ip_address', 'IP地址'),
      c.int('login_count', '该设备登录次数'),
      c.tinyint('is_trusted', '是否可信设备', ['0', '1']),
      c.datetime('first_seen', '首次出现时间'),
      c.datetime('last_seen', '最近出现时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'ods_user_points_log_di',
    comment: '用户积分变动日志原始表-日增量',
    layer: 'ods',
    domain: 'user',
    columns: [
      c.pk('log_id', '日志ID'),
      c.fk('user_id', 'ods_user_register_df', '用户ID'),
      c.int('points_change', '积分变动值'),
      c.varchar('change_type', '变动类型', {
        sampleValues: ['earn', 'redeem', 'expire', 'adjust'],
      }),
      c.varchar('source', '变动来源'),
      c.varchar('ref_order_id', '关联订单号'),
      c.int('balance_after', '变动后积分余额'),
      c.datetime('created_at', '创建时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'ods_trade_coupon_use_di',
    comment: '优惠券使用原始表-日增量',
    layer: 'ods',
    domain: 'trade',
    columns: [
      c.pk('use_id', '使用记录ID'),
      c.fk('user_id', 'ods_user_register_df', '用户ID'),
      c.fk('order_id', 'ods_trade_order_df', '订单ID'),
      c.bigint('coupon_id', '优惠券ID'),
      c.varchar('coupon_type', '优惠券类型', {
        sampleValues: ['full_reduction', 'percentage_off', 'free_shipping'],
      }),
      c.decimal('coupon_value', '优惠券面值'),
      c.decimal('actual_discount', '实际优惠金额'),
      c.datetime('use_time', '使用时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
];

/* ═══════════════════════════════════════════════════════════════
 * DIM Layer — 20 tables (dimension / lookup)
 * ═══════════════════════════════════════════════════════════════ */
const dimTables: TableDef[] = [
  // ── User Domain ──
  {
    name: 'dim_user_profile',
    comment: '用户画像维度表',
    layer: 'dim',
    domain: 'user',
    columns: [
      c.pk('id', '用户画像ID'),
      c.fk('user_id', 'ods_user_register_df', '用户ID'),
      c.varchar('age_group', '年龄段', {
        sampleValues: ['18-24', '25-30', '31-40', '41-50', '50+'],
      }),
      c.varchar('consumption_level', '消费水平', {
        sampleValues: ['low', 'medium', 'high', 'premium'],
      }),
      c.varchar('lifecycle_stage', '生命周期阶段', {
        sampleValues: ['new', 'active', 'dormant', 'churned'],
      }),
      c.varchar('preferred_category', '偏好类目'),
      c.int('login_frequency', '月均登录次数'),
      c.tinyint('status', '状态: 1-有效 0-无效', ['0', '1']),
      c.datetime('created_at', '创建时间'),
      c.datetime('updated_at', '更新时间'),
    ],
  },
  {
    name: 'dim_user_level',
    comment: '用户等级维度表',
    layer: 'dim',
    domain: 'user',
    columns: [
      c.pk('id', '等级ID'),
      c.varchar('level_name', '等级名称', {
        sampleValues: ['普通会员', '银卡会员', '金卡会员', '钻石会员'],
      }),
      c.int('level_code', '等级编码'),
      c.int('min_points', '所需最低积分'),
      c.double('discount_rate', '折扣率'),
      c.varchar('display_name', '显示名称'),
      c.text('benefits_desc', '权益描述'),
      c.tinyint('status', '状态: 1-启用 0-停用', ['0', '1']),
      c.datetime('created_at', '创建时间'),
      c.datetime('updated_at', '更新时间'),
    ],
  },
  {
    name: 'dim_user_tag',
    comment: '用户标签维度表',
    layer: 'dim',
    domain: 'user',
    columns: [
      c.pk('id', '标签ID'),
      c.varchar('tag_name', '标签名称'),
      c.varchar('tag_group', '标签分组', {
        sampleValues: ['behavior', 'preference', 'value', 'demographic'],
      }),
      c.varchar('display_name', '显示名称'),
      c.text('tag_definition', '标签定义SQL或规则'),
      c.tinyint('status', '状态: 1-启用 0-停用', ['0', '1']),
      c.datetime('created_at', '创建时间'),
      c.datetime('updated_at', '更新时间'),
    ],
  },

  // ── Product Domain ──
  {
    name: 'dim_product_sku',
    comment: '商品SKU维度表',
    layer: 'dim',
    domain: 'product',
    columns: [
      c.pk('id', 'SKU ID'),
      c.fk('product_id', 'ods_product_info_df', '关联商品ID'),
      c.varchar('sku_code', 'SKU编码'),
      c.varchar('sku_name', 'SKU名称'),
      c.varchar('spec_info', '规格信息'),
      c.decimal('price', '售价'),
      c.decimal('cost_price', '成本价'),
      c.int('stock', '当前库存'),
      c.varchar('barcode', '条形码'),
      c.tinyint('status', '状态: 1-在售 0-停售', ['0', '1']),
      c.datetime('created_at', '创建时间'),
      c.datetime('updated_at', '更新时间'),
    ],
  },
  {
    name: 'dim_product_category',
    comment: '商品类目维度表',
    layer: 'dim',
    domain: 'product',
    columns: [
      c.pk('id', '类目ID'),
      c.varchar('category_name', '类目名称'),
      c.varchar('display_name', '显示名称'),
      c.int('parent_id', '父级类目ID'),
      c.int('level', '层级: 1-一级 2-二级 3-三级'),
      c.varchar('category_path', '类目路径'),
      c.int('sort_order', '排序'),
      c.tinyint('status', '状态: 1-启用 0-停用', ['0', '1']),
      c.datetime('created_at', '创建时间'),
      c.datetime('updated_at', '更新时间'),
    ],
  },
  {
    name: 'dim_product_brand',
    comment: '品牌维度表',
    layer: 'dim',
    domain: 'product',
    columns: [
      c.pk('id', '品牌ID'),
      c.varchar('brand_name', '品牌名称'),
      c.varchar('display_name', '显示名称'),
      c.varchar('brand_logo_url', '品牌LOGO地址'),
      c.varchar('country_of_origin', '原产国', {
        sampleValues: ['中国', '美国', '日本', '韩国', '德国'],
      }),
      c.varchar('brand_level', '品牌档次', {
        sampleValues: ['luxury', 'premium', 'mid_range', 'budget'],
      }),
      c.tinyint('status', '状态: 1-启用 0-停用', ['0', '1']),
      c.datetime('created_at', '创建时间'),
      c.datetime('updated_at', '更新时间'),
    ],
  },
  {
    name: 'dim_product_attribute',
    comment: '商品属性维度表',
    layer: 'dim',
    domain: 'product',
    columns: [
      c.pk('id', '属性ID'),
      c.fk('category_id', 'dim_product_category', '所属类目ID'),
      c.varchar('attribute_name', '属性名称'),
      c.varchar('display_name', '显示名称'),
      c.varchar('attribute_type', '属性类型', {
        sampleValues: ['select', 'input', 'multi_select'],
      }),
      c.text('attribute_values', '可选值列表(JSON)'),
      c.tinyint('is_required', '是否必填', ['0', '1']),
      c.tinyint('status', '状态: 1-启用 0-停用', ['0', '1']),
      c.datetime('created_at', '创建时间'),
      c.datetime('updated_at', '更新时间'),
    ],
  },

  // ── Trade Domain ──
  {
    name: 'dim_merchant',
    comment: '商家维度表',
    layer: 'dim',
    domain: 'trade',
    columns: [
      c.pk('id', '商家ID'),
      c.varchar('merchant_name', '商家名称'),
      c.varchar('display_name', '显示名称'),
      c.varchar('merchant_type', '商家类型', {
        sampleValues: ['self_operated', 'third_party', 'franchise'],
      }),
      c.varchar('contact_phone', '联系电话', { isPii: true }),
      c.varchar('province', '所在省份'),
      c.varchar('city', '所在城市'),
      c.varchar('merchant_level', '商家等级', { sampleValues: ['standard', 'gold', 'platinum'] }),
      c.tinyint('status', '状态: 1-正常 2-冻结 3-关闭', ['1', '2', '3']),
      c.datetime('created_at', '创建时间'),
      c.datetime('updated_at', '更新时间'),
    ],
  },
  {
    name: 'dim_region',
    comment: '地区维度表',
    layer: 'dim',
    domain: 'trade',
    columns: [
      c.pk('id', '地区ID'),
      c.varchar('region_name', '地区名称'),
      c.varchar('display_name', '显示名称'),
      c.int('parent_id', '父级地区ID'),
      c.int('level', '层级: 1-省 2-市 3-区'),
      c.varchar('region_code', '地区编码'),
      c.varchar('zip_code', '邮政编码'),
      c.tinyint('status', '状态: 1-有效 0-无效', ['0', '1']),
      c.datetime('created_at', '创建时间'),
      c.datetime('updated_at', '更新时间'),
    ],
  },
  {
    name: 'dim_channel',
    comment: '渠道维度表',
    layer: 'dim',
    domain: 'trade',
    columns: [
      c.pk('id', '渠道ID'),
      c.varchar('channel_code', '渠道编码', {
        sampleValues: ['app', 'wechat', 'h5', 'web', 'mini_program'],
      }),
      c.varchar('channel_name', '渠道名称'),
      c.varchar('display_name', '显示名称'),
      c.varchar('channel_group', '渠道分组', { sampleValues: ['online', 'offline', 'social'] }),
      c.tinyint('status', '状态: 1-启用 0-停用', ['0', '1']),
      c.datetime('created_at', '创建时间'),
      c.datetime('updated_at', '更新时间'),
    ],
  },
  {
    name: 'dim_payment_method',
    comment: '支付方式维度表',
    layer: 'dim',
    domain: 'trade',
    columns: [
      c.pk('id', '支付方式ID'),
      c.varchar('method_code', '支付编码', {
        sampleValues: ['alipay', 'wechat_pay', 'credit_card', 'debit_card', 'balance'],
      }),
      c.varchar('method_name', '支付名称'),
      c.varchar('display_name', '显示名称'),
      c.double('fee_rate', '手续费率'),
      c.tinyint('status', '状态: 1-启用 0-停用', ['0', '1']),
      c.datetime('created_at', '创建时间'),
      c.datetime('updated_at', '更新时间'),
    ],
  },
  {
    name: 'dim_coupon',
    comment: '优惠券维度表',
    layer: 'dim',
    domain: 'trade',
    columns: [
      c.pk('id', '优惠券ID'),
      c.varchar('coupon_name', '优惠券名称'),
      c.varchar('display_name', '显示名称'),
      c.varchar('coupon_type', '优惠券类型', {
        sampleValues: ['full_reduction', 'percentage_off', 'free_shipping'],
      }),
      c.decimal('face_value', '面值'),
      c.decimal('min_order_amount', '最低使用金额'),
      c.date('valid_start', '生效开始日期'),
      c.date('valid_end', '生效结束日期'),
      c.int('total_quantity', '发放总量'),
      c.int('used_quantity', '已使用数量'),
      c.tinyint('status', '状态: 1-有效 2-失效 3-已过期', ['1', '2', '3']),
      c.datetime('created_at', '创建时间'),
      c.datetime('updated_at', '更新时间'),
    ],
  },
  {
    name: 'dim_warehouse',
    comment: '仓库维度表',
    layer: 'dim',
    domain: 'trade',
    columns: [
      c.pk('id', '仓库ID'),
      c.varchar('warehouse_name', '仓库名称'),
      c.varchar('display_name', '显示名称'),
      c.varchar('warehouse_type', '仓库类型', {
        sampleValues: ['central', 'regional', 'bonded', 'return'],
      }),
      c.varchar('province', '所在省份'),
      c.varchar('city', '所在城市'),
      c.varchar('contact_person', '联系人'),
      c.tinyint('status', '状态: 1-运营中 0-关闭', ['0', '1']),
      c.datetime('created_at', '创建时间'),
      c.datetime('updated_at', '更新时间'),
    ],
  },
  {
    name: 'dim_logistics_provider',
    comment: '物流服务商维度表',
    layer: 'dim',
    domain: 'trade',
    columns: [
      c.pk('id', '服务商ID'),
      c.varchar('provider_name', '服务商名称', {
        sampleValues: ['顺丰速运', '中通快递', '圆通速递', '韵达快递', '京东物流'],
      }),
      c.varchar('display_name', '显示名称'),
      c.varchar('provider_code', '服务商编码'),
      c.varchar('service_level', '服务等级', { sampleValues: ['standard', 'express', 'same_day'] }),
      c.tinyint('status', '状态: 1-合作中 0-停用', ['0', '1']),
      c.datetime('created_at', '创建时间'),
      c.datetime('updated_at', '更新时间'),
    ],
  },

  // ── Risk Domain ──
  {
    name: 'dim_risk_rule',
    comment: '风控规则维度表',
    layer: 'dim',
    domain: 'risk',
    columns: [
      c.pk('id', '规则ID'),
      c.varchar('rule_name', '规则名称'),
      c.varchar('display_name', '显示名称'),
      c.varchar('rule_type', '规则类型', {
        sampleValues: ['frequency', 'amount', 'behavior', 'device', 'geo'],
      }),
      c.varchar('risk_level', '风险等级', { sampleValues: ['low', 'medium', 'high', 'critical'] }),
      c.text('rule_expression', '规则表达式'),
      c.varchar('action_type', '处置类型', {
        sampleValues: ['pass', 'captcha', 'sms_verify', 'block', 'manual_review'],
      }),
      c.int('priority', '优先级'),
      c.tinyint('status', '状态: 1-启用 0-停用', ['0', '1']),
      c.datetime('created_at', '创建时间'),
      c.datetime('updated_at', '更新时间'),
    ],
  },
  {
    name: 'dim_risk_category',
    comment: '风险类别维度表',
    layer: 'dim',
    domain: 'risk',
    columns: [
      c.pk('id', '类别ID'),
      c.varchar('category_name', '类别名称'),
      c.varchar('display_name', '显示名称'),
      c.int('parent_id', '父级类别ID'),
      c.varchar('severity', '严重程度', { sampleValues: ['info', 'warning', 'danger', 'fatal'] }),
      c.text('description', '风险类别描述'),
      c.tinyint('status', '状态: 1-启用 0-停用', ['0', '1']),
      c.datetime('created_at', '创建时间'),
      c.datetime('updated_at', '更新时间'),
    ],
  },
  {
    name: 'dim_date',
    comment: '日期维度表',
    layer: 'dim',
    domain: 'trade',
    columns: [
      c.pk('id', '日期ID'),
      c.date('date_value', '日期值'),
      c.int('year', '年'),
      c.int('quarter', '季度'),
      c.int('month', '月'),
      c.int('week_of_year', '年中第几周'),
      c.int('day_of_week', '周几: 1-7'),
      c.varchar('day_name', '星期名称', {
        sampleValues: [
          'Monday',
          'Tuesday',
          'Wednesday',
          'Thursday',
          'Friday',
          'Saturday',
          'Sunday',
        ],
      }),
      c.tinyint('is_weekend', '是否周末', ['0', '1']),
      c.tinyint('is_holiday', '是否节假日', ['0', '1']),
      c.varchar('holiday_name', '节假日名称'),
    ],
  },
  {
    name: 'dim_time_period',
    comment: '时间段维度表',
    layer: 'dim',
    domain: 'trade',
    columns: [
      c.pk('id', '时段ID'),
      c.varchar('period_name', '时段名称', {
        sampleValues: ['凌晨', '早间', '上午', '中午', '下午', '傍晚', '晚间', '深夜'],
      }),
      c.varchar('display_name', '显示名称'),
      c.int('start_hour', '起始小时'),
      c.int('end_hour', '结束小时'),
      c.tinyint('status', '状态: 1-启用 0-停用', ['0', '1']),
      c.datetime('created_at', '创建时间'),
      c.datetime('updated_at', '更新时间'),
    ],
  },
  {
    name: 'dim_promotion_type',
    comment: '促销类型维度表',
    layer: 'dim',
    domain: 'trade',
    columns: [
      c.pk('id', '促销类型ID'),
      c.varchar('type_code', '类型编码', {
        sampleValues: ['flash_sale', 'group_buy', 'full_reduction', 'gift', 'bundle'],
      }),
      c.varchar('type_name', '类型名称'),
      c.varchar('display_name', '显示名称'),
      c.text('description', '促销类型描述'),
      c.tinyint('status', '状态: 1-启用 0-停用', ['0', '1']),
      c.datetime('created_at', '创建时间'),
      c.datetime('updated_at', '更新时间'),
    ],
  },
  {
    name: 'dim_operation_type',
    comment: '操作类型维度表',
    layer: 'dim',
    domain: 'user',
    columns: [
      c.pk('id', '操作类型ID'),
      c.varchar('type_code', '类型编码', {
        sampleValues: ['browse', 'add_cart', 'order', 'pay', 'review', 'share', 'collect'],
      }),
      c.varchar('type_name', '类型名称'),
      c.varchar('display_name', '显示名称'),
      c.varchar('type_group', '类型分组', {
        sampleValues: ['browse', 'transaction', 'interaction'],
      }),
      c.tinyint('status', '状态: 1-启用 0-停用', ['0', '1']),
      c.datetime('created_at', '创建时间'),
      c.datetime('updated_at', '更新时间'),
    ],
  },
];

/* ═══════════════════════════════════════════════════════════════
 * DWD Layer — 8 tables (cleaned detail)
 * ═══════════════════════════════════════════════════════════════ */
const dwdTables: TableDef[] = [
  {
    name: 'dwd_trade_order_detail_di',
    comment: '交易订单明细表-日增量',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      c.pk('id', '明细ID'),
      c.bigint('order_id', '订单ID'),
      c.bigint('user_id', '用户ID'),
      c.bigint('merchant_id', '商家ID'),
      c.bigint('sku_id', 'SKU ID'),
      c.bigint('product_id', '商品ID'),
      c.bigint('category_id', '类目ID'),
      c.varchar('order_status', '订单状态', {
        sampleValues: ['paid', 'shipped', 'completed', 'cancelled'],
      }),
      c.int('quantity', '购买数量'),
      c.decimal('unit_price', '单价'),
      c.decimal('discount_amount', '优惠金额'),
      c.decimal('actual_amount', '实付金额'),
      c.varchar('channel', '下单渠道', { sampleValues: ['app', 'h5', 'mini_program', 'web'] }),
      c.varchar('payment_method', '支付方式', {
        sampleValues: ['alipay', 'wechat_pay', 'credit_card'],
      }),
      c.datetime('order_time', '下单时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'dwd_trade_payment_detail_di',
    comment: '支付明细表-日增量',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      c.pk('id', '明细ID'),
      c.bigint('payment_id', '支付ID'),
      c.bigint('order_id', '订单ID'),
      c.bigint('user_id', '用户ID'),
      c.varchar('payment_method', '支付方式', {
        sampleValues: ['alipay', 'wechat_pay', 'credit_card', 'balance'],
      }),
      c.decimal('payment_amount', '支付金额'),
      c.varchar('payment_status', '支付状态', { sampleValues: ['success', 'failed', 'refunded'] }),
      c.datetime('payment_time', '支付时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'dwd_user_behavior_di',
    comment: '用户行为明细表-日增量',
    layer: 'dwd',
    domain: 'user',
    columns: [
      c.pk('id', '行为ID'),
      c.bigint('user_id', '用户ID'),
      c.varchar('behavior_type', '行为类型', {
        sampleValues: ['browse', 'add_cart', 'collect', 'share', 'search'],
      }),
      c.bigint('target_id', '行为对象ID'),
      c.varchar('target_type', '对象类型', { sampleValues: ['product', 'store', 'article'] }),
      c.varchar('page_name', '页面名称'),
      c.int('stay_duration', '停留时长(秒)'),
      c.varchar('device_type', '设备类型', { sampleValues: ['ios', 'android', 'web'] }),
      c.varchar('channel', '渠道来源', { sampleValues: ['app', 'h5', 'mini_program'] }),
      c.datetime('behavior_time', '行为时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'dwd_user_login_detail_di',
    comment: '用户登录明细表-日增量',
    layer: 'dwd',
    domain: 'user',
    columns: [
      c.pk('id', '明细ID'),
      c.bigint('user_id', '用户ID'),
      c.varchar('login_method', '登录方式', {
        sampleValues: ['password', 'sms', 'wechat', 'fingerprint'],
      }),
      c.varchar('device_type', '设备类型', { sampleValues: ['ios', 'android', 'web'] }),
      c.varchar('device_model', '设备型号'),
      c.varchar('os_version', '操作系统版本'),
      c.varchar('app_version', '应用版本'),
      c.varchar('ip_address', 'IP地址'),
      c.bigint('region_id', '地区ID'),
      c.tinyint('is_success', '是否成功', ['0', '1']),
      c.datetime('login_time', '登录时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'dwd_product_review_detail_di',
    comment: '商品评价明细表-日增量',
    layer: 'dwd',
    domain: 'product',
    columns: [
      c.pk('id', '明细ID'),
      c.bigint('review_id', '评价ID'),
      c.bigint('product_id', '商品ID'),
      c.bigint('user_id', '用户ID'),
      c.bigint('order_id', '订单ID'),
      c.bigint('category_id', '类目ID'),
      c.int('rating', '评分'),
      c.double('sentiment_score', '情感分析得分'),
      c.varchar('sentiment_label', '情感标签', {
        sampleValues: ['positive', 'neutral', 'negative'],
      }),
      c.int('word_count', '评价字数'),
      c.tinyint('has_image', '是否有图', ['0', '1']),
      c.datetime('review_time', '评价时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'dwd_trade_refund_detail_di',
    comment: '退款明细表-日增量',
    layer: 'dwd',
    domain: 'trade',
    columns: [
      c.pk('id', '明细ID'),
      c.bigint('refund_id', '退款ID'),
      c.bigint('order_id', '订单ID'),
      c.bigint('user_id', '用户ID'),
      c.bigint('merchant_id', '商家ID'),
      c.varchar('refund_reason', '退款原因', {
        sampleValues: ['商品质量问题', '发错货', '不想要了'],
      }),
      c.decimal('refund_amount', '退款金额'),
      c.varchar('refund_status', '退款状态', {
        sampleValues: ['approved', 'rejected', 'completed'],
      }),
      c.datetime('apply_time', '申请时间'),
      c.datetime('complete_time', '完成时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'dwd_risk_event_detail_di',
    comment: '风控事件明细表-日增量',
    layer: 'dwd',
    domain: 'risk',
    columns: [
      c.pk('id', '明细ID'),
      c.bigint('event_id', '事件ID'),
      c.bigint('user_id', '用户ID'),
      c.bigint('rule_id', '规则ID'),
      c.varchar('event_type', '事件类型', {
        sampleValues: ['login_anomaly', 'payment_fraud', 'bot_attack'],
      }),
      c.varchar('risk_level', '风险等级', { sampleValues: ['low', 'medium', 'high', 'critical'] }),
      c.int('risk_score', '风险评分'),
      c.varchar('action_taken', '处置动作', { sampleValues: ['pass', 'captcha', 'block'] }),
      c.varchar('device_type', '设备类型', { sampleValues: ['ios', 'android', 'pc'] }),
      c.varchar('ip_address', 'IP地址'),
      c.bigint('region_id', '地区ID'),
      c.datetime('event_time', '事件时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
  {
    name: 'dwd_product_inventory_detail_di',
    comment: '库存变动明细表-日增量',
    layer: 'dwd',
    domain: 'product',
    columns: [
      c.pk('id', '明细ID'),
      c.bigint('sku_id', 'SKU ID'),
      c.bigint('product_id', '商品ID'),
      c.bigint('warehouse_id', '仓库ID'),
      c.varchar('change_type', '变动类型', {
        sampleValues: ['purchase', 'sale', 'return', 'adjust'],
      }),
      c.int('change_quantity', '变动数量'),
      c.int('stock_before', '变动前库存'),
      c.int('stock_after', '变动后库存'),
      c.datetime('change_time', '变动时间'),
      c.date('ds', '数据分区日期'),
    ],
  },
];

/* ═══════════════════════════════════════════════════════════════
 * DWS Layer — 7 tables (basic summaries)
 * ═══════════════════════════════════════════════════════════════ */
const dwsTables: TableDef[] = [
  {
    name: 'dws_trade_merchant_summary_dd',
    comment: '商家交易日汇总表',
    layer: 'dws',
    domain: 'trade',
    columns: [
      c.pk('id', '汇总ID'),
      c.bigint('merchant_id', '商家ID'),
      c.date('stat_date', '统计日期'),
      c.bigint('order_count', '订单数'),
      c.decimal('total_amount', '交易总额'),
      c.decimal('refund_amount', '退款总额'),
      c.bigint('buyer_count', '购买用户数'),
      c.double('refund_rate', '退款率'),
      c.datetime('etl_time', 'ETL处理时间'),
    ],
  },
  {
    name: 'dws_trade_channel_summary_dd',
    comment: '渠道交易日汇总表',
    layer: 'dws',
    domain: 'trade',
    columns: [
      c.pk('id', '汇总ID'),
      c.varchar('channel', '渠道编码', { sampleValues: ['app', 'h5', 'mini_program', 'web'] }),
      c.date('stat_date', '统计日期'),
      c.bigint('order_count', '订单数'),
      c.decimal('total_amount', '交易总额'),
      c.bigint('pay_user_count', '支付用户数'),
      c.decimal('avg_order_amount', '平均订单金额'),
      c.double('conversion_rate', '转化率'),
      c.datetime('etl_time', 'ETL处理时间'),
    ],
  },
  {
    name: 'dws_user_active_summary_dd',
    comment: '用户活跃日汇总表',
    layer: 'dws',
    domain: 'user',
    columns: [
      c.pk('id', '汇总ID'),
      c.date('stat_date', '统计日期'),
      c.bigint('dau', '日活跃用户数'),
      c.bigint('new_user_count', '新增注册数'),
      c.bigint('login_count', '登录总次数'),
      c.double('retention_rate_1d', '次日留存率'),
      c.double('retention_rate_7d', '7日留存率'),
      c.varchar('top_device_type', '最多设备类型', { sampleValues: ['ios', 'android', 'web'] }),
      c.datetime('etl_time', 'ETL处理时间'),
    ],
  },
  {
    name: 'dws_product_sale_summary_dd',
    comment: '商品销售日汇总表',
    layer: 'dws',
    domain: 'product',
    columns: [
      c.pk('id', '汇总ID'),
      c.bigint('product_id', '商品ID'),
      c.bigint('category_id', '类目ID'),
      c.date('stat_date', '统计日期'),
      c.bigint('sale_count', '销售件数'),
      c.decimal('sale_amount', '销售金额'),
      c.bigint('order_count', '订单数'),
      c.bigint('buyer_count', '购买人数'),
      c.double('avg_rating', '平均评分'),
      c.int('review_count', '评价数'),
      c.datetime('etl_time', 'ETL处理时间'),
    ],
  },
  {
    name: 'dws_trade_region_summary_dd',
    comment: '地区交易日汇总表',
    layer: 'dws',
    domain: 'trade',
    columns: [
      c.pk('id', '汇总ID'),
      c.bigint('region_id', '地区ID'),
      c.varchar('province', '省份'),
      c.date('stat_date', '统计日期'),
      c.bigint('order_count', '订单数'),
      c.decimal('total_amount', '交易总额'),
      c.bigint('buyer_count', '购买用户数'),
      c.decimal('avg_order_amount', '平均客单价'),
      c.datetime('etl_time', 'ETL处理时间'),
    ],
  },
  {
    name: 'dws_risk_daily_summary_dd',
    comment: '风控事件日汇总表',
    layer: 'dws',
    domain: 'risk',
    columns: [
      c.pk('id', '汇总ID'),
      c.date('stat_date', '统计日期'),
      c.bigint('total_events', '事件总数'),
      c.bigint('high_risk_count', '高风险事件数'),
      c.bigint('blocked_count', '拦截数'),
      c.double('intercept_rate', '拦截率'),
      c.bigint('affected_users', '涉及用户数'),
      c.double('avg_risk_score', '平均风险评分'),
      c.datetime('etl_time', 'ETL处理时间'),
    ],
  },
  {
    name: 'dws_product_inventory_summary_dd',
    comment: '库存日汇总表',
    layer: 'dws',
    domain: 'product',
    columns: [
      c.pk('id', '汇总ID'),
      c.bigint('warehouse_id', '仓库ID'),
      c.date('stat_date', '统计日期'),
      c.bigint('total_sku_count', 'SKU总数'),
      c.bigint('out_of_stock_count', '缺货SKU数'),
      c.bigint('inbound_quantity', '入库数量'),
      c.bigint('outbound_quantity', '出库数量'),
      c.double('turnover_rate', '周转率'),
      c.datetime('etl_time', 'ETL处理时间'),
    ],
  },
];

/* ═══════════════════════════════════════════════════════════════
 * Metrics — 10 operational KPIs
 * ═══════════════════════════════════════════════════════════════ */
const metrics: MetricDef[] = [
  {
    name: 'registered_user_total',
    displayName: '注册用户总数',
    expression: 'COUNT(DISTINCT user_id)',
    metricType: 'atomic',
    sourceTable: 'ods_user_register_df',
    dimensions: ['register_source', 'gender'],
    granularity: ['day', 'month'],
    format: 'number',
    description: '平台累计注册用户数',
  },
  {
    name: 'active_product_count',
    displayName: '商品在架数量',
    expression: "COUNT(*) WHERE product_status = 'on_sale'",
    metricType: 'atomic',
    sourceTable: 'ods_product_info_df',
    filters: [{ column: 'product_status', op: '=', value: 'on_sale' }],
    dimensions: ['category_id', 'merchant_id'],
    format: 'number',
    description: '当前处于在售状态的商品总数',
  },
  {
    name: 'merchant_total',
    displayName: '商家总数',
    expression: 'COUNT(DISTINCT id)',
    metricType: 'atomic',
    sourceTable: 'dim_merchant',
    filters: [{ column: 'status', op: '=', value: '1' }],
    dimensions: ['merchant_type', 'merchant_level'],
    format: 'number',
    description: '平台有效商家数量',
  },
  {
    name: 'daily_order_count',
    displayName: '日订单量',
    expression: 'COUNT(DISTINCT order_id)',
    metricType: 'atomic',
    sourceTable: 'dwd_trade_order_detail_di',
    dimensions: ['channel', 'payment_method'],
    granularity: ['day'],
    format: 'number',
    description: '每日下单总数',
  },
  {
    name: 'daily_gmv',
    displayName: '日交易总额',
    expression: 'SUM(actual_amount)',
    metricType: 'atomic',
    sourceTable: 'dwd_trade_order_detail_di',
    filters: [{ column: 'order_status', op: '!=', value: 'cancelled' }],
    dimensions: ['channel', 'category_id'],
    granularity: ['day', 'month'],
    format: 'currency',
    description: '每日实际成交金额（不含取消订单）',
  },
  {
    name: 'refund_rate',
    displayName: '退款率',
    expression: 'COUNT(DISTINCT refund_id) / COUNT(DISTINCT order_id)',
    metricType: 'derived',
    sourceTable: 'dws_trade_merchant_summary_dd',
    dimensions: ['merchant_id'],
    granularity: ['day', 'month'],
    format: 'percentage',
    description: '退款订单占总订单的比例',
  },
  {
    name: 'avg_order_amount',
    displayName: '平均客单价',
    expression: 'SUM(actual_amount) / COUNT(DISTINCT order_id)',
    metricType: 'derived',
    sourceTable: 'dwd_trade_order_detail_di',
    dimensions: ['channel', 'category_id'],
    granularity: ['day', 'month'],
    format: 'currency',
    description: '每笔订单的平均实付金额',
  },
  {
    name: 'risk_intercept_rate',
    displayName: '风控拦截率',
    expression: "SUM(CASE WHEN action_taken = 'block' THEN 1 ELSE 0 END) / COUNT(*)",
    metricType: 'derived',
    sourceTable: 'dwd_risk_event_detail_di',
    dimensions: ['event_type', 'risk_level'],
    granularity: ['day'],
    format: 'percentage',
    description: '风控系统拦截事件占总风险事件的比例',
  },
  {
    name: 'sku_out_of_stock_rate',
    displayName: 'SKU缺货率',
    expression: 'out_of_stock_count / total_sku_count',
    metricType: 'derived',
    sourceTable: 'dws_product_inventory_summary_dd',
    dimensions: ['warehouse_id'],
    granularity: ['day'],
    format: 'percentage',
    description: '缺货SKU占总SKU的比例',
  },
  {
    name: 'avg_product_rating',
    displayName: '商品平均评分',
    expression: 'AVG(rating)',
    metricType: 'atomic',
    sourceTable: 'dwd_product_review_detail_di',
    dimensions: ['category_id', 'product_id'],
    granularity: ['day', 'month'],
    format: 'number',
    description: '商品评价的平均星级评分',
  },
];

/* ═══════════════════════════════════════════════════════════════
 * Glossary — 8 business terms
 * ═══════════════════════════════════════════════════════════════ */
const glossary: GlossaryDef[] = [
  {
    term: 'GMV',
    sqlExpression:
      "SUM(actual_amount) FROM dwd_trade_order_detail_di WHERE order_status != 'cancelled'",
    description: 'Gross Merchandise Volume，交易总额，指实际成交金额（排除取消订单）',
  },
  {
    term: '客单价',
    sqlExpression: 'SUM(actual_amount) / COUNT(DISTINCT order_id) FROM dwd_trade_order_detail_di',
    description: '平均每笔订单的实付金额，反映用户单次消费能力',
  },
  {
    term: 'ODS',
    sqlExpression: "SELECT table_name FROM information_schema.tables WHERE table_name LIKE 'ods_%'",
    description: 'Operational Data Store，操作数据层，直接从业务系统同步的原始数据，日全量/日增量',
  },
  {
    term: '在架商品',
    sqlExpression: "SELECT * FROM ods_product_info_df WHERE product_status = 'on_sale'",
    description: '当前处于"在售"状态、可被用户搜索和下单的商品',
  },
  {
    term: '有效商家',
    sqlExpression: "SELECT * FROM dim_merchant WHERE status = '1'",
    description: '状态为正常(status=1)、可正常经营的商家',
  },
  {
    term: '风控拦截',
    sqlExpression: "SELECT * FROM dwd_risk_event_detail_di WHERE action_taken = 'block'",
    description: '风控系统判定为高风险并执行拦截动作的事件',
  },
  {
    term: '日全量(df)',
    sqlExpression: "SELECT * FROM ods_trade_order_df WHERE ds = '${target_date}'",
    description: 'daily full snapshot，表名后缀 _df，每日全量快照，每天覆盖写入完整数据',
  },
  {
    term: '日增量(di)',
    sqlExpression: "SELECT * FROM ods_user_login_log_di WHERE ds = '${target_date}'",
    description: 'daily incremental，表名后缀 _di，每日增量数据，仅写入当天新增/变更记录',
  },
];

/* ═══════════════════════════════════════════════════════════════
 * Export — EngineSeedDefinition
 * ═══════════════════════════════════════════════════════════════ */
export const mysqlSeed: EngineSeedDefinition = {
  engineType: 'mysql',
  name: 'MySQL 业务库',
  description: '业务系统 MySQL 主库，承载 ODS 原始数据和 DIM 维度表',
  dialect: 'mysql',
  pgSchema: 'dw_mysql',
  tables: [...odsTables, ...dimTables, ...dwdTables, ...dwsTables],
  metrics,
  glossary,
};
